"""Tests for the style_engine pure pipeline-stage modules (seo phase).

Covers api.services.style_engine.pre_stage.run_pre_stage and
api.services.style_engine.post_stage.run_post_stage. All rule data and
sample text is synthetic -- built inline as StyleRules(raw=...), an inline
analyst speaker table, and inline seo_output.md-shaped report strings --
never depends on config/house_style.yaml. Mirrors the fixture/helper style
of tests/test_style_casing_entities.py and tests/test_style_scanner_limits.py.

Only the seo phase has behavior in this task; every other phase must
degrade gracefully to an empty/skipped passthrough (formatter/timestamp/etc.
are wired in by later tasks behind the same interface).
"""

from __future__ import annotations

from api.services.style_engine.phase_io import extract_seo_fields
from api.services.style_engine.post_stage import run_post_stage
from api.services.style_engine.pre_stage import run_pre_stage
from api.services.style_engine.rules import StyleRules

# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------


def _pre_rules(title_max: int = 42, **overrides) -> StyleRules:
    raw = {
        "meta": {"version": 1},
        "voice": {
            "forbidden_phrases": [
                {"match": "watch as", "category": "viewer_directive", "severity": "error"},
                {"match": "discover", "category": "viewer_directive", "severity": "error"},
                {"match": "will show", "category": "promise", "severity": "error"},
                {"match": "join us", "category": "cta", "severity": "error"},
                {"match": "amazing", "category": "superlative", "severity": "error"},
            ],
            "first_person_markers": [r"\bwe\b", r"\bour\b", r"\bus\b"],
            "second_person_markers": [r"\byou\b", r"\byour\b"],
        },
        "casing": {
            "style": "down",
            "proper_nouns": ["Wisconsin", "Governor", "Madison"],
            "acronyms": ["PBS"],
            "casing_variants": {"gov": "Gov."},
            "surname_stoplist": ["van", "der", "de", "la", "the"],
        },
        "limits": {
            "fields": {
                "title": {"max": title_max},
                "short_description": {"max": 90},
                "long_description": {"max": 350},
                "keywords": {"count": {"min": 15, "max": 20}},
                "social_tags": {},
            },
            "content_type_overrides": {},
        },
        "programs": {
            "Here & Now": {
                "short_description_formula": "{role} {verb} {subject}.",
                "verbs": {"elected": ["discusses"], "non_elected": ["explains", "describes", "considers"]},
            },
        },
    }
    raw.update(overrides)
    return StyleRules(raw=raw)


def _post_rules(title_max: int = 80, short_max: int = 90, long_max: int = 350) -> StyleRules:
    raw = {
        "meta": {"version": 1},
        "voice": {
            "forbidden_phrases": [
                {"match": "discover", "category": "viewer_directive", "severity": "error"},
                {"match": "watch as", "category": "viewer_directive", "severity": "error"},
            ],
            "first_person_markers": [r"\bwe\b", r"\bour\b"],
            "second_person_markers": [r"\byou\b"],
        },
        "casing": {
            "style": "down",
            "proper_nouns": ["Wisconsin", "Governor", "Madison"],
            "acronyms": ["PBS"],
            "casing_variants": {"gov": "Gov."},
            "surname_stoplist": ["van", "der", "de", "la", "the"],
        },
        "limits": {
            "fields": {
                "title": {"max": title_max},
                "short_description": {"max": short_max},
                "long_description": {"max": long_max},
            },
            "content_type_overrides": {},
        },
        "programs": {},
    }
    return StyleRules(raw=raw)


ANALYST_TABLE = """<!-- Provenance: Generated by cardigan-v4 analyst phase -->

## Speakers & Roles

| Speaker | Role/Title | Topic | Time |
|---|---|---|---|
| Nick Hoffman | Host | Budget debate | 1:20 |
| Angela Fitzgerald | Anchor | Weather | 5:40 |
"""

# Mentions Nick Hoffman (and thus the bare surname "Hoffman") but never
# Angela Fitzgerald -- used to prove keyword_candidates is transcript-verified.
TRANSCRIPT_TEXT = "Nick Hoffman opens the show discussing the state budget in Wisconsin."


def _seo_report(
    title: str,
    short_description: str = "A short description of the episode.",
    long_description: str = "A longer description of the episode content, spanning more detail than the short one.",
) -> str:
    return (
        "# SEO Report\n\n"
        "### Title (Final Recommendation)\n\n"
        "**Recommended:**\n"
        f"{title}\n\n"
        "**Character Count:** 0\n\n"
        "---\n\n"
        "### Short Description (150 chars max)\n\n"
        "**Recommended:**\n"
        f"{short_description}\n\n"
        "---\n\n"
        "### Long Description (300 chars max)\n\n"
        "**Recommended:**\n"
        f"{long_description}\n\n"
        "---\n"
    )


# ---------------------------------------------------------------------------
# run_pre_stage -- seo phase
# ---------------------------------------------------------------------------


class TestPreStageSeoData:
    def test_char_budgets_not_hardcoded(self):
        rules = _pre_rules(title_max=42)
        result = run_pre_stage("seo", {}, rules)
        assert result.data["char_budgets"]["title"] == 42
        assert result.data["char_budgets"]["short_description"] == 90
        assert result.data["char_budgets"]["long_description"] == 350
        # keywords is a count-limit (list field), not a char budget.
        assert "keywords" not in result.data["char_budgets"]

    def test_proper_nouns_from_analyst_table(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"analyst_output": ANALYST_TABLE}, rules)
        assert "Nick Hoffman" in result.data["proper_nouns"]
        assert "Angela Fitzgerald" in result.data["proper_nouns"]

    def test_keyword_candidates_only_transcript_verified(self):
        rules = _pre_rules()
        result = run_pre_stage(
            "seo",
            {"analyst_output": ANALYST_TABLE, "transcript": TRANSCRIPT_TEXT},
            rules,
        )
        assert "Nick Hoffman" in result.data["keyword_candidates"]
        assert "Angela Fitzgerald" not in result.data["keyword_candidates"]

    def test_program_rules_here_and_now(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"program": "Here & Now"}, rules)
        assert result.data["program_rules"]["short_description_formula"] == "{role} {verb} {subject}."

    def test_program_rules_empty_for_unknown_program(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"program": "Some Other Show"}, rules)
        assert result.data["program_rules"] == {}

    def test_program_rules_empty_when_no_program(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {}, rules)
        assert result.data["program_rules"] == {}


class TestPreStageSeoPromptSection:
    def test_char_budget_number_appears_in_prompt(self):
        rules = _pre_rules(title_max=42)
        result = run_pre_stage("seo", {}, rules)
        assert "42" in result.prompt_section

    def test_proper_nouns_appear_in_prompt(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"analyst_output": ANALYST_TABLE}, rules)
        assert "Nick Hoffman" in result.prompt_section
        assert "Angela Fitzgerald" in result.prompt_section

    def test_only_transcript_verified_keywords_appear(self):
        rules = _pre_rules()
        result = run_pre_stage(
            "seo",
            {"analyst_output": ANALYST_TABLE, "transcript": TRANSCRIPT_TEXT},
            rules,
        )
        assert "Nick Hoffman" in result.prompt_section
        # Only the keyword-candidates line should omit Fitzgerald -- proper
        # nouns line still lists her, so check both facts about data instead
        # of the full text.
        assert "Angela Fitzgerald" not in result.data["keyword_candidates"]

    def test_forbidden_examples_from_synthetic_categories(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {}, rules)
        assert "watch as" in result.prompt_section
        assert "discover" in result.prompt_section
        assert "will show" in result.prompt_section
        assert "join us" in result.prompt_section
        assert "amazing" in result.prompt_section

    def test_first_person_markers_appear(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {}, rules)
        assert "we" in result.prompt_section
        assert "our" in result.prompt_section

    def test_regex_forbidden_entry_renders_readable_not_raw_regex(self):
        # A regex-flagged forbidden_phrases entry (e.g. \bfree\b, mirroring
        # house_style.yaml's "sales" category) must render as a readable
        # phrase in the prompt, not raw regex syntax with \b anchors.
        rules = _pre_rules(
            voice={
                "forbidden_phrases": [
                    {"match": r"\bfree\b", "category": "sales", "severity": "warning", "regex": True},
                ],
                "first_person_markers": [],
                "second_person_markers": [],
            }
        )
        result = run_pre_stage("seo", {}, rules)
        assert "free" in result.prompt_section
        assert r"\b" not in result.prompt_section

    def test_here_and_now_program_block_present(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"program": "Here & Now"}, rules)
        assert "Program formula (Here & Now)" in result.prompt_section
        assert "discusses" in result.prompt_section

    def test_program_block_absent_for_other_program(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"program": "Some Other Show"}, rules)
        assert "Program formula" not in result.prompt_section

    def test_program_block_absent_when_no_program(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {}, rules)
        assert "Program formula" not in result.prompt_section

    def test_down_style_line_present(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {}, rules)
        assert "down style" in result.prompt_section.lower()


class TestPreStageGraceful:
    def test_no_analyst_output_renders_with_empty_nouns(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {}, rules)
        assert result.data["proper_nouns"] == []
        assert result.data["keyword_candidates"] == []
        assert result.prompt_section  # still renders, non-empty

    def test_none_analyst_output_does_not_raise(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"analyst_output": None}, rules)
        assert result.data["proper_nouns"] == []

    def test_no_transcript_yields_empty_keyword_candidates(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"analyst_output": ANALYST_TABLE}, rules)
        assert result.data["keyword_candidates"] == []

    def test_unknown_phase_returns_empty_result(self):
        rules = _pre_rules()
        result = run_pre_stage("timestamp", {}, rules)
        assert result.phase == "timestamp"
        assert result.prompt_section == ""
        assert result.data == {}

    def test_unknown_phase_ignores_context(self):
        rules = _pre_rules()
        result = run_pre_stage(
            "formatter", {"analyst_output": ANALYST_TABLE, "program": "Here & Now"}, rules
        )
        assert result.prompt_section == ""
        assert result.data == {}


# ---------------------------------------------------------------------------
# run_post_stage -- seo phase: end-to-end normalize
# ---------------------------------------------------------------------------


class TestPostStageEndToEndNormalize:
    def test_over_capitalized_title_normalized_and_spliced(self):
        rules = _post_rules()
        raw_title = "Wisconsin Governor Signs New Budget Bill In Madison"
        raw_output = _seo_report(raw_title)

        result = run_post_stage("seo", raw_output, {}, rules)

        assert result.changed is True
        assert len(result.check.fixes) == 1
        fix = result.check.fixes[0]
        assert fix.rule_id == "casing.down_style.title"
        assert fix.before == raw_title

        expected_title = "Wisconsin Governor signs new budget bill in Madison"
        assert fix.after == expected_title

        reparsed = extract_seo_fields(result.normalized_output)
        assert reparsed.title.value == expected_title

        # Rest of document is byte-identical outside the title's span.
        raw_fields = extract_seo_fields(raw_output)
        assert result.normalized_output[: raw_fields.title.start] == raw_output[: raw_fields.title.start]
        tail_start_new = raw_fields.title.start + len(expected_title)
        assert result.normalized_output[tail_start_new:] == raw_output[raw_fields.title.end :]

    def test_convergence_over_cap_and_over_lower_same_result(self):
        rules = _post_rules()
        over_cap = _seo_report("Wisconsin Governor Signs New Budget Bill In Madison")
        over_lower = _seo_report("wisconsin governor signs new budget bill in madison")

        result_cap = run_post_stage("seo", over_cap, {}, rules)
        result_lower = run_post_stage("seo", over_lower, {}, rules)

        title_cap = extract_seo_fields(result_cap.normalized_output).title.value
        title_lower = extract_seo_fields(result_lower.normalized_output).title.value
        assert title_cap == title_lower

    def test_already_clean_title_unchanged(self):
        rules = _post_rules()
        title = "Wisconsin Governor signs new budget bill in Madison"
        raw_output = _seo_report(title)

        result = run_post_stage("seo", raw_output, {}, rules)

        assert result.changed is False
        assert result.normalized_output == raw_output
        assert result.check.fixes == []


# ---------------------------------------------------------------------------
# run_post_stage -- seo phase: flag tier never rewrites
# ---------------------------------------------------------------------------


class TestPostStageFlagTierNeverRewrites:
    def test_over_limit_short_description_flagged_not_modified(self):
        rules = _post_rules(short_max=90)
        raw_title = "Wisconsin Governor signs new budget bill in Madison"
        over_limit_short_desc = "x" * 150
        raw_output = _seo_report(raw_title, short_description=over_limit_short_desc)

        result = run_post_stage("seo", raw_output, {}, rules)

        limit_violations = [v for v in result.check.violations if v.rule_id == "limits.short_description.max"]
        assert len(limit_violations) == 1
        assert limit_violations[0].severity == "error"

        reparsed = extract_seo_fields(result.normalized_output)
        assert reparsed.short_description.value == over_limit_short_desc

    def test_forbidden_phrase_in_title_flagged_but_word_kept(self):
        rules = _post_rules()
        raw_title = "Discover Wisconsin's Budget Story"
        raw_output = _seo_report(raw_title)

        result = run_post_stage("seo", raw_output, {}, rules)

        forbidden_violations = [
            v for v in result.check.violations if v.rule_id == "voice.forbidden.viewer_directive"
        ]
        assert len(forbidden_violations) == 1
        assert forbidden_violations[0].field == "title"

        reparsed = extract_seo_fields(result.normalized_output)
        # Casing-normalized only -- the forbidden word itself is never stripped.
        assert "discover" in reparsed.title.value.lower()

    def test_limit_violation_reflects_final_title_not_raw(self):
        # title_max=9: raw "gov evers" is exactly 9 chars (no violation on
        # the raw value), but down-styling expands "gov" -> "Gov." (adds a
        # period), making the FINAL title 10 chars -- over the limit. The
        # violation must be computed against the final (post-normalization)
        # value, not the raw one.
        rules = _post_rules(title_max=9)
        raw_title = "gov evers"
        assert len(raw_title) == 9
        raw_output = _seo_report(raw_title)

        result = run_post_stage("seo", raw_output, {}, rules)

        final_title = extract_seo_fields(result.normalized_output).title.value
        assert final_title == "Gov. evers"
        assert len(final_title) == 10

        title_violations = [v for v in result.check.violations if v.rule_id == "limits.title.max"]
        assert len(title_violations) == 1
        assert "10" in title_violations[0].message


# ---------------------------------------------------------------------------
# run_post_stage -- seo phase: malformed input / unknown phase
# ---------------------------------------------------------------------------


class TestPostStageUnparseable:
    def test_unparseable_report_passthrough_no_raise(self):
        rules = _post_rules()
        raw_output = "# SEO Report\n\nNo recommendations generated.\n"

        result = run_post_stage("seo", raw_output, {}, rules)

        assert result.check.parse_ok is False
        assert result.normalized_output == raw_output
        assert result.changed is False
        assert len(result.check.violations) == 1
        violation = result.check.violations[0]
        assert violation.rule_id == "phase_io.seo.unparseable"
        assert violation.severity == "warning"
        assert violation.model_fixable is True

    def test_empty_report_does_not_raise(self):
        rules = _post_rules()
        result = run_post_stage("seo", "", {}, rules)
        assert result.check.parse_ok is False
        assert result.normalized_output == ""


class TestPostStageUnknownPhase:
    def test_unknown_phase_skipped_passthrough(self):
        rules = _post_rules()
        raw_output = "irrelevant content for a phase with no registered behavior"

        result = run_post_stage("timestamp", raw_output, {}, rules)

        assert result.check.skipped is True
        assert result.normalized_output == raw_output
        assert result.changed is False
        assert result.check.violations == []
        assert result.check.fixes == []
