"""Tests for the style_engine SEO field extractor (span-aware).

Covers api.services.style_engine.phase_io: extract_seo_fields, FieldSpan,
SeoFields. Port/extension of scripts/poc_house_style_normalizer.py's
extract_recommended, extended to return exact character spans into the
source document (so a later stage can splice normalized values back in
place). All sample seo_output.md text is synthetic, built inline to mirror
the real prompts/seo.md output template shape (including its parenthetical
heading suffixes like "### Title (Final Recommendation)").
"""

from __future__ import annotations

from api.services.style_engine.phase_io import FieldSpan, SeoFields, extract_seo_fields

# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------

REALISTIC_SEO_MD = """<!-- Provenance: Generated by cardigan-v4 seo phase -->

# SEO Report
**Project:** TEST123
**Program:** Here & Now
**Date Processed:** 2026-07-10
**Agent:** seo-specialist
**Model:** anthropic/claude-sonnet-5

---

## Optimized Metadata

### Title (Final Recommendation)

**Recommended:**
Wisconsin Governor Signs New Budget Bill

**Character Count:** 42/60

**Keywords Included:** budget, Wisconsin, governor

**Reasoning:**
Leads with the primary keyword and stays well under the limit.

**Alternatives:**
1. Gov. Evers Signs State Budget Into Law
2. New Wisconsin Budget Bill Becomes Law

---

### Short Description (150 chars max)

**Recommended:**
Gov. Tony Evers signs the state budget, outlining new investments in education and infrastructure across Wisconsin.

**Character Count:** 118/150

**Keywords Included:** budget, education, infrastructure

---

### Long Description (300 chars max)

**Recommended:**
Wisconsin Gov. Tony Evers signs a new state budget bill, directing significant new investments toward public education, transportation infrastructure, and rural broadband access across the state, following months of bipartisan negotiation.

**Character Count:** 240/300

**Keywords Included:** budget, education, broadband

---
"""

NO_COMMENT_SEO_MD = REALISTIC_SEO_MD.split("-->\n\n", 1)[1]

MISSING_LONG_DESC_SEO_MD = """# SEO Report

### Title (Final Recommendation)

**Recommended:**
Wisconsin Governor Signs New Budget Bill

**Character Count:** 42/60

---

### Short Description (150 chars max)

**Recommended:**
Gov. Tony Evers signs the state budget today.

**Character Count:** 46/150
"""

EMPTY_SEO_MD = "# SEO Report\n\nNo recommendations generated.\n"


# ---------------------------------------------------------------------------
# extract_seo_fields -- round-trip span fidelity
# ---------------------------------------------------------------------------


class TestSpanFidelity:
    def test_title_span_exact(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        assert fields.title is not None
        assert fields.title.value == "Wisconsin Governor Signs New Budget Bill"
        assert REALISTIC_SEO_MD[fields.title.start : fields.title.end] == fields.title.value

    def test_short_description_span_exact(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        assert fields.short_description is not None
        expected = (
            "Gov. Tony Evers signs the state budget, outlining new investments "
            "in education and infrastructure across Wisconsin."
        )
        assert fields.short_description.value == expected
        assert (
            REALISTIC_SEO_MD[fields.short_description.start : fields.short_description.end]
            == fields.short_description.value
        )

    def test_long_description_span_exact(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        assert fields.long_description is not None
        assert (
            REALISTIC_SEO_MD[fields.long_description.start : fields.long_description.end]
            == fields.long_description.value
        )
        assert fields.long_description.value.startswith("Wisconsin Gov. Tony Evers signs")

    def test_all_three_spans_hold_simultaneously(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        for span in (fields.title, fields.short_description, fields.long_description):
            assert span is not None
            assert REALISTIC_SEO_MD[span.start : span.end] == span.value


# ---------------------------------------------------------------------------
# extract_seo_fields -- missing sections
# ---------------------------------------------------------------------------


class TestMissingSections:
    def test_missing_long_description_is_none(self):
        fields = extract_seo_fields(MISSING_LONG_DESC_SEO_MD)
        assert fields.title is not None
        assert fields.short_description is not None
        assert fields.long_description is None

    def test_no_recommendations_all_none(self):
        fields = extract_seo_fields(EMPTY_SEO_MD)
        assert fields.title is None
        assert fields.short_description is None
        assert fields.long_description is None

    def test_empty_document_all_none(self):
        fields = extract_seo_fields("")
        assert fields.title is None
        assert fields.short_description is None
        assert fields.long_description is None

    def test_missing_never_raises(self):
        # Graceful: malformed/partial input must not raise.
        extract_seo_fields("### Title\n\nNo recommended line here.\n")


# ---------------------------------------------------------------------------
# extract_seo_fields -- provenance header tolerance
# ---------------------------------------------------------------------------


class TestProvenanceHeaderTolerance:
    def test_leading_comment_does_not_break_extraction(self):
        with_comment = extract_seo_fields(REALISTIC_SEO_MD)
        without_comment = extract_seo_fields(NO_COMMENT_SEO_MD)
        assert with_comment.title.value == without_comment.title.value
        assert with_comment.short_description.value == without_comment.short_description.value
        assert with_comment.long_description.value == without_comment.long_description.value

    def test_leading_comment_shifts_but_preserves_span_validity(self):
        with_comment = extract_seo_fields(REALISTIC_SEO_MD)
        without_comment = extract_seo_fields(NO_COMMENT_SEO_MD)
        # The comment adds a prefix, so the with-comment span must start
        # later in the document, but must still be exact for its own text.
        assert with_comment.title.start > without_comment.title.start
        assert (
            REALISTIC_SEO_MD[with_comment.title.start : with_comment.title.end]
            == with_comment.title.value
        )


# ---------------------------------------------------------------------------
# SeoFields.to_dict / FieldSpan
# ---------------------------------------------------------------------------


class TestSeoFieldsToDict:
    def test_to_dict_shape_with_values(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        d = fields.to_dict()
        assert d["title"]["value"] == "Wisconsin Governor Signs New Budget Bill"
        assert isinstance(d["title"]["start"], int)
        assert isinstance(d["title"]["end"], int)

    def test_to_dict_none_for_missing_fields(self):
        fields = extract_seo_fields(EMPTY_SEO_MD)
        d = fields.to_dict()
        assert d["title"] is None
        assert d["short_description"] is None
        assert d["long_description"] is None

    def test_field_span_is_plain_dataclass(self):
        span = FieldSpan(value="Hello", start=0, end=5)
        assert span.value == "Hello"
        assert span.start == 0
        assert span.end == 5

    def test_seo_fields_defaults_all_none(self):
        fields = SeoFields()
        assert fields.title is None
        assert fields.short_description is None
        assert fields.long_description is None
