"""Tests for the style_engine pure pipeline-stage modules (seo, validator,
formatter, timestamp phases).

Covers api.services.style_engine.pre_stage.run_pre_stage and
api.services.style_engine.post_stage.run_post_stage. All rule data and
sample text is synthetic -- built inline as StyleRules(raw=...), an inline
analyst speaker table, and inline seo_output.md-shaped report strings --
never depends on config/house_style.yaml. Mirrors the fixture/helper style
of tests/test_style_casing_entities.py and tests/test_style_scanner_limits.py.

seo, validator, formatter, and timestamp phases have behavior; any other
phase name (e.g. "widget", used below as a stand-in for a genuinely
unregistered phase) must degrade gracefully to an empty/skipped passthrough.
Unit-level coverage of the timestamp phase's pure timecode math and chapter
parse/emit machinery (timecodes.py, phase_io.py's chapter functions) lives
in tests/test_style_timecodes_io.py -- this file only covers pre_stage.py /
post_stage.py's timestamp integration (SRT-driven candidate extraction, the
parse -> snap -> case-normalize -> emit pipeline, and violation surfacing).
"""

from __future__ import annotations

from api.services.style_engine.phase_io import extract_seo_fields
from api.services.style_engine.post_stage import run_post_stage
from api.services.style_engine.pre_stage import run_pre_stage
from api.services.style_engine.rules import StyleRules
from api.services.style_engine.timecodes import format_media_manager, format_youtube

# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------


def _pre_rules(title_max: int = 42, **overrides) -> StyleRules:
    raw = {
        "meta": {"version": 1},
        "voice": {
            "forbidden_phrases": [
                {"match": "watch as", "category": "viewer_directive", "severity": "error"},
                {"match": "discover", "category": "viewer_directive", "severity": "error"},
                {"match": "will show", "category": "promise", "severity": "error"},
                {"match": "join us", "category": "cta", "severity": "error"},
                {"match": "amazing", "category": "superlative", "severity": "error"},
            ],
            "first_person_markers": [r"\bwe\b", r"\bour\b", r"\bus\b"],
            "second_person_markers": [r"\byou\b", r"\byour\b"],
        },
        "casing": {
            "style": "down",
            "proper_nouns": ["Wisconsin", "Governor", "Madison"],
            "acronyms": ["PBS"],
            "casing_variants": {"gov": "Gov."},
            "surname_stoplist": ["van", "der", "de", "la", "the"],
        },
        "limits": {
            "fields": {
                "title": {"max": title_max},
                "short_description": {"max": 90},
                "long_description": {"max": 350},
                "keywords": {"count": {"min": 15, "max": 20}},
                "social_tags": {},
            },
            "content_type_overrides": {},
        },
        "programs": {
            "Here & Now": {
                "short_description_formula": "{role} {verb} {subject}.",
                "verbs": {"elected": ["discusses"], "non_elected": ["explains", "describes", "considers"]},
            },
        },
    }
    raw.update(overrides)
    return StyleRules(raw=raw)


def _post_rules(title_max: int = 80, short_max: int = 90, long_max: int = 350) -> StyleRules:
    raw = {
        "meta": {"version": 1},
        "voice": {
            "forbidden_phrases": [
                {"match": "discover", "category": "viewer_directive", "severity": "error"},
                {"match": "watch as", "category": "viewer_directive", "severity": "error"},
            ],
            "first_person_markers": [r"\bwe\b", r"\bour\b"],
            "second_person_markers": [r"\byou\b"],
        },
        "casing": {
            "style": "down",
            "proper_nouns": ["Wisconsin", "Governor", "Madison"],
            "acronyms": ["PBS"],
            "casing_variants": {"gov": "Gov."},
            "surname_stoplist": ["van", "der", "de", "la", "the"],
        },
        "limits": {
            "fields": {
                "title": {"max": title_max},
                "short_description": {"max": short_max},
                "long_description": {"max": long_max},
            },
            "content_type_overrides": {},
        },
        "programs": {},
    }
    return StyleRules(raw=raw)


ANALYST_TABLE = """<!-- Provenance: Generated by cardigan-v4 analyst phase -->

## Speakers & Roles

| Speaker | Role/Title | Topic | Time |
|---|---|---|---|
| Nick Hoffman | Host | Budget debate | 1:20 |
| Angela Fitzgerald | Anchor | Weather | 5:40 |
"""

# Mentions Nick Hoffman (and thus the bare surname "Hoffman") but never
# Angela Fitzgerald -- used to prove keyword_candidates is transcript-verified.
TRANSCRIPT_TEXT = "Nick Hoffman opens the show discussing the state budget in Wisconsin."


def _seo_report(
    title: str,
    short_description: str = "A short description of the episode.",
    long_description: str = "A longer description of the episode content, spanning more detail than the short one.",
) -> str:
    return (
        "# SEO Report\n\n"
        "### Title (Final Recommendation)\n\n"
        "**Recommended:**\n"
        f"{title}\n\n"
        "**Character Count:** 0\n\n"
        "---\n\n"
        "### Short Description (150 chars max)\n\n"
        "**Recommended:**\n"
        f"{short_description}\n\n"
        "---\n\n"
        "### Long Description (300 chars max)\n\n"
        "**Recommended:**\n"
        f"{long_description}\n\n"
        "---\n"
    )


# ---------------------------------------------------------------------------
# run_pre_stage -- seo phase
# ---------------------------------------------------------------------------


class TestPreStageSeoData:
    def test_char_budgets_not_hardcoded(self):
        rules = _pre_rules(title_max=42)
        result = run_pre_stage("seo", {}, rules)
        assert result.data["char_budgets"]["title"] == 42
        assert result.data["char_budgets"]["short_description"] == 90
        assert result.data["char_budgets"]["long_description"] == 350
        # keywords is a count-limit (list field), not a char budget.
        assert "keywords" not in result.data["char_budgets"]

    def test_proper_nouns_from_analyst_table(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"analyst_output": ANALYST_TABLE}, rules)
        assert "Nick Hoffman" in result.data["proper_nouns"]
        assert "Angela Fitzgerald" in result.data["proper_nouns"]

    def test_keyword_candidates_only_transcript_verified(self):
        rules = _pre_rules()
        result = run_pre_stage(
            "seo",
            {"analyst_output": ANALYST_TABLE, "transcript": TRANSCRIPT_TEXT},
            rules,
        )
        assert "Nick Hoffman" in result.data["keyword_candidates"]
        assert "Angela Fitzgerald" not in result.data["keyword_candidates"]

    def test_program_rules_here_and_now(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"program": "Here & Now"}, rules)
        assert result.data["program_rules"]["short_description_formula"] == "{role} {verb} {subject}."

    def test_program_rules_empty_for_unknown_program(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"program": "Some Other Show"}, rules)
        assert result.data["program_rules"] == {}

    def test_program_rules_empty_when_no_program(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {}, rules)
        assert result.data["program_rules"] == {}


class TestPreStageSeoPromptSection:
    def test_char_budget_number_appears_in_prompt(self):
        rules = _pre_rules(title_max=42)
        result = run_pre_stage("seo", {}, rules)
        assert "42" in result.prompt_section

    def test_proper_nouns_appear_in_prompt(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"analyst_output": ANALYST_TABLE}, rules)
        assert "Nick Hoffman" in result.prompt_section
        assert "Angela Fitzgerald" in result.prompt_section

    def test_only_transcript_verified_keywords_appear(self):
        rules = _pre_rules()
        result = run_pre_stage(
            "seo",
            {"analyst_output": ANALYST_TABLE, "transcript": TRANSCRIPT_TEXT},
            rules,
        )
        assert "Nick Hoffman" in result.prompt_section
        # Only the keyword-candidates line should omit Fitzgerald -- proper
        # nouns line still lists her, so check both facts about data instead
        # of the full text.
        assert "Angela Fitzgerald" not in result.data["keyword_candidates"]

    def test_forbidden_examples_from_synthetic_categories(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {}, rules)
        assert "watch as" in result.prompt_section
        assert "discover" in result.prompt_section
        assert "will show" in result.prompt_section
        assert "join us" in result.prompt_section
        assert "amazing" in result.prompt_section

    def test_first_person_markers_appear(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {}, rules)
        assert "we" in result.prompt_section
        assert "our" in result.prompt_section

    def test_regex_forbidden_entry_renders_readable_not_raw_regex(self):
        # A regex-flagged forbidden_phrases entry (e.g. \bfree\b, mirroring
        # house_style.yaml's "sales" category) must render as a readable
        # phrase in the prompt, not raw regex syntax with \b anchors.
        rules = _pre_rules(
            voice={
                "forbidden_phrases": [
                    {"match": r"\bfree\b", "category": "sales", "severity": "warning", "regex": True},
                ],
                "first_person_markers": [],
                "second_person_markers": [],
            }
        )
        result = run_pre_stage("seo", {}, rules)
        assert "free" in result.prompt_section
        assert r"\b" not in result.prompt_section

    def test_here_and_now_program_block_present(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"program": "Here & Now"}, rules)
        assert "Program formula (Here & Now)" in result.prompt_section
        assert "discusses" in result.prompt_section

    def test_program_block_absent_for_other_program(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"program": "Some Other Show"}, rules)
        assert "Program formula" not in result.prompt_section

    def test_program_block_absent_when_no_program(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {}, rules)
        assert "Program formula" not in result.prompt_section

    def test_down_style_line_present(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {}, rules)
        assert "down style" in result.prompt_section.lower()


class TestPreStageGraceful:
    def test_no_analyst_output_renders_with_empty_nouns(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {}, rules)
        assert result.data["proper_nouns"] == []
        assert result.data["keyword_candidates"] == []
        assert result.prompt_section  # still renders, non-empty

    def test_none_analyst_output_does_not_raise(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"analyst_output": None}, rules)
        assert result.data["proper_nouns"] == []

    def test_no_transcript_yields_empty_keyword_candidates(self):
        rules = _pre_rules()
        result = run_pre_stage("seo", {"analyst_output": ANALYST_TABLE}, rules)
        assert result.data["keyword_candidates"] == []

    def test_unknown_phase_returns_empty_result(self):
        rules = _pre_rules()
        result = run_pre_stage("widget", {}, rules)
        assert result.phase == "widget"
        assert result.prompt_section == ""
        assert result.data == {}

    def test_unknown_phase_ignores_context(self):
        # "formatter"/"timestamp" now have real behavior -- "widget" stands
        # in for a genuinely unregistered phase and must degrade gracefully
        # regardless of context contents.
        rules = _pre_rules()
        result = run_pre_stage("widget", {"analyst_output": ANALYST_TABLE, "program": "Here & Now"}, rules)
        assert result.prompt_section == ""
        assert result.data == {}


# ---------------------------------------------------------------------------
# run_post_stage -- seo phase: end-to-end normalize
# ---------------------------------------------------------------------------


class TestPostStageEndToEndNormalize:
    def test_over_capitalized_title_normalized_and_spliced(self):
        rules = _post_rules()
        raw_title = "Wisconsin Governor Signs New Budget Bill In Madison"
        raw_output = _seo_report(raw_title)

        result = run_post_stage("seo", raw_output, {}, rules)

        assert result.changed is True
        assert len(result.check.fixes) == 1
        fix = result.check.fixes[0]
        assert fix.rule_id == "casing.down_style.title"
        assert fix.before == raw_title

        expected_title = "Wisconsin Governor signs new budget bill in Madison"
        assert fix.after == expected_title

        reparsed = extract_seo_fields(result.normalized_output)
        assert reparsed.title.value == expected_title

        # Rest of document is byte-identical outside the title's span.
        raw_fields = extract_seo_fields(raw_output)
        assert result.normalized_output[: raw_fields.title.start] == raw_output[: raw_fields.title.start]
        tail_start_new = raw_fields.title.start + len(expected_title)
        assert result.normalized_output[tail_start_new:] == raw_output[raw_fields.title.end :]

    def test_convergence_over_cap_and_over_lower_same_result(self):
        rules = _post_rules()
        over_cap = _seo_report("Wisconsin Governor Signs New Budget Bill In Madison")
        over_lower = _seo_report("wisconsin governor signs new budget bill in madison")

        result_cap = run_post_stage("seo", over_cap, {}, rules)
        result_lower = run_post_stage("seo", over_lower, {}, rules)

        title_cap = extract_seo_fields(result_cap.normalized_output).title.value
        title_lower = extract_seo_fields(result_lower.normalized_output).title.value
        assert title_cap == title_lower

    def test_already_clean_title_unchanged(self):
        rules = _post_rules()
        title = "Wisconsin Governor signs new budget bill in Madison"
        raw_output = _seo_report(title)

        result = run_post_stage("seo", raw_output, {}, rules)

        assert result.changed is False
        assert result.normalized_output == raw_output
        assert result.check.fixes == []


# ---------------------------------------------------------------------------
# run_post_stage -- seo phase: flag tier never rewrites
# ---------------------------------------------------------------------------


class TestPostStageFlagTierNeverRewrites:
    def test_forbidden_phrase_in_title_flagged_but_word_kept(self):
        rules = _post_rules()
        raw_title = "Discover Wisconsin's Budget Story"
        raw_output = _seo_report(raw_title)

        result = run_post_stage("seo", raw_output, {}, rules)

        forbidden_violations = [v for v in result.check.violations if v.rule_id == "voice.forbidden.viewer_directive"]
        assert len(forbidden_violations) == 1
        assert forbidden_violations[0].field == "title"

        reparsed = extract_seo_fields(result.normalized_output)
        # Casing-normalized only -- the forbidden word itself is never stripped.
        assert "discover" in reparsed.title.value.lower()

    def test_limit_violation_reflects_final_title_not_raw(self):
        # title_max=9: raw "gov evers" is exactly 9 chars (no violation on
        # the raw value), but down-styling expands "gov" -> "Gov." (adds a
        # period), making the FINAL title 10 chars -- over the limit. The
        # violation must be computed against the final (post-normalization)
        # value, not the raw one.
        rules = _post_rules(title_max=9)
        raw_title = "gov evers"
        assert len(raw_title) == 9
        raw_output = _seo_report(raw_title)

        result = run_post_stage("seo", raw_output, {}, rules)

        final_title = extract_seo_fields(result.normalized_output).title.value
        assert final_title == "Gov. evers"
        assert len(final_title) == 10

        title_violations = [v for v in result.check.violations if v.rule_id == "limits.title.max"]
        assert len(title_violations) == 1
        assert "10" in title_violations[0].message


class TestPostStageSeoLengthEnforcement:
    """seo over-limit descriptions are truncated to fit (enforce tier), so the
    Recommended value the SST write path consumes is always length-compliant."""

    def test_over_limit_short_description_truncated(self):
        rules = _post_rules(short_max=90)
        over = (
            "Ojibwe dancer and designer Aerius Benton-Banai shares how jingle dress dancing healed her whole community."
        )
        assert len(over) > 90
        raw_output = _seo_report("A down-style title", short_description=over)

        result = run_post_stage("seo", raw_output, {}, rules)

        final = extract_seo_fields(result.normalized_output).short_description.value
        assert len(final) <= 90
        assert final.endswith("…")
        assert final[:-1] in over  # a clean prefix of the original — never reworded
        assert "limits.short_description.truncated" in [f.rule_id for f in result.check.fixes]
        assert [v for v in result.check.violations if v.rule_id == "limits.short_description.max"] == []
        assert result.changed is True

    def test_over_limit_long_description_truncated(self):
        rules = _post_rules(long_max=120)
        over = ("word " * 40).strip()  # ~195 chars
        raw_output = _seo_report("A title", long_description=over)

        result = run_post_stage("seo", raw_output, {}, rules)

        final = extract_seo_fields(result.normalized_output).long_description.value
        assert len(final) <= 120
        assert "limits.long_description.truncated" in [f.rule_id for f in result.check.fixes]
        assert [v for v in result.check.violations if v.rule_id == "limits.long_description.max"] == []

    def test_within_limit_description_untouched(self):
        rules = _post_rules(short_max=90)
        ok = "A short, compliant description of the episode."
        raw_output = _seo_report("A title", short_description=ok)

        result = run_post_stage("seo", raw_output, {}, rules)

        final = extract_seo_fields(result.normalized_output).short_description.value
        assert final == ok
        assert [f for f in result.check.fixes if "truncated" in f.rule_id] == []

    def test_single_long_token_hard_cut(self):
        rules = _post_rules(short_max=20)
        raw_output = _seo_report("A title", short_description="x" * 150)  # no word boundaries

        result = run_post_stage("seo", raw_output, {}, rules)

        final = extract_seo_fields(result.normalized_output).short_description.value
        assert len(final) <= 20
        assert final.endswith("…")


# ---------------------------------------------------------------------------
# run_post_stage -- seo phase: malformed input / unknown phase
# ---------------------------------------------------------------------------


class TestPostStageUnparseable:
    def test_unparseable_report_passthrough_no_raise(self):
        rules = _post_rules()
        raw_output = "# SEO Report\n\nNo recommendations generated.\n"

        result = run_post_stage("seo", raw_output, {}, rules)

        assert result.check.parse_ok is False
        assert result.normalized_output == raw_output
        assert result.changed is False
        assert len(result.check.violations) == 1
        violation = result.check.violations[0]
        assert violation.rule_id == "phase_io.seo.unparseable"
        assert violation.severity == "warning"
        assert violation.model_fixable is True

    def test_empty_report_does_not_raise(self):
        rules = _post_rules()
        result = run_post_stage("seo", "", {}, rules)
        assert result.check.parse_ok is False
        assert result.normalized_output == ""


class TestPostStageUnknownPhase:
    def test_unknown_phase_skipped_passthrough(self):
        rules = _post_rules()
        raw_output = "irrelevant content for a phase with no registered behavior"

        result = run_post_stage("widget", raw_output, {}, rules)

        assert result.check.skipped is True
        assert result.normalized_output == raw_output
        assert result.changed is False
        assert result.check.violations == []
        assert result.check.fixes == []


# ---------------------------------------------------------------------------
# run_pre_stage -- validator phase (task 2a)
# ---------------------------------------------------------------------------


def _validator_rules(semantic_checks: list[str] | None = None) -> StyleRules:
    if semantic_checks is None:
        semantic_checks = ["title accurately reflects content", "description accurately reflects content"]
    raw = {
        "meta": {"version": 1},
        "phases": {"validator": {"semantic_checks": semantic_checks}},
    }
    return StyleRules(raw=raw)


def _style_check(*violations: dict) -> dict:
    return {"phase": "seo", "violations": list(violations), "fixes": [], "parse_ok": True, "skipped": False}


def _violation_dict(severity: str) -> dict:
    return {
        "rule_id": "lint.seo.title_over_limit",
        "phase": "seo",
        "severity": severity,
        "message": "irrelevant for these tests",
        "field": "title",
        "span": None,
        "model_fixable": True,
    }


class TestPreStageValidatorEmpty:
    def test_no_style_checks_key_returns_empty_result(self):
        rules = _validator_rules()
        result = run_pre_stage("validator", {}, rules)
        assert result.phase == "validator"
        assert result.prompt_section == ""
        assert result.data == {}

    def test_none_style_checks_returns_empty_result(self):
        rules = _validator_rules()
        result = run_pre_stage("validator", {"style_checks": None}, rules)
        assert result.prompt_section == ""
        assert result.data == {}

    def test_empty_dict_style_checks_returns_empty_result(self):
        rules = _validator_rules()
        result = run_pre_stage("validator", {"style_checks": {}}, rules)
        assert result.prompt_section == ""
        assert result.data == {}


class TestPreStageValidatorPromptSection:
    def test_section_header_present(self):
        rules = _validator_rules()
        style_checks = {"seo": _style_check(_violation_dict("error"))}
        result = run_pre_stage("validator", {"style_checks": style_checks}, rules)
        assert "## Deterministic checks already performed" in result.prompt_section

    def test_per_phase_summary_counts_error_and_warning_flags(self):
        rules = _validator_rules()
        style_checks = {
            "seo": _style_check(_violation_dict("error"), _violation_dict("error"), _violation_dict("warning")),
        }
        result = run_pre_stage("validator", {"style_checks": style_checks}, rules)
        assert "seo: 2 error flag(s), 1 warning(s)" in result.prompt_section
        assert "mechanical limits/casing already enforced/flagged by the pipeline" in result.prompt_section

    def test_multiple_phases_each_summarized(self):
        rules = _validator_rules()
        style_checks = {
            "seo": _style_check(_violation_dict("error")),
            "formatter": _style_check(_violation_dict("warning")),
        }
        result = run_pre_stage("validator", {"style_checks": style_checks}, rules)
        assert "seo: 1 error flag(s), 0 warning(s)" in result.prompt_section
        assert "formatter: 0 error flag(s), 1 warning(s)" in result.prompt_section

    def test_phase_with_zero_violations_still_summarized(self):
        rules = _validator_rules()
        style_checks = {"analyst": _style_check()}
        result = run_pre_stage("validator", {"style_checks": style_checks}, rules)
        assert "analyst: 0 error flag(s), 0 warning(s)" in result.prompt_section

    def test_instruction_do_not_recheck_mechanics_present(self):
        rules = _validator_rules()
        style_checks = {"seo": _style_check(_violation_dict("error"))}
        result = run_pre_stage("validator", {"style_checks": style_checks}, rules)
        assert (
            "Do NOT re-check character limits, casing, or format mechanics — they are handled "
            "deterministically." in result.prompt_section
        )

    def test_default_two_semantic_checks_render_exact_instruction_text(self):
        rules = _validator_rules()  # default: title + description
        style_checks = {"seo": _style_check(_violation_dict("error"))}
        result = run_pre_stage("validator", {"style_checks": style_checks}, rules)
        assert (
            "Judge ONLY: (1) title accurately reflects content; "
            "(2) description accurately reflects content; keywords relevant to content."
        ) in result.prompt_section

    def test_semantic_checks_are_data_driven_not_hardcoded(self):
        # A synthetic, unrelated semantic_checks list must show up verbatim --
        # proves the (1)/(2)/... list is rendered from rules, not hardcoded.
        rules = _validator_rules(
            semantic_checks=["tone matches house style", "no fabricated claims", "keywords appear naturally"]
        )
        style_checks = {"seo": _style_check(_violation_dict("error"))}
        result = run_pre_stage("validator", {"style_checks": style_checks}, rules)
        assert (
            "(1) tone matches house style; (2) no fabricated claims; (3) keywords appear naturally; "
            "keywords relevant to content."
        ) in result.prompt_section

    def test_empty_semantic_checks_list_still_renders_fixed_suffix(self):
        rules = _validator_rules(semantic_checks=[])
        style_checks = {"seo": _style_check(_violation_dict("error"))}
        result = run_pre_stage("validator", {"style_checks": style_checks}, rules)
        assert "Judge ONLY: keywords relevant to content." in result.prompt_section

    def test_data_carries_style_checks_summary(self):
        rules = _validator_rules()
        style_checks = {
            "seo": _style_check(_violation_dict("error"), _violation_dict("warning")),
        }
        result = run_pre_stage("validator", {"style_checks": style_checks}, rules)
        assert result.data["style_checks_summary"]["seo"] == {"error_count": 1, "warning_count": 1}


# ---------------------------------------------------------------------------
# run_pre_stage / run_post_stage -- formatter phase (task 3a)
# ---------------------------------------------------------------------------

_FORMATTER_SUBSTITUTIONS = [
    {"find": r"\b[Oo]kay\b", "replace": "OK", "tier": "enforce"},
    {"find": r"\bSenator\b", "replace": "Sen.", "tier": "enforce"},
    {"find": r"\bLiberals\b", "replace": "liberals", "tier": "enforce", "note": "sentence-initial guard applies"},
    {
        "id": "de_italicize_program_names",
        "find": r"\*(Wisconsin Life|Here & Now)\*",
        "replace": r"\1",
        "tier": "enforce",
        "note": "strips markdown italics around known program names; replace is a backreference to the matched name",
    },
    {
        "id": "oxford_comma",
        "detect": r",\s+and\b",
        "tier": "flag",
        "severity": "warning",
        "note": "no Oxford comma in lists",
    },
    {
        "id": "capitol_capital",
        "detect": r"\bcapital\b",
        "tier": "flag",
        "severity": "warning",
        "note": "'Capitol' vs 'capital'",
    },
]

_FORMATTER_SPEAKER_LABEL_SPEC = {
    "pattern": r"^\*\*[A-Z][\w.'-]+(?: [A-Z][\w.'-]+)+:\*\*",
    "trailing_spaces": 2,
    "blank_lines_between_turns": 1,
    "no_honorifics": True,
}


def _formatter_rules(
    substitutions: list[dict] | None = None,
    speaker_label: dict | None = None,
    review_notes: dict | None = None,
) -> StyleRules:
    raw = {
        "meta": {"version": 1},
        "phases": {
            "formatter": {
                "substitutions": _FORMATTER_SUBSTITUTIONS if substitutions is None else substitutions,
                "speaker_label": _FORMATTER_SPEAKER_LABEL_SPEC if speaker_label is None else speaker_label,
                "review_notes": (
                    {"placement": "top", "format": "html_comment", "tier": "flag"}
                    if review_notes is None
                    else review_notes
                ),
            }
        },
        "casing": {"surname_stoplist": []},
    }
    return StyleRules(raw=raw)


class TestPreStageFormatterData:
    def test_proper_nouns_from_analyst_table(self):
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {"analyst_output": ANALYST_TABLE}, rules)
        assert result.phase == "formatter"
        assert "Nick Hoffman" in result.data["proper_nouns"]
        assert "Angela Fitzgerald" in result.data["proper_nouns"]

    def test_speaker_label_spec_carries_raw_values(self):
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {}, rules)
        spec = result.data["speaker_label_spec"]
        assert spec["trailing_spaces"] == 2
        assert spec["blank_lines_between_turns"] == 1
        assert spec["no_honorifics"] is True

    def test_enforce_substitutions_excludes_flag_tier(self):
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {}, rules)
        subs = result.data["enforce_substitutions"]
        assert {s.get("tier") for s in subs} == {"enforce"}
        ids = {s.get("id") for s in subs if s.get("id")}
        assert "oxford_comma" not in ids
        assert "capitol_capital" not in ids
        assert "de_italicize_program_names" in ids


class TestPreStageFormatterPromptSection:
    def test_section_header_present(self):
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {}, rules)
        assert "## Style Rules (authoritative)" in result.prompt_section

    def test_proper_nouns_authoritative_line_present(self):
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {"analyst_output": ANALYST_TABLE}, rules)
        assert "Nick Hoffman" in result.prompt_section
        assert "authoritative spellings" in result.prompt_section.lower()

    def test_speaker_label_spec_rendered_with_odd_values_not_hardcoded(self):
        # Odd values (not the real config's 2/1) must show up verbatim,
        # proving the numbers are read from data, never hardcoded prose.
        rules = _formatter_rules(
            speaker_label={
                "pattern": _FORMATTER_SPEAKER_LABEL_SPEC["pattern"],
                "trailing_spaces": 5,
                "blank_lines_between_turns": 3,
                "no_honorifics": True,
            }
        )
        result = run_pre_stage("formatter", {}, rules)
        assert "5 trailing space" in result.prompt_section
        assert "3 blank line" in result.prompt_section

    def test_no_honorifics_false_omits_honorific_instruction(self):
        rules = _formatter_rules(
            speaker_label={
                "pattern": _FORMATTER_SPEAKER_LABEL_SPEC["pattern"],
                "trailing_spaces": 2,
                "blank_lines_between_turns": 1,
                "no_honorifics": False,
            }
        )
        result = run_pre_stage("formatter", {}, rules)
        assert "honorific" not in result.prompt_section.lower()

    def test_substitution_pairs_rendered_from_yaml_not_hardcoded(self):
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {}, rules)
        assert "OK (never okay)" in result.prompt_section
        assert "Sen. (never Senator)" in result.prompt_section

    def test_regexy_find_uses_note_when_present(self):
        # de_italicize's find is alternation-shaped -- best-effort cleanup
        # can't produce a clean phrase, so the note supplies it instead.
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {}, rules)
        assert "strips markdown italics around known program names" in result.prompt_section

    def test_backreference_replace_never_prints_raw_backreference_token(self):
        # Regression: de_italicize's replace is the literal string "\1" (a
        # regex backreference, not a literal replacement outside an actual
        # match) -- rendering it via the normal "X (never Y)" template would
        # literally print "\1" into the prompt, which is meaningless to a
        # human/model reader.
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {}, rules)
        assert r"\1" not in result.prompt_section

    def test_simple_find_with_note_still_uses_cleanup_not_note(self):
        # A note is present on the "Liberals" entry too, but its find
        # cleans up to a plain word ("Liberals") -- the note must NOT
        # override a clean best-effort result.
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {}, rules)
        assert "liberals (never Liberals)" in result.prompt_section
        assert "sentence-initial guard applies" not in result.prompt_section

    def test_flag_tier_entries_never_appear_in_pairs_line(self):
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {}, rules)
        assert "oxford" not in result.prompt_section.lower()
        assert "capitol_capital" not in result.prompt_section.lower()

    def test_review_notes_placement_line_data_driven(self):
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {}, rules)
        assert "top" in result.prompt_section.lower()
        assert "html comment" in result.prompt_section.lower()

    def test_review_notes_line_reflects_odd_placement_value(self):
        rules = _formatter_rules(review_notes={"placement": "bottom", "format": "plain_text"})
        result = run_pre_stage("formatter", {}, rules)
        assert "bottom" in result.prompt_section.lower()
        assert "plain text" in result.prompt_section.lower()


class TestPreStageFormatterGraceful:
    def test_no_analyst_output_omits_names_block(self):
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {}, rules)
        assert result.data["proper_nouns"] == []
        assert "authoritative spellings" not in result.prompt_section.lower()

    def test_none_analyst_output_does_not_raise(self):
        rules = _formatter_rules()
        result = run_pre_stage("formatter", {"analyst_output": None}, rules)
        assert result.data["proper_nouns"] == []

    def test_unknown_keys_in_speaker_label_spec_tolerated(self):
        rules = _formatter_rules(
            speaker_label={
                "pattern": _FORMATTER_SPEAKER_LABEL_SPEC["pattern"],
                "trailing_spaces": 2,
                "blank_lines_between_turns": 1,
                "no_honorifics": True,
                "some_future_field": {"nested": "value"},
            }
        )
        result = run_pre_stage("formatter", {}, rules)
        assert result.prompt_section  # still renders without raising

    def test_missing_speaker_label_omits_line(self):
        rules = _formatter_rules(speaker_label={})
        result = run_pre_stage("formatter", {}, rules)
        assert "Speaker labels" not in result.prompt_section

    def test_missing_review_notes_omits_line(self):
        rules = _formatter_rules(review_notes={})
        result = run_pre_stage("formatter", {}, rules)
        assert "Review notes" not in result.prompt_section

    def test_empty_substitutions_omits_pairs_line(self):
        rules = _formatter_rules(substitutions=[])
        result = run_pre_stage("formatter", {}, rules)
        assert "write it right" not in result.prompt_section.lower()


# ---------------------------------------------------------------------------
# run_post_stage -- formatter phase (task 3a)
# ---------------------------------------------------------------------------

_FORMATTER_DOC_HEADER = (
    "# Formatted Transcript\n"
    "**Project:** 2WLI1234HD\n"
    "**Program:** Here & Now\n"
    "**Duration:** 10:00\n"
    "**Date Processed:** 2026-07-10\n"
)


def _formatter_doc(
    body: str,
    review_notes: str | None = None,
    review_notes_before_header: bool = False,
    status: str = "ready_for_editing",
) -> str:
    notes_block = f"{review_notes}\n\n" if review_notes else ""
    if review_notes_before_header:
        return f"{notes_block}{_FORMATTER_DOC_HEADER}\n---\n\n{body}\n\n---\n\n**Status:** {status}\n"
    return f"{_FORMATTER_DOC_HEADER}\n---\n\n{notes_block}{body}\n\n---\n\n**Status:** {status}\n"


class TestPostStageFormatterEndToEndNormalize:
    def test_full_normalize_byte_exact(self):
        rules = _formatter_rules()
        raw_body = (
            "**Nick Hoffman:**\n"
            "Senator Smith says that's okay with the budget, and mentioned *Here & Now* coverage.\n"
            "\n\n\n"
            "**Angela Fitzgerald:**     \n"
            "That's right, we'll see."
        )
        raw_output = _formatter_doc(raw_body)

        result = run_post_stage("formatter", raw_output, {}, rules)

        assert result.changed is True
        expected_body = (
            "**Nick Hoffman:**  \n"
            "Sen. Smith says that's OK with the budget, and mentioned Here & Now coverage.\n"
            "\n"
            "**Angela Fitzgerald:**  \n"
            "That's right, we'll see."
        )
        expected_output = _formatter_doc(expected_body)
        assert result.normalized_output == expected_output

    def test_fix_entries_report_before_after_and_counts(self):
        rules = _formatter_rules()
        raw_body = "**Nick Hoffman:**\nSenator Smith says that's okay.\n\n**Angela Fitzgerald:**\nOkay, agreed."
        raw_output = _formatter_doc(raw_body)

        result = run_post_stage("formatter", raw_output, {}, rules)

        rule_ids = {f.rule_id for f in result.check.fixes}
        # rule_ids are slugged from each pair's `replace` value when the
        # yaml entry has no explicit `id` -- "Sen." -> "sen", "OK" -> "ok".
        assert rule_ids == {"formatter.substitution.sen", "formatter.substitution.ok"}
        okay_fix = next(f for f in result.check.fixes if f.rule_id == "formatter.substitution.ok")
        assert okay_fix.count == 2  # "okay" + "Okay"

    def test_header_and_footer_metadata_never_touched(self):
        rules = _formatter_rules()
        raw_body = "**Nick Hoffman:**\nSenator Smith says okay.\n\n**Angela Fitzgerald:**\nAgreed."
        raw_output = _formatter_doc(raw_body)

        result = run_post_stage("formatter", raw_output, {}, rules)

        assert "**Date Processed:** 2026-07-10\n" in result.normalized_output
        assert "**Status:** ready_for_editing\n" in result.normalized_output
        assert "**Date Processed:**  \n" not in result.normalized_output


class TestPostStageFormatterGuards:
    def test_fenced_code_block_and_url_untouched(self):
        rules = _formatter_rules()
        raw_body = "**Nick Hoffman:**\n" "Visit https://example.com/okay-page and see this:\n\n" "```\nokay = True\n```"
        raw_output = _formatter_doc(raw_body)

        result = run_post_stage("formatter", raw_output, {}, rules)

        assert "https://example.com/okay-page" in result.normalized_output
        assert "okay = True" in result.normalized_output

    def test_sentence_initial_liberals_untouched(self):
        rules = _formatter_rules()
        raw_body = "**Nick Hoffman:**\nLiberals gathered downtown to discuss the plan."
        raw_output = _formatter_doc(raw_body)

        result = run_post_stage("formatter", raw_output, {}, rules)

        assert "Liberals gathered downtown" in result.normalized_output
        assert "liberals gathered downtown" not in result.normalized_output


class TestPostStageFormatterConvergence:
    def test_okay_variants_converge_to_identical_output(self):
        rules = _formatter_rules()
        body_lower = "**Nick Hoffman:**\nThat's okay with me."
        body_title = "**Nick Hoffman:**\nThat's Okay with me."

        result_lower = run_post_stage("formatter", _formatter_doc(body_lower), {}, rules)
        result_title = run_post_stage("formatter", _formatter_doc(body_title), {}, rules)

        assert result_lower.normalized_output == result_title.normalized_output


class TestPostStageFormatterFlagTier:
    def test_oxford_comma_detected_text_unchanged(self):
        rules = _formatter_rules()
        # Label line already carries correct trailing-space/spec whitespace
        # so the only thing under test is the flag-tier "never rewrites"
        # guarantee, not incidental enforce-tier whitespace normalization.
        raw_body = "**Nick Hoffman:**  \nWe discussed red, white, and blue today."
        raw_output = _formatter_doc(raw_body)

        result = run_post_stage("formatter", raw_output, {}, rules)

        assert result.normalized_output == raw_output
        oxford_violations = [v for v in result.check.violations if v.rule_id == "formatter.oxford_comma"]
        assert len(oxford_violations) == 1
        assert oxford_violations[0].severity == "warning"
        assert oxford_violations[0].model_fixable is True

    def test_capitol_capital_detected(self):
        rules = _formatter_rules()
        raw_body = "**Nick Hoffman:**\nThe capital was raised for the new building fund."
        raw_output = _formatter_doc(raw_body)

        result = run_post_stage("formatter", raw_output, {}, rules)

        capitol_violations = [v for v in result.check.violations if v.rule_id == "formatter.capitol_capital"]
        assert len(capitol_violations) == 1
        assert "capital" in result.normalized_output  # detection only, never rewritten

    def test_no_flag_violations_when_absent(self):
        rules = _formatter_rules()
        raw_body = "**Nick Hoffman:**\nWe discussed the budget plan today."
        raw_output = _formatter_doc(raw_body)

        result = run_post_stage("formatter", raw_output, {}, rules)

        flag_rule_ids = {v.rule_id for v in result.check.violations}
        assert "formatter.oxford_comma" not in flag_rule_ids
        assert "formatter.capitol_capital" not in flag_rule_ids

    def test_review_notes_in_body_flagged(self):
        rules = _formatter_rules()
        raw_body = (
            "**Nick Hoffman:**\nStatement.\n\n<!-- REVIEW NOTES: speaker unclear -->\n\n**Angela Fitzgerald:**\nMore."
        )
        raw_output = _formatter_doc(raw_body)

        result = run_post_stage("formatter", raw_output, {}, rules)

        review_violations = [v for v in result.check.violations if v.rule_id == "lint.formatter.review_notes_in_body"]
        assert len(review_violations) == 1
        assert review_violations[0].model_fixable is False

    def test_review_notes_at_top_not_flagged(self):
        rules = _formatter_rules()
        raw_body = "**Nick Hoffman:**\nStatement.\n\n**Angela Fitzgerald:**\nMore."
        raw_output = _formatter_doc(
            raw_body,
            review_notes="<!-- REVIEW NOTES: speaker unclear -->",
            review_notes_before_header=True,
        )

        result = run_post_stage("formatter", raw_output, {}, rules)

        review_violations = [v for v in result.check.violations if v.rule_id == "lint.formatter.review_notes_in_body"]
        assert review_violations == []


class TestPostStageFormatterNoVoiceScanning:
    def test_amazing_and_we_never_flagged(self):
        # Voice/forbidden scanning is a seo-phase concept only -- dialogue
        # is not metadata copy, people may say "amazing" or "we" on camera.
        rules = _formatter_rules()
        raw_body = "**Nick Hoffman:**\nWe think this is an amazing budget deal for Wisconsin."
        raw_output = _formatter_doc(raw_body)

        result = run_post_stage("formatter", raw_output, {}, rules)

        voice_violations = [v for v in result.check.violations if v.rule_id.startswith("voice.")]
        assert voice_violations == []
        assert "amazing" in result.normalized_output
        assert "We think" in result.normalized_output


class TestPostStageFormatterWordCountGuard:
    def test_pathological_substitution_reverts_to_raw(self):
        # A synthetic "the" -> "" substitution deletes real content words --
        # the guard must catch this and return raw output unchanged.
        pathological_subs = [{"find": r"\bthe\b", "replace": "", "tier": "enforce"}]
        rules = _formatter_rules(substitutions=pathological_subs)
        raw_body = (
            "**Nick Hoffman:**\n"
            "The budget deal includes the new funding for the schools in the state "
            "and the roads across the region for the coming year."
        )
        raw_output = _formatter_doc(raw_body)

        result = run_post_stage("formatter", raw_output, {}, rules)

        assert result.normalized_output == raw_output
        assert result.changed is False
        guard_violations = [v for v in result.check.violations if v.rule_id == "formatter.normalization_guard"]
        assert len(guard_violations) == 1
        assert guard_violations[0].severity == "error"
        assert guard_violations[0].model_fixable is False
        assert result.check.fixes == []

    def test_normal_substitutions_never_trigger_guard(self):
        rules = _formatter_rules()
        raw_body = (
            "**Nick Hoffman:**\n"
            "Senator Smith and Attorney General Jones said the vote was okay, and "
            "mentioned *Here & Now* coverage of the Liberals rally."
        )
        raw_output = _formatter_doc(raw_body)

        result = run_post_stage("formatter", raw_output, {}, rules)

        guard_violations = [v for v in result.check.violations if v.rule_id == "formatter.normalization_guard"]
        assert guard_violations == []
        assert result.normalized_output != raw_output


class TestPostStageFormatterIdempotence:
    def test_double_post_stage_is_a_no_op(self):
        rules = _formatter_rules()
        raw_body = (
            "**Nick Hoffman:**\n"
            "Senator Smith said that's okay, and mentioned *Here & Now* coverage of "
            "the Liberals rally.\n\n\n"
            "**Angela Fitzgerald:**     \n"
            "Agreed, we'll follow up."
        )
        raw_output = _formatter_doc(raw_body)

        once = run_post_stage("formatter", raw_output, {}, rules)
        twice = run_post_stage("formatter", once.normalized_output, {}, rules)

        assert once.normalized_output == twice.normalized_output
        assert twice.changed is False


# ---------------------------------------------------------------------------
# run_pre_stage / run_post_stage -- timestamp phase (task 4a)
# ---------------------------------------------------------------------------

_TIMESTAMP_CHAPTER_MAX = [
    {"lt": 5, "max": 3},
    {"lt": 15, "max": 5},
    {"lt": 30, "max": 7},
    {"lt": 60, "max": 8},
    {"lt": None, "max": 10},
]


def _timestamp_rules(
    first_chapter_title: str = "Episode intro",
    chapter_name: dict | None = None,
    chapter_max_by_duration: list | None = None,
    constraints: dict | None = None,
    forbidden_phrases: list | None = None,
) -> StyleRules:
    raw = {
        "meta": {"version": 1},
        "voice": {
            "forbidden_phrases": (
                [{"match": "discover", "category": "viewer_directive", "severity": "error"}]
                if forbidden_phrases is None
                else forbidden_phrases
            ),
            "first_person_markers": [r"\bwe\b"],
            "second_person_markers": [r"\byou\b"],
        },
        "casing": {
            "style": "down",
            "proper_nouns": ["Wisconsin", "Nick Hoffman", "Angela Fitzgerald"],
            "acronyms": [],
            "casing_variants": {},
            "surname_stoplist": [],
        },
        "phases": {
            "timestamp": {
                "chapter_max_by_duration": (
                    _TIMESTAMP_CHAPTER_MAX if chapter_max_by_duration is None else chapter_max_by_duration
                ),
                "first_chapter": {"time": "0:00", "title": first_chapter_title, "tier": "enforce"},
                "chapter_name": (
                    {"case": "sentence", "words": {"min": 2, "max": 6}, "tier": "flag"}
                    if chapter_name is None
                    else chapter_name
                ),
                "formats": {
                    "media_manager": {"start": "H:MM:SS.000", "end": "H:MM:SS.999", "tier": "enforce"},
                    "youtube": {"style": "M:SS", "tier": "enforce"},
                },
                "constraints": (
                    {"no_gaps": True, "chronological": True, "final_end_equals_srt_end": True}
                    if constraints is None
                    else constraints
                ),
            }
        },
    }
    return StyleRules(raw=raw)


def _srt_timecode(ms: int) -> str:
    hours, remainder = divmod(ms, 3600000)
    minutes, remainder = divmod(remainder, 60000)
    seconds, millis = divmod(remainder, 1000)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{millis:03d}"


def _build_srt(captions: list[tuple[int, int, str]]) -> str:
    """``captions``: list of ``(start_ms, end_ms, text)`` tuples."""
    blocks = [
        f"{index}\n{_srt_timecode(start_ms)} --> {_srt_timecode(end_ms)}\n{text}\n"
        for index, (start_ms, end_ms, text) in enumerate(captions, start=1)
    ]
    return "\n".join(blocks)


# A 10-minute synthetic SRT with two speaker transitions (">>") and two
# music cues ("[bright music]" / "♪...♪") among plain dialogue captions that
# must NOT become candidates. srt_end_ms == 600000 (last caption's end).
TIMESTAMP_SRT = _build_srt(
    [
        (0, 3000, "Welcome to the show today."),
        (3000, 6000, "[bright music]"),
        (6000, 30000, ">> Nick Hoffman: Let's talk about the state budget."),
        (30000, 60000, "The budget includes new funding for schools across Wisconsin."),
        (150000, 155000, ">> Angela Fitzgerald: Now let's shift over to the weather."),
        (155000, 495000, "It's going to be sunny for most of the week."),
        (495000, 498000, "♪ closing theme ♪"),
        (498000, 600000, "Thanks for watching, we'll see you next time."),
    ]
)

# The four candidate boundary times TIMESTAMP_SRT should yield, in order.
TIMESTAMP_CANDIDATE_TIMES = [3000, 6000, 150000, 495000]


def _timestamp_context(srt: str = TIMESTAMP_SRT, **overrides) -> dict:
    context = {"transcript_file": "episode.srt", "transcript": srt}
    context.update(overrides)
    return context


class TestPreStageTimestampGraceful:
    def test_non_srt_transcript_file_returns_empty(self):
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", {"transcript_file": "episode.txt", "transcript": "plain text"}, rules)
        assert result.phase == "timestamp"
        assert result.prompt_section == ""
        assert result.data == {}

    def test_missing_transcript_file_returns_empty(self):
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", {}, rules)
        assert result.prompt_section == ""
        assert result.data == {}

    def test_srt_extension_but_unparseable_content_returns_empty(self):
        rules = _timestamp_rules()
        result = run_pre_stage(
            "timestamp", {"transcript_file": "episode.srt", "transcript": "not real srt content"}, rules
        )
        assert result.prompt_section == ""
        assert result.data == {}


class TestPreStageTimestampData:
    def test_srt_end_ms_and_duration_ms_from_last_caption(self):
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        assert result.data["srt_end_ms"] == 600000
        assert result.data["duration_ms"] == 600000

    def test_max_chapters_from_rules_duration_table(self):
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        # 10 minutes falls in the "lt: 15" bucket -> max 5.
        assert result.data["max_chapters"] == 5

    def test_max_chapters_reflects_odd_duration_table(self):
        # Proves max_chapters is read from rules, not hardcoded: an
        # off-spec table collapses everything to 2.
        rules = _timestamp_rules(chapter_max_by_duration=[{"lt": None, "max": 2}])
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        assert result.data["max_chapters"] == 2

    def test_boundary_candidates_kinds_and_order(self):
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        candidates = result.data["boundary_candidates"]
        assert [c["time_ms"] for c in candidates] == TIMESTAMP_CANDIDATE_TIMES
        assert [c["kind"] for c in candidates] == [
            "music_cue",
            "speaker_transition",
            "speaker_transition",
            "music_cue",
        ]

    def test_speaker_transition_label_contains_speaker_text(self):
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        candidate = next(c for c in result.data["boundary_candidates"] if c["time_ms"] == 6000)
        assert "Nick Hoffman" in candidate["label"]
        assert candidate["formatted"] == format_youtube(6000)

    def test_final_end_both_formats(self):
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        assert result.data["final_end"]["youtube"] == format_youtube(600000)
        assert result.data["final_end"]["media_manager"] == format_media_manager(600000, end=True)


class TestPreStageTimestampSubsampling:
    def test_small_candidate_list_not_subsampled(self):
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        assert result.data["boundary_candidates_subsampled"] is False
        assert result.data["boundary_candidates_total"] == len(TIMESTAMP_CANDIDATE_TIMES)

    def test_over_sixty_candidates_capped_and_flagged(self):
        captions = [(i * 1000, i * 1000 + 500, f">> Speaker {i}: line") for i in range(100)]
        srt = _build_srt(captions)
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(srt=srt), rules)
        assert len(result.data["boundary_candidates"]) == 60
        assert result.data["boundary_candidates_subsampled"] is True
        assert result.data["boundary_candidates_total"] == 100

    def test_subsampled_candidates_span_full_range(self):
        captions = [(i * 1000, i * 1000 + 500, f">> Speaker {i}: line") for i in range(100)]
        srt = _build_srt(captions)
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(srt=srt), rules)
        times = [c["time_ms"] for c in result.data["boundary_candidates"]]
        assert times[0] == 0
        assert times == sorted(times)
        assert times[-1] > 90000  # spread across the whole 100s range, not just the head


class TestPreStageTimestampPromptSection:
    def test_chapter_limit_line(self):
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        assert "produce at most 5 chapters" in result.prompt_section

    def test_candidate_list_header(self):
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        assert "choose boundaries ONLY from this candidate list:" in result.prompt_section

    def test_candidates_rendered_with_formatted_timecode_and_kind(self):
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        assert format_youtube(6000) in result.prompt_section
        assert "speaker_transition" in result.prompt_section
        assert "music_cue" in result.prompt_section

    def test_first_chapter_line_data_driven(self):
        rules = _timestamp_rules(first_chapter_title="Cold open")
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        assert "first chapter is always 0:00 Cold open (added automatically)" in result.prompt_section

    def test_final_chapter_line_present(self):
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        assert "final chapter ends at exactly 10:00 (handled automatically)" in result.prompt_section

    def test_chapter_naming_line_data_driven_odd_values(self):
        rules = _timestamp_rules(chapter_name={"case": "title", "words": {"min": 3, "max": 5}})
        result = run_pre_stage("timestamp", _timestamp_context(), rules)
        assert "title case" in result.prompt_section
        assert "3-5 words" in result.prompt_section

    def test_label_excerpt_capped_at_forty_chars(self):
        long_text = ">> Nick Hoffman: " + ("a very long line of dialogue " * 5)
        srt = _build_srt([(0, 1000, long_text)])
        rules = _timestamp_rules()
        result = run_pre_stage("timestamp", _timestamp_context(srt=srt), rules)
        candidate = result.data["boundary_candidates"][0]
        assert len(candidate["label"]) <= 40


# ---------------------------------------------------------------------------
# run_post_stage -- timestamp phase (task 4a)
# ---------------------------------------------------------------------------


def _chapters_raw_output(lines: list[str], prose_before: str = "", prose_after: str = "") -> str:
    fence = "```chapters\n" + "\n".join(lines) + "\n```"
    parts = [part for part in (prose_before, fence, prose_after) if part]
    return "\n\n".join(parts)


def _timestamp_style_pre(rules: StyleRules, srt: str = TIMESTAMP_SRT) -> dict:
    """Build a context["style_pre"] dict the way worker.py would after a
    real run_pre_stage("timestamp", ...) call, so post_stage tests can
    exercise the "boundary not in candidate list" check realistically."""
    pre = run_pre_stage("timestamp", _timestamp_context(srt=srt), rules)
    return {"prompt_section": pre.prompt_section, **pre.data}


HAPPY_TIMESTAMP_LINES = [
    "0:00 Episode intro",
    "0:06 Budget debate begins",
    "2:30 Weather turns sunny",
    "8:15 Closing credits roll",
]


class TestPostStageTimestampUnparseable:
    def test_no_fence_passthrough(self):
        rules = _timestamp_rules()
        raw_output = "I looked at the transcript but didn't find clear chapter breaks."

        result = run_post_stage("timestamp", raw_output, _timestamp_context(), rules)

        assert result.check.parse_ok is False
        assert result.normalized_output == raw_output
        assert result.changed is False
        assert len(result.check.violations) == 1
        violation = result.check.violations[0]
        assert violation.rule_id == "phase_io.timestamp.unparseable"
        assert violation.severity == "warning"
        assert violation.model_fixable is True

    def test_empty_output_does_not_raise(self):
        rules = _timestamp_rules()
        result = run_post_stage("timestamp", "", _timestamp_context(), rules)
        assert result.check.parse_ok is False
        assert result.normalized_output == ""


class TestPostStageTimestampEndToEnd:
    def test_happy_path_matches_emit_timestamp_report(self):
        rules = _timestamp_rules()
        context = _timestamp_context()
        context["style_pre"] = _timestamp_style_pre(rules)
        raw_output = _chapters_raw_output(HAPPY_TIMESTAMP_LINES)

        result = run_post_stage("timestamp", raw_output, context, rules)

        assert result.check.parse_ok is True
        assert result.changed is True
        assert result.normalized_output.startswith("# Timestamp Report")
        assert "| Episode intro | 0:00:00.000 | 0:00:05.999 |" in result.normalized_output
        assert "0:00 Episode intro" in result.normalized_output
        assert "8:15 Closing credits roll" in result.normalized_output
        # Final row's end is exactly the SRT end (600000ms == 10:00:00.000
        # via honest ms math -- see timecodes.format_media_manager).
        assert "0:10:00.000" in result.normalized_output

        chapter_count_violations = [v for v in result.check.violations if v.rule_id == "timestamp.chapter_count"]
        assert chapter_count_violations == []
        boundary_violations = [v for v in result.check.violations if v.rule_id == "timestamp.boundary_unlisted"]
        assert boundary_violations == []

        emit_fixes = [f for f in result.check.fixes if f.rule_id == "timestamp.emit"]
        assert len(emit_fixes) == 1

    def test_slim_contract_synthetic_output_byte_exact_with_project_line(self):
        """A slim-profile-shaped model response -- nothing but the ```chapters
        fence (exactly what timestamp.output_contract's slim profile
        instructs the model to produce; no manually-typed tables, no prose)
        -- round-trips through run_post_stage into a byte-exact final
        report, including the **Project:** line sourced from
        context["project_name"] (task 4b's two engine fixes combined)."""
        rules = _timestamp_rules()
        context = _timestamp_context()
        context["project_name"] = "Budget Debate 2026"
        context["style_pre"] = _timestamp_style_pre(rules)
        # Bare slim-contract output: only the fenced chapters block.
        raw_output = "```chapters\n" + "\n".join(HAPPY_TIMESTAMP_LINES) + "\n```"

        result = run_post_stage("timestamp", raw_output, context, rules)

        expected = (
            "# Timestamp Report\n\n"
            "**Project:** Budget Debate 2026\n"
            "**Duration:** 10:00\n\n"
            "---\n\n"
            "## Media Manager Format\n\n"
            "Copy-paste this table into PBS Media Manager chapter fields:\n\n"
            "| Title | Start Time | End Time |\n"
            "|-------|------------|----------|\n"
            "| Episode intro | 0:00:00.000 | 0:00:05.999 |\n"
            "| Budget debate begins | 0:00:06.000 | 0:02:29.999 |\n"
            "| Weather turns sunny | 0:02:30.000 | 0:08:14.999 |\n"
            "| Closing credits roll | 0:08:15.000 | 0:10:00.000 |\n\n"
            "---\n\n"
            "## YouTube Format\n\n"
            "Copy-paste these timestamps directly into your YouTube description:\n\n"
            "0:00 Episode intro\n"
            "0:06 Budget debate begins\n"
            "2:30 Weather turns sunny\n"
            "8:15 Closing credits roll\n\n"
            "---\n\n"
            "## Notes\n\n"
            "- No gaps between chapters -- each ends exactly where the next begins.\n"
            "- Chapters are listed in chronological order.\n"
            "- Final chapter end time matches the last SRT timestamp.\n"
        )
        assert result.check.parse_ok is True
        assert result.normalized_output == expected

    def test_no_project_line_when_project_name_absent_from_context(self):
        rules = _timestamp_rules()
        context = _timestamp_context()  # no "project_name" key at all
        context["style_pre"] = _timestamp_style_pre(rules)
        raw_output = _chapters_raw_output(HAPPY_TIMESTAMP_LINES)

        result = run_post_stage("timestamp", raw_output, context, rules)

        assert "**Project:**" not in result.normalized_output
        assert result.normalized_output.startswith("# Timestamp Report\n\n**Duration:**")

    def test_srt_end_ms_reparsed_when_style_pre_absent(self):
        rules = _timestamp_rules()
        context = _timestamp_context()  # no "style_pre" key at all
        raw_output = _chapters_raw_output(HAPPY_TIMESTAMP_LINES)

        result = run_post_stage("timestamp", raw_output, context, rules)

        assert result.check.parse_ok is True
        assert "0:10:00.000" in result.normalized_output

    def test_convergence_different_formats_and_casing_produce_byte_identical_output(self):
        rules = _timestamp_rules()
        context = _timestamp_context()
        context["style_pre"] = _timestamp_style_pre(rules)

        raw_a = _chapters_raw_output(
            [
                "0:00 episode intro",
                "0:06 Budget Debate Begins",
                "2:30 weather turns sunny",
                "8:15 CLOSING CREDITS ROLL",
            ]
        )
        raw_b = _chapters_raw_output(
            [
                "0:00:00 Episode Intro",
                "0:00:06 budget debate begins",
                "0:02:30 Weather Turns Sunny",
                "0:08:15 closing credits roll",
            ]
        )

        result_a = run_post_stage("timestamp", raw_a, context, rules)
        result_b = run_post_stage("timestamp", raw_b, context, rules)

        assert result_a.normalized_output == result_b.normalized_output

    def test_forbidden_word_in_title_flagged_but_kept(self):
        rules = _timestamp_rules()
        context = _timestamp_context()
        context["style_pre"] = _timestamp_style_pre(rules)
        raw_output = _chapters_raw_output(
            [
                "0:00 Episode intro",
                "0:06 Discover the budget debate",
            ]
        )

        result = run_post_stage("timestamp", raw_output, context, rules)

        forbidden_violations = [v for v in result.check.violations if v.rule_id == "voice.forbidden.viewer_directive"]
        assert len(forbidden_violations) == 1
        assert forbidden_violations[0].field == "chapter_title"
        # Casing-normalized only -- the forbidden word itself is never stripped.
        assert "discover" in result.normalized_output.lower()

    def test_chapter_count_violation_when_model_exceeds_max(self):
        rules = _timestamp_rules()  # 10-minute duration -> max 5
        context = _timestamp_context()
        context["style_pre"] = _timestamp_style_pre(rules)
        lines = ["0:00 Episode intro"] + [f"{i}:00 Extra segment {i}" for i in range(1, 8)]
        raw_output = _chapters_raw_output(lines)

        result = run_post_stage("timestamp", raw_output, context, rules)

        count_violations = [v for v in result.check.violations if v.rule_id == "timestamp.chapter_count"]
        assert len(count_violations) == 1
        assert count_violations[0].severity == "warning"
        # The emitter already truncated to max_chapters=5: intro + the
        # first 4 extras survive, the last 3 are dropped from the output.
        assert "Extra segment 4" in result.normalized_output
        assert "Extra segment 5" not in result.normalized_output
        assert "Extra segment 6" not in result.normalized_output
        assert "Extra segment 7" not in result.normalized_output

    def test_chapter_count_violation_from_forced_first_chapter_truncation(self):
        """The exact under-reporting scenario task 4b's fix closes: the
        model returns exactly max_chapters chapters (5, for this 10-minute
        fixture), and NONE of them starts at 0:00. The raw model count
        (5) does NOT exceed max_chapters (5) -- the old `pre_snap_count >
        max_chapters` check alone would miss this entirely. But
        snap_chapters' forced-first-chapter prepend adds a 6th chapter
        (0:00 Episode intro), pushing the snapped list to 6, which then gets
        truncated back down to 5 -- silently dropping one of the model's
        real proposed chapters. The fix must catch this via the truncation
        note and name the dropped chapter in the violation message.
        """
        rules = _timestamp_rules()  # 10-minute duration -> max 5
        context = _timestamp_context()  # no style_pre -- keeps this focused on chapter_count
        lines = [f"{i}:00 Segment {i}" for i in range(1, 6)]  # exactly 5, none at 0:00
        raw_output = _chapters_raw_output(lines)

        result = run_post_stage("timestamp", raw_output, context, rules)

        count_violations = [v for v in result.check.violations if v.rule_id == "timestamp.chapter_count"]
        assert len(count_violations) == 1
        assert count_violations[0].severity == "warning"
        assert count_violations[0].model_fixable is True
        # Names the specific chapter the forced-prepend-triggered truncation dropped.
        assert "Segment 5" in count_violations[0].message
        assert "Segment 5" not in result.normalized_output
        # The other 4 model-proposed chapters plus the forced "Episode intro"
        # survive (5 total, at the cap).
        for kept in ("Segment 1", "Segment 2", "Segment 3", "Segment 4"):
            assert kept in result.normalized_output
        assert "Episode intro" in result.normalized_output

    def test_boundary_unlisted_violation_for_off_candidate_chapter(self):
        rules = _timestamp_rules()
        context = _timestamp_context()
        context["style_pre"] = _timestamp_style_pre(rules)
        # 3:20 (200000ms) is nowhere near any of TIMESTAMP_CANDIDATE_TIMES.
        raw_output = _chapters_raw_output(["0:00 Episode intro", "3:20 An unlisted boundary"])

        result = run_post_stage("timestamp", raw_output, context, rules)

        unlisted = [v for v in result.check.violations if v.rule_id == "timestamp.boundary_unlisted"]
        assert len(unlisted) == 1
        assert unlisted[0].model_fixable is True

    def test_first_chapter_exempt_from_boundary_unlisted_check(self):
        rules = _timestamp_rules()
        context = _timestamp_context()
        context["style_pre"] = _timestamp_style_pre(rules)
        # First chapter is forced to 0:00 regardless of the model's choice
        # and is never itself flagged as an unlisted boundary.
        raw_output = _chapters_raw_output(["0:00 Episode intro", "0:06 Budget debate begins"])

        result = run_post_stage("timestamp", raw_output, context, rules)

        unlisted = [v for v in result.check.violations if v.rule_id == "timestamp.boundary_unlisted"]
        assert unlisted == []

    def test_no_boundary_check_when_no_style_pre_candidates(self):
        rules = _timestamp_rules()
        context = _timestamp_context()  # no style_pre at all
        raw_output = _chapters_raw_output(["0:00 Episode intro", "3:20 Anything goes"])

        result = run_post_stage("timestamp", raw_output, context, rules)

        unlisted = [v for v in result.check.violations if v.rule_id == "timestamp.boundary_unlisted"]
        assert unlisted == []

    def test_chapter_name_length_violation_for_odd_config(self):
        rules = _timestamp_rules(chapter_name={"case": "sentence", "words": {"min": 4, "max": 6}})
        context = _timestamp_context()
        context["style_pre"] = _timestamp_style_pre(rules)
        # "Budget debate" is 2 words -- under the odd 4-6 word minimum. Note
        # the auto-generated "Episode intro" first chapter is 2 words too,
        # so it also trips this deliberately-odd 4-6 minimum -- the check
        # applies uniformly to every chapter title, not just model choices.
        raw_output = _chapters_raw_output(["0:00 Episode intro", "0:06 Budget debate"])

        result = run_post_stage("timestamp", raw_output, context, rules)

        length_violations = [v for v in result.check.violations if v.rule_id == "timestamp.chapter_name_length"]
        assert len(length_violations) == 2
        assert all("4-6" in v.message for v in length_violations)
        assert any("Budget debate" in v.message for v in length_violations)

    def test_snap_notes_surface_as_timestamp_snapped_violations(self):
        rules = _timestamp_rules(first_chapter_title="Cold open")
        context = _timestamp_context()
        context["style_pre"] = _timestamp_style_pre(rules)
        # Model's first chapter isn't "Cold open" -> snap_chapters produces
        # exactly one note (a forced-title override).
        raw_output = _chapters_raw_output(["0:00 Episode intro", "0:06 Budget debate begins"])

        result = run_post_stage("timestamp", raw_output, context, rules)

        snapped_violations = [v for v in result.check.violations if v.rule_id == "timestamp.snapped"]
        assert len(snapped_violations) == 1
        assert "Cold open" in snapped_violations[0].message
        assert snapped_violations[0].model_fixable is False

    def test_duplicate_start_snap_note_surfaces_as_violation(self):
        rules = _timestamp_rules()
        context = _timestamp_context()
        context["style_pre"] = _timestamp_style_pre(rules)
        raw_output = _chapters_raw_output(
            ["0:00 Episode intro", "0:06 Budget debate begins", "0:06 Duplicate boundary"]
        )

        result = run_post_stage("timestamp", raw_output, context, rules)

        snapped_violations = [v for v in result.check.violations if v.rule_id == "timestamp.snapped"]
        assert any("duplicate" in v.message for v in snapped_violations)

    def test_title_casing_normalized_via_fixes(self):
        rules = _timestamp_rules()
        context = _timestamp_context()
        context["style_pre"] = _timestamp_style_pre(rules)
        raw_output = _chapters_raw_output(["0:00 Episode intro", "0:06 THE BUDGET DEBATE BEGINS NOW TODAY"])

        result = run_post_stage("timestamp", raw_output, context, rules)

        title_fixes = [f for f in result.check.fixes if f.rule_id == "casing.down_style.chapter_title"]
        assert len(title_fixes) == 1
        assert title_fixes[0].before == "THE BUDGET DEBATE BEGINS NOW TODAY"
        assert title_fixes[0].after != title_fixes[0].before
        assert "the budget debate" in title_fixes[0].after.lower()


# ---------------------------------------------------------------------------
# run_pre_stage / run_post_stage -- analyst phase (task 5, the last per-phase
# stage). Pre-stage computes verified source facts (never estimated) + a
# data-driven draft-metadata-guidance line + the shared voice do-not list.
# Post-stage is flag-only -- no enforce tier at all, normalized_output is
# always byte-identical to raw_output and changed is always False.
# ---------------------------------------------------------------------------

_DEFAULT_ANALYST_REQUIRED_SECTIONS = [
    "Summary",
    "Key Themes",
    "Speakers & Roles",
    "Structural Breakdown",
    "SEO Keywords",
]


def _analyst_rules(
    title_max: int = 80,
    short_max: int = 90,
    long_max: int = 350,
    keywords_count: dict | None = None,
    required_sections: list[str] | None = None,
    content_type_overrides: dict | None = None,
) -> StyleRules:
    raw = {
        "meta": {"version": 1},
        "voice": {
            "forbidden_phrases": [
                {"match": "watch as", "category": "viewer_directive", "severity": "error"},
                {"match": "amazing", "category": "superlative", "severity": "error"},
                {"match": "join us", "category": "cta", "severity": "error"},
            ],
            "first_person_markers": [r"\bwe\b", r"\bour\b"],
            "second_person_markers": [r"\byou\b"],
        },
        "casing": {
            "style": "down",
            "proper_nouns": ["Wisconsin"],
            "acronyms": ["PBS"],
            "casing_variants": {},
            "surname_stoplist": ["van", "der", "de", "la", "the"],
        },
        "limits": {
            "fields": {
                "title": {"max": title_max},
                "short_description": {"max": short_max},
                "long_description": {"max": long_max},
                "keywords": {"count": keywords_count or {"min": 15, "max": 20}},
            },
            "content_type_overrides": content_type_overrides or {},
        },
        "phases": {
            "analyst": {
                "required_sections": (
                    _DEFAULT_ANALYST_REQUIRED_SECTIONS if required_sections is None else required_sections
                )
            }
        },
        "programs": {},
    }
    return StyleRules(raw=raw)


ANALYST_SPEAKER_SRT = _build_srt(
    [
        (0, 3000, "Welcome to the show today."),
        (6000, 30000, ">> Nick Hoffman: Let's talk about the state budget."),
        (498000, 600000, "Thanks for watching, we'll see you next time."),
    ]
)


def _analyst_context(**overrides) -> dict:
    context = {
        "transcript_file": "2WLI1234HD.srt",
        "transcript": ANALYST_SPEAKER_SRT,
        "project_name": "2WLI1234HD",
    }
    context.update(overrides)
    return context


def _analyst_document(
    *,
    include_summary: bool = True,
    include_themes: bool = True,
    include_speakers: bool = True,
    include_structure: bool = True,
    include_seo_keywords: bool = True,
    trailing: str = "This document ends cleanly.",
) -> str:
    parts = []
    if include_summary:
        parts.append("## Summary\n\nAn overview of the episode content and its main narrative arc.")
    if include_themes:
        parts.append("## Key Themes\n\n1. **Budget**: discussion of the state budget.")
    if include_speakers:
        parts.append(
            "## Speakers & Roles\n\n"
            "| Speaker | Role/Title | Context | First Appearance |\n"
            "|---|---|---|---|\n"
            "| Nick Hoffman | Host | Budget debate | 1:20 |"
        )
    if include_structure:
        parts.append("## Structural Breakdown\n\n### Act 1: Introduction (0:00 - 1:00)\n- Intro material.")
    if include_seo_keywords:
        parts.append("## SEO Keywords (Preliminary)\n\n**Primary:** budget")
    if trailing:
        parts.append(trailing)
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# run_pre_stage -- analyst phase: data
# ---------------------------------------------------------------------------


class TestPreStageAnalystData:
    def test_duration_minutes_exact_from_srt(self):
        rules = _analyst_rules()
        result = run_pre_stage("analyst", _analyst_context(), rules)
        assert result.phase == "analyst"
        assert result.data["duration_minutes"] == 600000 / 60000

    def test_word_count_whitespace_split_of_transcript(self):
        rules = _analyst_rules()
        result = run_pre_stage("analyst", {"transcript": "one two three four five"}, rules)
        assert result.data["word_count"] == 5

    def test_project_name_and_transcript_file_pass_through(self):
        rules = _analyst_rules()
        result = run_pre_stage("analyst", {"project_name": "2WLI9999HD", "transcript_file": "2WLI9999HD.srt"}, rules)
        assert result.data["project_name"] == "2WLI9999HD"
        assert result.data["transcript_file"] == "2WLI9999HD.srt"

    def test_char_budgets_from_rules_limits(self):
        rules = _analyst_rules(title_max=42, short_max=17, long_max=99)
        result = run_pre_stage("analyst", {}, rules)
        assert result.data["char_budgets"] == {"title": 42, "short_description": 17, "long_description": 99}

    def test_char_budgets_excludes_keyword_count(self):
        # keywords is count-shaped (min/max), not max-shaped -- must never
        # leak into char_budgets (which is string-field maxes only).
        rules = _analyst_rules()
        result = run_pre_stage("analyst", {}, rules)
        assert "keywords" not in result.data["char_budgets"]

    def test_char_budgets_reflect_content_type_override(self):
        # Proves char_budgets is computed from rules.limits_for(program,
        # content_type), not hardcoded -- an odd override collapses title to 5.
        rules = _analyst_rules(content_type_overrides={"short": {"title": {"max": 5}}})
        result = run_pre_stage("analyst", {"content_type": "short"}, rules)
        assert result.data["char_budgets"]["title"] == 5


# ---------------------------------------------------------------------------
# run_pre_stage -- analyst phase: graceful degradation
# ---------------------------------------------------------------------------


class TestPreStageAnalystGraceful:
    def test_empty_context_does_not_raise(self):
        rules = _analyst_rules()
        result = run_pre_stage("analyst", {}, rules)
        assert result.phase == "analyst"
        assert result.data["duration_minutes"] is None
        assert result.data["word_count"] == 0
        assert result.data["project_name"] is None
        assert result.data["transcript_file"] is None
        assert result.prompt_section  # still renders (Voice line always present)

    def test_non_srt_transcript_file_falls_back_to_context_duration(self):
        rules = _analyst_rules()
        result = run_pre_stage(
            "analyst",
            {"transcript_file": "episode.txt", "transcript": "plain text", "duration_minutes": 12.5},
            rules,
        )
        assert result.data["duration_minutes"] == 12.5

    def test_srt_file_unparseable_content_falls_back_to_context_duration(self):
        rules = _analyst_rules()
        result = run_pre_stage(
            "analyst",
            {"transcript_file": "episode.srt", "transcript": "not real srt content", "duration_minutes": 9.0},
            rules,
        )
        assert result.data["duration_minutes"] == 9.0

    def test_no_duration_source_at_all_is_none(self):
        rules = _analyst_rules()
        result = run_pre_stage("analyst", {"transcript_file": "episode.txt", "transcript": "plain text"}, rules)
        assert result.data["duration_minutes"] is None

    def test_no_limits_in_rules_yields_empty_char_budgets_and_still_renders(self):
        rules = StyleRules(raw={"meta": {"version": 1}})
        result = run_pre_stage("analyst", {}, rules)
        assert result.data["char_budgets"] == {}
        assert result.prompt_section  # Voice line still renders ("(none)")


# ---------------------------------------------------------------------------
# run_pre_stage -- analyst phase: prompt section rendering
# ---------------------------------------------------------------------------


class TestPreStageAnalystPromptSection:
    def test_section_header_present(self):
        rules = _analyst_rules()
        result = run_pre_stage("analyst", {}, rules)
        assert "## Style Rules (authoritative)" in result.prompt_section

    def test_verified_facts_line_includes_all_available_facts(self):
        rules = _analyst_rules()
        result = run_pre_stage("analyst", _analyst_context(), rules)
        assert "Verified facts" in result.prompt_section
        assert "never estimate these" in result.prompt_section
        assert "duration 10.0 minutes" in result.prompt_section
        assert "transcript ~" in result.prompt_section
        assert "project 2WLI1234HD" in result.prompt_section
        assert "source file 2WLI1234HD.srt" in result.prompt_section

    def test_verified_facts_omits_missing_duration_gracefully(self):
        rules = _analyst_rules()
        result = run_pre_stage("analyst", {"project_name": "2WLI0001HD"}, rules)
        facts_line = next(line for line in result.prompt_section.splitlines() if "Verified facts" in line)
        assert "duration" not in facts_line
        assert "project 2WLI0001HD" in facts_line

    def test_verified_facts_line_absent_when_nothing_available(self):
        rules = _analyst_rules()
        result = run_pre_stage("analyst", {}, rules)
        assert "Verified facts" not in result.prompt_section

    def test_zero_word_transcript_omits_word_count_fact(self):
        rules = _analyst_rules()
        result = run_pre_stage("analyst", {"project_name": "X"}, rules)
        facts_line = next(line for line in result.prompt_section.splitlines() if "Verified facts" in line)
        assert "words" not in facts_line

    def test_draft_metadata_guidance_data_driven_not_hardcoded(self):
        # Odd values must show up verbatim, proving the numbers are read
        # from rules, never hardcoded prose (mirrors the formatter pattern).
        rules = _analyst_rules(title_max=42, short_max=17, long_max=99, keywords_count={"min": 3, "max": 7})
        result = run_pre_stage("analyst", {}, rules)
        assert "Draft title ≤ 42 chars" in result.prompt_section
        assert "draft short description ≤ 17" in result.prompt_section
        assert "draft long description ≤ 99" in result.prompt_section
        assert "3-7 keywords" in result.prompt_section

    def test_draft_metadata_guidance_real_config_values(self):
        rules = _analyst_rules()
        result = run_pre_stage("analyst", {}, rules)
        assert "Draft metadata guidance" in result.prompt_section
        assert "Draft title ≤ 80 chars" in result.prompt_section
        assert "draft short description ≤ 90" in result.prompt_section
        assert "draft long description ≤ 350" in result.prompt_section
        assert "15-20 keywords" in result.prompt_section

    def test_voice_do_not_list_present_and_reuses_seo_rendering(self):
        rules = _analyst_rules()
        result = run_pre_stage("analyst", {}, rules)
        seo_result = run_pre_stage("seo", {}, rules)
        assert "**Voice:**" in result.prompt_section
        # Same rendering helper -- the "Never use: ..." clause is identical
        # text in both phases' rendered sections.
        analyst_voice_line = next(line for line in result.prompt_section.splitlines() if line.startswith("**Voice:**"))
        seo_voice_line = next(line for line in seo_result.prompt_section.splitlines() if line.startswith("**Voice:**"))
        assert analyst_voice_line == seo_voice_line


# ---------------------------------------------------------------------------
# run_post_stage -- analyst phase: analyst.section_missing
# ---------------------------------------------------------------------------


class TestPostStageAnalystSectionMissing:
    def test_all_required_sections_present_no_violation(self):
        rules = _analyst_rules()
        raw_output = _analyst_document()
        result = run_post_stage("analyst", raw_output, {}, rules)
        assert [v for v in result.check.violations if v.rule_id == "analyst.section_missing"] == []

    def test_missing_section_flagged(self):
        rules = _analyst_rules()
        raw_output = _analyst_document(include_themes=False)
        result = run_post_stage("analyst", raw_output, {}, rules)
        missing = [v for v in result.check.violations if v.rule_id == "analyst.section_missing"]
        assert len(missing) == 1
        assert "Key Themes" in missing[0].message
        assert missing[0].severity == "warning"
        assert missing[0].model_fixable is True

    def test_multiple_missing_sections_each_flagged(self):
        rules = _analyst_rules()
        raw_output = _analyst_document(include_themes=False, include_structure=False)
        result = run_post_stage("analyst", raw_output, {}, rules)
        missing_ids = {v.rule_id for v in result.check.violations if v.rule_id == "analyst.section_missing"}
        assert missing_ids == {"analyst.section_missing"}
        messages = [v.message for v in result.check.violations if v.rule_id == "analyst.section_missing"]
        assert any("Key Themes" in m for m in messages)
        assert any("Structural Breakdown" in m for m in messages)

    def test_heading_match_is_case_insensitive(self):
        rules = _analyst_rules()
        raw_output = _analyst_document(include_themes=False) + "\n\n## key THEMES\n\nlowercase heading variant."
        result = run_post_stage("analyst", raw_output, {}, rules)
        assert [v for v in result.check.violations if v.rule_id == "analyst.section_missing"] == []

    def test_seo_keywords_heading_matches_real_parenthetical_variant(self):
        # The real analyst.md heading is "## SEO Keywords (Preliminary)" --
        # the required_sections entry is just "SEO Keywords" (substring match).
        rules = _analyst_rules()
        raw_output = (
            _analyst_document(include_seo_keywords=False) + "\n\n## SEO Keywords (Preliminary)\n\nkeywords here."
        )
        result = run_post_stage("analyst", raw_output, {}, rules)
        assert [v for v in result.check.violations if v.rule_id == "analyst.section_missing"] == []

    def test_no_required_sections_configured_skips_check(self):
        rules = _analyst_rules(required_sections=[])
        raw_output = "## Only One Heading\n\nnot much else."
        result = run_post_stage("analyst", raw_output, {}, rules)
        assert [v for v in result.check.violations if v.rule_id == "analyst.section_missing"] == []


# ---------------------------------------------------------------------------
# run_post_stage -- analyst phase: analyst.speaker_table_unparseable
# ---------------------------------------------------------------------------


class TestPostStageAnalystSpeakerTable:
    def test_substantial_output_without_names_flagged(self):
        rules = _analyst_rules()
        raw_output = "## Summary\n\n" + ("word " * 60) + "no names anywhere in this document at all."
        result = run_post_stage("analyst", raw_output, {}, rules)
        unparseable = [v for v in result.check.violations if v.rule_id == "analyst.speaker_table_unparseable"]
        assert len(unparseable) == 1
        assert unparseable[0].severity == "warning"
        assert unparseable[0].model_fixable is True

    def test_substantial_output_with_names_not_flagged(self):
        rules = _analyst_rules()
        raw_output = _analyst_document(trailing="word " * 60 + "with a clean ending.")
        result = run_post_stage("analyst", raw_output, {}, rules)
        assert [v for v in result.check.violations if v.rule_id == "analyst.speaker_table_unparseable"] == []

    def test_short_output_without_names_not_flagged(self):
        # <=50 words: too thin for the missing-table signal to mean anything.
        rules = _analyst_rules()
        raw_output = "## Summary\n\nA short document with no speaker table."
        assert len(raw_output.split()) <= 50
        result = run_post_stage("analyst", raw_output, {}, rules)
        assert [v for v in result.check.violations if v.rule_id == "analyst.speaker_table_unparseable"] == []


# ---------------------------------------------------------------------------
# run_post_stage -- analyst phase: analyst.truncation_suspect
# ---------------------------------------------------------------------------


class TestPostStageAnalystTruncation:
    def test_missing_terminal_punctuation_flagged_not_model_fixable(self):
        rules = _analyst_rules()
        raw_output = _analyst_document(trailing="This line just trails off without")
        result = run_post_stage("analyst", raw_output, {}, rules)
        truncated = [v for v in result.check.violations if v.rule_id == "analyst.truncation_suspect"]
        assert len(truncated) == 1
        assert truncated[0].severity == "warning"
        assert truncated[0].model_fixable is False

    def test_clean_terminal_punctuation_not_flagged(self):
        rules = _analyst_rules()
        raw_output = _analyst_document(trailing="This document ends with a clean sentence.")
        result = run_post_stage("analyst", raw_output, {}, rules)
        assert [v for v in result.check.violations if v.rule_id == "analyst.truncation_suspect"] == []

    def test_shares_detection_with_lint_formatter_truncation_check(self):
        # Same excerpt-producing logic as lint.py's formatter path --
        # not duplicated, just reused with a different rule_id/model_fixable.
        from api.services.style_engine.lint import find_truncation_excerpt

        raw_output = _analyst_document(trailing="This line just trails off without")
        assert find_truncation_excerpt(raw_output) is not None


# ---------------------------------------------------------------------------
# run_post_stage -- analyst phase: never rewrites
# ---------------------------------------------------------------------------


class TestPostStageAnalystNeverRewrites:
    def test_changed_always_false_even_with_violations(self):
        rules = _analyst_rules()
        raw_output = "## Summary\n\n" + ("word " * 60) + "no names and no ending punctuation"
        result = run_post_stage("analyst", raw_output, {}, rules)
        assert result.check.violations  # sanity: violations did fire
        assert result.changed is False
        assert result.normalized_output == raw_output

    def test_changed_always_false_on_clean_output(self):
        rules = _analyst_rules()
        raw_output = _analyst_document()
        result = run_post_stage("analyst", raw_output, {}, rules)
        assert result.changed is False
        assert result.normalized_output == raw_output

    def test_parse_ok_always_true(self):
        rules = _analyst_rules()
        result = run_post_stage("analyst", "", {}, rules)
        assert result.check.parse_ok is True
        assert result.check.skipped is False

    def test_empty_output_does_not_raise(self):
        rules = _analyst_rules()
        result = run_post_stage("analyst", "", {}, rules)
        assert result.normalized_output == ""
        assert result.changed is False
