"""Tests for the style_engine SEO field extractor (span-aware).

Covers api.services.style_engine.phase_io: extract_seo_fields, FieldSpan,
SeoFields. Port/extension of scripts/poc_house_style_normalizer.py's
extract_recommended, extended to return exact character spans into the
source document (so a later stage can splice normalized values back in
place). All sample seo_output.md text is synthetic, built inline to mirror
the real prompts/seo.md output template shape (including its parenthetical
heading suffixes like "### Title (Final Recommendation)").
"""

from __future__ import annotations

import pytest

from api.services.style_engine.phase_io import (
    FieldSpan,
    SeoFields,
    extract_seo_fields,
    splice_seo_fields,
)

# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------

REALISTIC_SEO_MD = """<!-- Provenance: Generated by cardigan-v4 seo phase -->

# SEO Report
**Project:** TEST123
**Program:** Here & Now
**Date Processed:** 2026-07-10
**Agent:** seo-specialist
**Model:** anthropic/claude-sonnet-5

---

## Optimized Metadata

### Title (Final Recommendation)

**Recommended:**
Wisconsin Governor Signs New Budget Bill

**Character Count:** 42/60

**Keywords Included:** budget, Wisconsin, governor

**Reasoning:**
Leads with the primary keyword and stays well under the limit.

**Alternatives:**
1. Gov. Evers Signs State Budget Into Law
2. New Wisconsin Budget Bill Becomes Law

---

### Short Description (150 chars max)

**Recommended:**
Gov. Tony Evers signs the state budget, outlining new investments in education and infrastructure across Wisconsin.

**Character Count:** 118/150

**Keywords Included:** budget, education, infrastructure

---

### Long Description (300 chars max)

**Recommended:**
Wisconsin Gov. Tony Evers signs a new state budget bill, directing significant new investments toward public education, transportation infrastructure, and rural broadband access across the state, following months of bipartisan negotiation.

**Character Count:** 240/300

**Keywords Included:** budget, education, broadband

---
"""

NO_COMMENT_SEO_MD = REALISTIC_SEO_MD.split("-->\n\n", 1)[1]

MISSING_LONG_DESC_SEO_MD = """# SEO Report

### Title (Final Recommendation)

**Recommended:**
Wisconsin Governor Signs New Budget Bill

**Character Count:** 42/60

---

### Short Description (150 chars max)

**Recommended:**
Gov. Tony Evers signs the state budget today.

**Character Count:** 46/150
"""

EMPTY_SEO_MD = "# SEO Report\n\nNo recommendations generated.\n"


# ---------------------------------------------------------------------------
# extract_seo_fields -- round-trip span fidelity
# ---------------------------------------------------------------------------


class TestSpanFidelity:
    def test_title_span_exact(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        assert fields.title is not None
        assert fields.title.value == "Wisconsin Governor Signs New Budget Bill"
        assert REALISTIC_SEO_MD[fields.title.start : fields.title.end] == fields.title.value

    def test_short_description_span_exact(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        assert fields.short_description is not None
        expected = (
            "Gov. Tony Evers signs the state budget, outlining new investments "
            "in education and infrastructure across Wisconsin."
        )
        assert fields.short_description.value == expected
        assert (
            REALISTIC_SEO_MD[fields.short_description.start : fields.short_description.end]
            == fields.short_description.value
        )

    def test_long_description_span_exact(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        assert fields.long_description is not None
        assert (
            REALISTIC_SEO_MD[fields.long_description.start : fields.long_description.end]
            == fields.long_description.value
        )
        assert fields.long_description.value.startswith("Wisconsin Gov. Tony Evers signs")

    def test_all_three_spans_hold_simultaneously(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        for span in (fields.title, fields.short_description, fields.long_description):
            assert span is not None
            assert REALISTIC_SEO_MD[span.start : span.end] == span.value


# ---------------------------------------------------------------------------
# extract_seo_fields -- missing sections
# ---------------------------------------------------------------------------


class TestMissingSections:
    def test_missing_long_description_is_none(self):
        fields = extract_seo_fields(MISSING_LONG_DESC_SEO_MD)
        assert fields.title is not None
        assert fields.short_description is not None
        assert fields.long_description is None

    def test_no_recommendations_all_none(self):
        fields = extract_seo_fields(EMPTY_SEO_MD)
        assert fields.title is None
        assert fields.short_description is None
        assert fields.long_description is None

    def test_empty_document_all_none(self):
        fields = extract_seo_fields("")
        assert fields.title is None
        assert fields.short_description is None
        assert fields.long_description is None

    def test_missing_never_raises(self):
        # Graceful: malformed/partial input must not raise.
        extract_seo_fields("### Title\n\nNo recommended line here.\n")


# ---------------------------------------------------------------------------
# extract_seo_fields -- provenance header tolerance
# ---------------------------------------------------------------------------


class TestProvenanceHeaderTolerance:
    def test_leading_comment_does_not_break_extraction(self):
        with_comment = extract_seo_fields(REALISTIC_SEO_MD)
        without_comment = extract_seo_fields(NO_COMMENT_SEO_MD)
        assert with_comment.title.value == without_comment.title.value
        assert with_comment.short_description.value == without_comment.short_description.value
        assert with_comment.long_description.value == without_comment.long_description.value

    def test_leading_comment_shifts_but_preserves_span_validity(self):
        with_comment = extract_seo_fields(REALISTIC_SEO_MD)
        without_comment = extract_seo_fields(NO_COMMENT_SEO_MD)
        # The comment adds a prefix, so the with-comment span must start
        # later in the document, but must still be exact for its own text.
        assert with_comment.title.start > without_comment.title.start
        assert REALISTIC_SEO_MD[with_comment.title.start : with_comment.title.end] == with_comment.title.value


# ---------------------------------------------------------------------------
# SeoFields.to_dict / FieldSpan
# ---------------------------------------------------------------------------


class TestSeoFieldsToDict:
    def test_to_dict_shape_with_values(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        d = fields.to_dict()
        assert d["title"]["value"] == "Wisconsin Governor Signs New Budget Bill"
        assert isinstance(d["title"]["start"], int)
        assert isinstance(d["title"]["end"], int)

    def test_to_dict_none_for_missing_fields(self):
        fields = extract_seo_fields(EMPTY_SEO_MD)
        d = fields.to_dict()
        assert d["title"] is None
        assert d["short_description"] is None
        assert d["long_description"] is None

    def test_field_span_is_plain_dataclass(self):
        span = FieldSpan(value="Hello", start=0, end=5)
        assert span.value == "Hello"
        assert span.start == 0
        assert span.end == 5

    def test_seo_fields_defaults_all_none(self):
        fields = SeoFields()
        assert fields.title is None
        assert fields.short_description is None
        assert fields.long_description is None


# ---------------------------------------------------------------------------
# splice_seo_fields -- round trip
# ---------------------------------------------------------------------------


class TestSpliceRoundTrip:
    def test_single_replacement_round_trips(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        new_title = "Wisconsin Gov. Signs Budget Into Law"
        spliced = splice_seo_fields(REALISTIC_SEO_MD, fields, {"title": new_title})
        reparsed = extract_seo_fields(spliced)
        assert reparsed.title is not None
        assert reparsed.title.value == new_title
        # Unaffected fields are untouched.
        assert reparsed.short_description.value == fields.short_description.value
        assert reparsed.long_description.value == fields.long_description.value

    def test_three_replacements_round_trip(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        replacements = {
            "title": "New Wisconsin Title",
            "short_description": "New short description text.",
            "long_description": "New long description text, considerably longer than the others.",
        }
        spliced = splice_seo_fields(REALISTIC_SEO_MD, fields, replacements)
        reparsed = extract_seo_fields(spliced)
        assert reparsed.title.value == replacements["title"]
        assert reparsed.short_description.value == replacements["short_description"]
        assert reparsed.long_description.value == replacements["long_description"]

    def test_replacements_with_different_lengths_do_not_corrupt_earlier_spans(self):
        # title comes before short_description/long_description in the doc;
        # replacing title with something much longer/shorter must not shift
        # the later fields' correctness (splice-from-the-end guarantees this).
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        replacements = {
            "title": "X",
            "long_description": "Y" * 500,
        }
        spliced = splice_seo_fields(REALISTIC_SEO_MD, fields, replacements)
        reparsed = extract_seo_fields(spliced)
        assert reparsed.title.value == "X"
        assert reparsed.long_description.value == "Y" * 500
        assert reparsed.short_description.value == fields.short_description.value


# ---------------------------------------------------------------------------
# splice_seo_fields -- identity / no-op
# ---------------------------------------------------------------------------


class TestSpliceIdentity:
    def test_empty_replacements_returns_document_unchanged(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        spliced = splice_seo_fields(REALISTIC_SEO_MD, fields, {})
        assert spliced == REALISTIC_SEO_MD

    def test_unknown_replacement_key_is_ignored(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        spliced = splice_seo_fields(REALISTIC_SEO_MD, fields, {"nonexistent_field": "value"})
        assert spliced == REALISTIC_SEO_MD

    def test_replacement_for_missing_span_is_ignored(self):
        fields = extract_seo_fields(MISSING_LONG_DESC_SEO_MD)
        assert fields.long_description is None
        spliced = splice_seo_fields(MISSING_LONG_DESC_SEO_MD, fields, {"long_description": "should not appear"})
        assert spliced == MISSING_LONG_DESC_SEO_MD


# ---------------------------------------------------------------------------
# splice_seo_fields -- span-integrity guard
# ---------------------------------------------------------------------------


class TestSpliceIntegrityGuard:
    def test_tampered_document_raises_value_error(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        # Tamper with the document at the title's span so it no longer
        # matches the value captured in `fields`.
        tampered = (
            REALISTIC_SEO_MD[: fields.title.start]
            + "Something Completely Different"
            + REALISTIC_SEO_MD[fields.title.end :]
        )
        with pytest.raises(ValueError):
            splice_seo_fields(tampered, fields, {"title": "New Title"})

    def test_error_message_names_the_field(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        tampered = (
            REALISTIC_SEO_MD[: fields.title.start]
            + "Something Completely Different"
            + REALISTIC_SEO_MD[fields.title.end :]
        )
        with pytest.raises(ValueError, match="title"):
            splice_seo_fields(tampered, fields, {"title": "New Title"})

    def test_untampered_fields_still_splice_when_another_field_is_tampered(self):
        # Tampering title's span (with a same-length replacement, so later
        # spans' offsets are undisturbed) but only replacing
        # short_description must not raise -- the guard only checks fields
        # actually being spliced.
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        same_length_tamper = "Z" * len(fields.title.value)
        tampered = REALISTIC_SEO_MD[: fields.title.start] + same_length_tamper + REALISTIC_SEO_MD[fields.title.end :]
        spliced = splice_seo_fields(tampered, fields, {"short_description": "New short desc."})
        reparsed = extract_seo_fields(spliced)
        assert reparsed.short_description.value == "New short desc."


# ---------------------------------------------------------------------------
# splice_seo_fields -- byte-for-byte preservation outside spans
# ---------------------------------------------------------------------------


class TestSplicePreservesSurroundingText:
    def test_text_outside_spans_is_byte_identical(self):
        fields = extract_seo_fields(REALISTIC_SEO_MD)
        new_title = "Shorter Title"
        spliced = splice_seo_fields(REALISTIC_SEO_MD, fields, {"title": new_title})
        # Everything before the title's span is untouched.
        assert spliced[: fields.title.start] == REALISTIC_SEO_MD[: fields.title.start]
        # Everything after the title's span (shifted by the length delta) is untouched.
        tail_start_spliced = fields.title.start + len(new_title)
        tail_start_original = fields.title.end
        assert spliced[tail_start_spliced:] == REALISTIC_SEO_MD[tail_start_original:]
