"""Tests for the worker's style-engine pre/post hooks (routing.style_engine).

Wires the pure `run_pre_stage`/`run_post_stage` pipeline stages
(api/services/style_engine/{pre_stage,post_stage}.py) into `JobWorker._run_phase`
behind default-off `routing.style_engine` config flags. Covers:

1. Kill switch -- missing config block, `enabled: false`, or phase mode "off"
   must produce byte-for-byte today's behavior (proven separately by the
   unmodified tests/api/test_worker.py suite staying green; also asserted
   directly here for the persisted-file format).
2. Pre-generation hook -- prompt-section injection into the built user
   prompt, and the stale-state guard that pops any leftover `style_pre` from
   a previous phase.
3. Post-generation hook -- shadow mode (record-only, raw content flows) vs.
   enforce mode (normalized content persists, `.raw.md` archive, provenance
   line) vs. fail-open on any exception (missing rules file, event-logging
   failure).

Follows tests/api/test_worker.py's fixture/mocking conventions (mock_llm_client,
mock_llm_response, AGENTS_DIR patched to redirect into tmp_path).
"""

import json
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
import yaml

from api.models.events import EventType
from api.services import worker as worker_mod
from api.services.escalation import classify_qa_failure
from api.services.worker import JobWorker

# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------


@pytest.fixture
def mock_llm_client():
    """Create a mock LLM client. Mirrors tests/api/test_worker.py's fixture --
    `config["routing"]` deliberately has no `style_engine` key, which is the
    kill-switch default state."""
    client = MagicMock()
    client.config = {
        "routing": {
            "long_form_threshold_minutes": 15,
        }
    }
    client.get_backend_for_phase.return_value = "openrouter-cheapskate"
    return client


@pytest.fixture
def mock_llm_response():
    """Create a mock LLM response."""
    response = MagicMock()
    response.content = "Test output content"
    response.cost = 0.001
    response.total_tokens = 500
    response.model = "test-model"
    return response


def _style_engine_cfg(rules_file, phases=None, enabled=True, keep_raw_on_fix=True, qa_gate=None):
    cfg = {
        "enabled": enabled,
        "rules_file": str(rules_file),
        "keep_raw_on_fix": keep_raw_on_fix,
        "phases": phases or {},
    }
    if qa_gate is not None:
        cfg["qa_gate"] = qa_gate
    return cfg


def _write_rules(tmp_path, title_max=80, short_max=90, long_max=350):
    """Minimal house-style YAML covering both pre-stage and post-stage needs.
    Mirrors the synthetic StyleRules built inline in tests/test_style_stages.py."""
    raw = {
        "meta": {"version": 1},
        "voice": {
            "forbidden_phrases": [
                {"match": "discover", "category": "viewer_directive", "severity": "error"},
            ],
            "first_person_markers": [r"\bwe\b", r"\bour\b"],
            "second_person_markers": [r"\byou\b"],
        },
        "casing": {
            "style": "down",
            "proper_nouns": ["Wisconsin", "Governor", "Madison"],
            "acronyms": ["PBS"],
            "casing_variants": {},
            "surname_stoplist": [],
        },
        "limits": {
            "fields": {
                "title": {"max": title_max},
                "short_description": {"max": short_max},
                "long_description": {"max": long_max},
            },
            "content_type_overrides": {},
        },
        "programs": {},
    }
    path = tmp_path / "house_style.yaml"
    path.write_text(yaml.safe_dump(raw))
    return path


def _seo_report(
    title: str,
    short_description: str = "A short description of the episode.",
    long_description: str = "A longer description of the episode content, spanning more detail than the short one.",
) -> str:
    return (
        "# SEO Report\n\n"
        "### Title (Final Recommendation)\n\n"
        "**Recommended:**\n"
        f"{title}\n\n"
        "**Character Count:** 0\n\n"
        "---\n\n"
        "### Short Description (150 chars max)\n\n"
        "**Recommended:**\n"
        f"{short_description}\n\n"
        "---\n\n"
        "### Long Description (300 chars max)\n\n"
        "**Recommended:**\n"
        f"{long_description}\n\n"
        "---\n"
    )


ANALYST_TABLE = """<!-- Provenance: Generated by cardigan-v4 analyst phase -->

## Speakers & Roles

| Speaker | Role/Title | Topic | Time |
|---|---|---|---|
| Nick Hoffman | Host | Budget debate | 1:20 |
"""


# ---------------------------------------------------------------------------
# 1. Kill switch: all-off -- byte-for-byte today's behavior
# ---------------------------------------------------------------------------


class TestKillSwitch:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_no_style_engine_block_is_pure_passthrough(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """No `routing.style_engine` key at all -- _run_phase must behave exactly
        as it did before this task: no style_pre, no style_checks, output is the
        raw LLM content, and the persisted file has no style-engine provenance
        line."""
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Test transcript"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["success"] is True
        assert result["output"] == "Test output content"
        assert "style_pre" not in context
        assert "style_checks" not in context

        expected_header = "<!-- model: test-model | cost: $0.0010 | tokens: 500 -->\n"
        assert (tmp_path / "seo_output.md").read_text() == expected_header + "Test output content"

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_enabled_false_is_pure_passthrough(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """style_engine block present but enabled: false -- same kill-switch
        guarantee as a missing block."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path,
                    phases={"seo": {"pre": True, "post": "enforce"}},
                    enabled=False,
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Test transcript", "analyst_output": ANALYST_TABLE}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["output"] == "Test output content"
        assert "style_pre" not in context
        assert "style_checks" not in context
        assert not (tmp_path / "seo_output.raw.md").exists()

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_phase_mode_off_is_pure_passthrough(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """style_engine enabled globally but this phase's pre/post are off --
        no injection, no post-processing."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": False, "post": "off"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Test transcript", "analyst_output": ANALYST_TABLE}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["output"] == "Test output content"
        assert "style_pre" not in context
        assert "style_checks" not in context


# ---------------------------------------------------------------------------
# 2. Pre-generation hook
# ---------------------------------------------------------------------------


class TestPreHook:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_pre_enabled_injects_style_section_into_prompt(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": True, "post": "off"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Nick Hoffman opens the show.", "analyst_output": ANALYST_TABLE}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["success"] is True
        assert "style_pre" in context
        assert context["style_pre"]["prompt_section"].startswith("## Style Rules (authoritative)")

        sent_messages = mock_llm_client.chat.call_args.kwargs["messages"]
        user_message = sent_messages[1]["content"]
        assert "## Style Rules (authoritative)" in user_message
        assert "Nick Hoffman" in user_message

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_pre_disabled_omits_style_section(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": False, "post": "off"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Nick Hoffman opens the show.", "analyst_output": ANALYST_TABLE}

        await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert "style_pre" not in context
        sent_messages = mock_llm_client.chat.call_args.kwargs["messages"]
        user_message = sent_messages[1]["content"]
        assert "## Style Rules (authoritative)" not in user_message

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_stale_style_pre_popped_when_pre_disabled(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """A `style_pre` left in context by a previous phase must never leak
        into a phase whose pre-hook is off."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": False, "post": "off"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {
            "transcript": "Nick Hoffman opens the show.",
            "style_pre": {"prompt_section": "## Style Rules (authoritative)\nSTALE FROM PREVIOUS PHASE\n"},
        }

        await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert "style_pre" not in context
        sent_messages = mock_llm_client.chat.call_args.kwargs["messages"]
        user_message = sent_messages[1]["content"]
        assert "STALE FROM PREVIOUS PHASE" not in user_message


# ---------------------------------------------------------------------------
# 3. Post-generation hook: shadow vs enforce
# ---------------------------------------------------------------------------


class TestPostHookShadow:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_shadow_records_but_never_mutates(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": False, "post": "shadow"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_output = _seo_report("Discover Wisconsin's Budget Story")
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)

        logged_events = []

        async def _capture(event):
            logged_events.append(event)

        mock_log_event.side_effect = _capture
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        # Result output and persisted file are the RAW response content.
        assert result["success"] is True
        assert result["output"] == raw_output
        persisted = (tmp_path / "seo_output.md").read_text()
        assert persisted.endswith(raw_output)
        assert "style-engine:" not in persisted
        assert not (tmp_path / "seo_output.raw.md").exists()

        # But context + events record the check.
        assert "style_checks" in context
        violations = context["style_checks"]["seo"]["violations"]
        assert len(violations) >= 1

        style_violation_events = [e for e in logged_events if e.event_type == EventType.style_violation]
        assert len(style_violation_events) == len(violations)
        assert style_violation_events[0].data.phase == "seo"
        assert style_violation_events[0].data.extra["mode"] == "shadow"
        assert style_violation_events[0].data.extra["action"] == "shadow"


class TestPostHookEnforce:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_enforce_normalizes_and_writes_raw_archive(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": False, "post": "enforce"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_title = "Wisconsin Governor Signs New Budget Bill In Madison"
        raw_output = _seo_report(raw_title)
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        expected_title = "Wisconsin Governor signs new budget bill in Madison"
        assert result["success"] is True
        assert expected_title in result["output"]
        assert raw_title not in result["output"]

        persisted = (tmp_path / "seo_output.md").read_text()
        assert "<!-- style-engine: fixes: 1 | flags: 0 -->" in persisted
        assert expected_title in persisted

        raw_archive = tmp_path / "seo_output.raw.md"
        assert raw_archive.exists()
        assert raw_archive.read_text() == raw_output

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_enforce_keep_raw_on_fix_false_skips_archive(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path,
                    phases={"seo": {"pre": False, "post": "enforce"}},
                    keep_raw_on_fix=False,
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_title = "Wisconsin Governor Signs New Budget Bill In Madison"
        raw_output = _seo_report(raw_title)
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["success"] is True
        assert not (tmp_path / "seo_output.raw.md").exists()


# ---------------------------------------------------------------------------
# 4. Fail-open guarantees
# ---------------------------------------------------------------------------


class TestFailOpen:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_post_fails_open_on_missing_rules_file(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    tmp_path / "does_not_exist.yaml",
                    phases={"seo": {"pre": False, "post": "enforce"}},
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["success"] is True
        assert result["output"] == "Test output content"
        assert (tmp_path / "seo_output.md").read_text().endswith("Test output content")
        assert not (tmp_path / "seo_output.raw.md").exists()

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_pre_fails_open_on_missing_rules_file(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    tmp_path / "does_not_exist.yaml",
                    phases={"seo": {"pre": True, "post": "off"}},
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["success"] is True
        assert "style_pre" not in context

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    @patch("api.services.style_engine.run_post_stage")
    async def test_post_fails_open_when_log_event_raises(
        self, mock_run_post_stage, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """A style_violation log_event() failure must not fail the phase or
        leak a partially-applied normalization -- the raw content flows.

        Extended test: when log_event raises on a LATER violation (not the first),
        the style_checks[phase] entry must be cleaned up so the QA gate doesn't
        treat an incomplete event trail as a completed check."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": False, "post": "shadow"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_output = _seo_report(
            title="Discover Wisconsin Governor Signs New Budget Bill In Madison",
            short_description="Wisconsin Governor DISCOVERS the budget impact.",
            long_description="A longer description about what the Governor Discovered regarding the budget situation."
        )
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)

        # Mock post object with MULTIPLE violations to trigger loop iterations
        from api.services.style_engine.types import RuleViolation
        mock_post = MagicMock()
        mock_post.normalized_output = raw_output
        mock_post.changed = False

        # Create 2 violations to ensure loop iterates more than once
        violations = [
            RuleViolation(
                rule_id="voice.forbidden.viewer_directive",
                phase="seo",
                severity="error",
                message='Forbidden phrase "Discover"',
                field="title",
                span=[0, 8],
                model_fixable=True,
            ),
            RuleViolation(
                rule_id="casing.mismatch",
                phase="seo",
                severity="warning",
                message="Unexpected casing in field",
                field="short_description",
                span=[10, 20],
                model_fixable=True,
            ),
        ]
        mock_check = MagicMock()
        mock_check.violations = violations
        mock_check.to_dict.return_value = {"violations": [v.to_dict() for v in violations]}
        mock_post.check = mock_check
        mock_run_post_stage.return_value = mock_post

        call_count = [0]
        async def _flaky_log_event(event):
            """Log first violation successfully, raise on the second."""
            if event.event_type == EventType.style_violation:
                call_count[0] += 1
                if call_count[0] > 1:
                    raise RuntimeError("boom on second violation")
            return None

        mock_log_event.side_effect = _flaky_log_event
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["success"] is True
        assert result["output"] == raw_output
        assert not (tmp_path / "seo_output.raw.md").exists()

        # NEW ASSERTION: style_checks[seo] must NOT exist on fail-open path
        # (even though violations were found, the exception mid-loop leaves it partial)
        assert "seo" not in context.get("style_checks", {}), (
            "style_checks[seo] should be cleaned up on fail-open, "
            "but survived with partial state"
        )


# ---------------------------------------------------------------------------
# 5. Validator lint + merge hook (_apply_style_lint, task 2b)
#
# Wires `run_lint`/`merge_style_flags` (api/services/style_engine/{lint,
# qa_merge}.py, task 2a) into the worker's validation flow behind
# `routing.style_engine.phases.validator.lint` (off | shadow | enforce).
# ---------------------------------------------------------------------------


def _bare_worker(style_engine_cfg: dict) -> JobWorker:
    """A JobWorker with only `llm.config.routing.style_engine` stubbed --
    enough for `_apply_style_lint` (and, for the wiring test below,
    `_finalize_with_qa_gate`) without touching the DB/queue machinery."""
    worker = JobWorker.__new__(JobWorker)
    worker.llm = MagicMock()
    worker.llm.config = {"routing": {"style_engine": style_engine_cfg}}
    return worker


_CLEAN_FORMATTER_BODY = (
    "**John Smith:**\nDialogue text that is long enough to matter here and ends properly."
)


def _passing_verdict() -> dict:
    return {
        "overall": "pass",
        "phase_results": {
            "analyst": {"status": "pass", "flags": []},
            "formatter": {"status": "pass", "flags": []},
            "seo": {"status": "pass", "flags": []},
        },
    }


class TestValidatorLintHook:
    @pytest.mark.asyncio
    async def test_lint_off_explicit_is_passthrough(self, tmp_path, monkeypatch):
        """`validator.lint: "off"` -- the explicit off case (kill switch is
        covered generally by test_worker.py staying green; this is the
        lint-specific off assertion)."""
        rules_path = _write_rules(tmp_path)
        cfg = _style_engine_cfg(rules_path, phases={"validator": {"lint": "off"}})
        worker = _bare_worker(cfg)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        context = {
            "analyst_output": ANALYST_TABLE,
            "formatter_output": _CLEAN_FORMATTER_BODY,
            "seo_output": _seo_report("A reasonably short seo title"),
        }
        validation_data = _passing_verdict()

        result = await worker._apply_style_lint(job_id=1, context=context, validation_data=validation_data)

        assert result is validation_data
        assert "lint_checks" not in context

    @pytest.mark.asyncio
    async def test_shadow_records_events_and_lint_checks_without_merging(self, tmp_path, monkeypatch):
        rules_path = _write_rules(tmp_path, title_max=40)
        cfg = _style_engine_cfg(rules_path, phases={"validator": {"lint": "shadow"}})
        worker = _bare_worker(cfg)

        logged_events = []

        async def _capture(event):
            logged_events.append(event)

        monkeypatch.setattr(worker_mod, "log_event", _capture)

        over_limit_title = "This SEO Title Is Deliberately Written To Exceed The Forty Character Limit"
        context = {
            "analyst_output": ANALYST_TABLE,
            "formatter_output": _CLEAN_FORMATTER_BODY,
            "seo_output": _seo_report(over_limit_title),
        }
        validation_data = _passing_verdict()

        result = await worker._apply_style_lint(job_id=1, context=context, validation_data=validation_data)

        # Shadow mode is strictly record-only -- same object, no merge.
        assert result is validation_data

        assert "lint_checks" in context
        seo_violations = context["lint_checks"]["seo"]["violations"]
        assert any(v["rule_id"] == "lint.seo.title_over_limit" for v in seo_violations)

        lint_events = [e for e in logged_events if e.event_type == EventType.style_violation]
        assert lint_events, "expected at least one style_violation event from the lint suite"
        assert all(e.data.extra.get("source") == "lint" for e in lint_events)
        assert all(e.data.extra.get("mode") == "shadow" for e in lint_events)

    @pytest.mark.asyncio
    async def test_enforce_fail_on_error_appends_flag_and_flips_status(self, tmp_path, monkeypatch):
        rules_path = _write_rules(tmp_path, title_max=40)
        cfg = _style_engine_cfg(
            rules_path,
            phases={"validator": {"lint": "enforce"}},
            qa_gate={"merge_flags": True, "fail_on_error": True},
        )
        worker = _bare_worker(cfg)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        over_limit_title = "This SEO Title Is Deliberately Written To Exceed The Forty Character Limit"
        context = {
            "analyst_output": ANALYST_TABLE,
            "formatter_output": _CLEAN_FORMATTER_BODY,
            "seo_output": _seo_report(over_limit_title),
        }
        validation_data = _passing_verdict()

        result = await worker._apply_style_lint(job_id=1, context=context, validation_data=validation_data)

        assert result is not validation_data  # merge returns a fresh dict
        seo_flags = result["phase_results"]["seo"]["flags"]
        assert any(f.startswith("[style:lint.seo.title_over_limit]") for f in seo_flags)
        assert result["phase_results"]["seo"]["status"] == "fail"
        assert result["overall"] == "fail"
        # merge_style_flags never mutates its input.
        assert validation_data["overall"] == "pass"
        assert validation_data["phase_results"]["seo"]["flags"] == []

    @pytest.mark.asyncio
    async def test_enforce_nonfixable_lint_hit_routes_escalation_false(self, tmp_path, monkeypatch):
        """Formatter output missing -> lint.output_missing (model_fixable=False)
        -> merged flag carries the "[style-nonfixable:...]" prefix ->
        classify_qa_failure over the MERGED result returns escalate=False.
        Proves the end-to-end routing the escalation.py change enables."""
        rules_path = _write_rules(tmp_path)
        cfg = _style_engine_cfg(
            rules_path,
            phases={"validator": {"lint": "enforce"}},
            qa_gate={"merge_flags": True, "fail_on_error": True},
        )
        worker = _bare_worker(cfg)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        context = {
            "analyst_output": ANALYST_TABLE,
            # formatter_output intentionally omitted -> lint.output_missing
            "seo_output": _seo_report("A reasonably short seo title"),
        }
        validation_data = _passing_verdict()

        result = await worker._apply_style_lint(job_id=1, context=context, validation_data=validation_data)

        formatter_flags = result["phase_results"]["formatter"]["flags"]
        assert any(f.startswith("[style-nonfixable:lint.output_missing]") for f in formatter_flags)
        assert result["phase_results"]["formatter"]["status"] == "fail"
        assert result["overall"] == "fail"

        classed = classify_qa_failure(result, context)
        assert classed["escalate"] is False
        assert classed["nonfixable"]

    @pytest.mark.asyncio
    async def test_fail_open_on_bogus_rules_file(self, tmp_path, monkeypatch):
        cfg = _style_engine_cfg(
            tmp_path / "does_not_exist.yaml",
            phases={"validator": {"lint": "enforce"}},
            qa_gate={"merge_flags": True, "fail_on_error": True},
        )
        worker = _bare_worker(cfg)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())
        warning_calls = []
        monkeypatch.setattr(
            worker_mod.logger, "warning", lambda *a, **kw: warning_calls.append((a, kw))
        )

        context = {
            "analyst_output": ANALYST_TABLE,
            "formatter_output": _CLEAN_FORMATTER_BODY,
            "seo_output": _seo_report("A reasonably short seo title"),
        }
        validation_data = _passing_verdict()

        result = await worker._apply_style_lint(job_id=1, context=context, validation_data=validation_data)

        assert result is validation_data
        assert "lint_checks" not in context
        assert warning_calls, "fail-open must log a warning"

    @pytest.mark.asyncio
    async def test_none_validation_data_enforce_builds_merged_skeleton(self, tmp_path, monkeypatch):
        """Unparseable LLM validator output -> validation_data is None ->
        _apply_style_lint must still merge the lint flags into qa_merge's
        None-skeleton (exercises qa_merge's None path through the worker)."""
        rules_path = _write_rules(tmp_path)
        cfg = _style_engine_cfg(
            rules_path,
            phases={"validator": {"lint": "enforce"}},
            qa_gate={"merge_flags": True, "fail_on_error": True},
        )
        worker = _bare_worker(cfg)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        context: dict = {}  # all 3 canonical phase outputs missing

        result = await worker._apply_style_lint(job_id=1, context=context, validation_data=None)

        assert result["_merged_from_none"] is True
        assert result["overall"] == "fail"
        for phase in ("analyst", "formatter", "seo"):
            flags = result["phase_results"][phase]["flags"]
            assert any(f.startswith("[style-nonfixable:lint.output_missing]") for f in flags)
            assert result["phase_results"][phase]["status"] == "fail"


class TestFinalizeQaGateLintWiring:
    """Proves the SECOND call site (`_finalize_with_qa_gate`'s re-validation
    parse, ~worker.py:1440) routes through `_apply_style_lint` before the
    merged verdict decides completed vs. paused -- not just the main-loop
    parse point covered by TestValidatorLintHook above."""

    @pytest.mark.asyncio
    async def test_revalidation_merges_lint_flags_before_gate_decision(self, tmp_path, monkeypatch):
        rules_path = _write_rules(tmp_path)
        style_cfg = _style_engine_cfg(
            rules_path,
            phases={"validator": {"lint": "enforce"}},
            qa_gate={"merge_flags": True, "fail_on_error": True},
        )

        worker = JobWorker.__new__(JobWorker)
        worker.llm = MagicMock()
        worker.llm.config = {
            "qa_escalation": {
                "on_validation_fail": True,
                "max_auto_escalations": 1,
                "exclude_variants": ["fast", "fable"],
            },
            "routing": {"style_engine": style_cfg},
        }

        monkeypatch.setattr(worker_mod, "get_job", AsyncMock(return_value=None))
        monkeypatch.setattr(
            worker_mod, "resolve_escalated_model", AsyncMock(return_value="anthropic/claude-sonnet-4-6")
        )
        pause = AsyncMock()
        monkeypatch.setattr(worker_mod, "pause_and_suggest", pause)
        update_job_mock = AsyncMock()
        monkeypatch.setattr(worker_mod, "update_job", update_job_mock)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        passing_verdict_json = json.dumps(_passing_verdict())
        escalated_seo_output = (
            "Escalated seo output content that is comfortably longer than the "
            "fifty character substantive-length floor."
        )

        async def fake_run_phase(job_id, phase_name, context, project_path, model_override=None):
            if phase_name == "validator":
                return {"success": True, "output": passing_verdict_json, "model": "validator-model"}
            return {"success": True, "output": escalated_seo_output, "model": "strong-model"}

        monkeypatch.setattr(worker, "_run_phase", fake_run_phase)

        initial_validation_result = {
            "overall": "fail",
            "phase_results": {
                "analyst": {"status": "pass", "flags": []},
                "formatter": {"status": "pass", "flags": []},
                "seo": {"status": "fail", "flags": ["seo title needs shortening"]},
            },
        }
        context = {
            "analyst_output": ANALYST_TABLE,
            "seo_output": "stale pre-escalation seo output",
            # formatter_output intentionally omitted -- lint.output_missing
            # fires during the re-validation's _apply_style_lint call even
            # though the LLM's re-validation JSON claims formatter passed.
        }

        outcome = await worker._finalize_with_qa_gate(
            job_id=99,
            context=context,
            project_path=str(tmp_path),
            validation_result=initial_validation_result,
            phase_order=["analyst", "formatter", "seo", "validator"],
        )

        # Without the merge wired in, the LLM's re-validation JSON says
        # "pass" and the gate would complete. With it wired in, the missing
        # formatter output surfaces a non-fixable flag that flips the
        # persisted verdict to "fail" -- the gate must pause instead.
        assert outcome == "paused"
        pause.assert_awaited_once()

        persisted = [
            c.args[1]
            for c in update_job_mock.await_args_list
            if len(c.args) >= 2 and hasattr(c.args[1], "validation_result")
        ]
        assert persisted, "update_job was never called with a validation_result payload"
        merged = persisted[-1].validation_result
        assert merged["overall"] == "fail"
        formatter_flags = merged["phase_results"]["formatter"]["flags"]
        assert any(f.startswith("[style-nonfixable:lint.output_missing]") for f in formatter_flags)


class TestRetryRevalidationLintMerge:
    """Proves the THIRD call site (`retry_single_phase`'s post-retry re-validation
    parse, ~worker.py:564) routes through `_apply_style_lint` before persisting --
    not just the main-loop parse (TestValidatorLintHook) and QA-gate parse
    (TestFinalizeQaGateLintWiring) covered above."""

    @pytest.mark.asyncio
    async def test_retry_phase_merges_lint_flags_on_revalidation(self, tmp_path, monkeypatch):
        """After retrying a phase (e.g., seo), the re-run of the validator must
        merge lint flags before persisting the validation_result, so a manually
        retried job with validator.lint="enforce" does NOT bypass QA flags.

        This test proves the third validation-persist path routes through
        _apply_style_lint by verifying the hook is called with the parsed
        validator verdict and context, and the merged result is persisted."""
        rules_path = _write_rules(tmp_path, title_max=40)
        style_cfg = _style_engine_cfg(
            rules_path,
            phases={"validator": {"lint": "enforce"}},
            qa_gate={"merge_flags": True, "fail_on_error": True},
        )

        worker = JobWorker.__new__(JobWorker)
        worker.llm = MagicMock()
        worker.llm.config = {
            "routing": {"style_engine": style_cfg},
        }

        # Mock job with minimal fields needed for retry_single_phase
        existing_job = MagicMock()
        existing_job.model_dump.return_value = {
            "id": 42,
            "project_name": "Test Project",
            "transcript_file": "test.txt",
            "project_path": str(tmp_path),
            "word_count": 100,
            "duration_minutes": 5,
            "status": "completed",
            "phases": [
                {
                    "name": "seo",
                    "status": "completed",
                    "cost": 0.001,
                    "tokens": 100,
                    "input_tokens": 50,
                    "output_tokens": 50,
                    "model": "test-model",
                    "completed_at": "2024-01-01T00:00:00Z",
                    "retry_count": 0,
                }
            ],
        }
        existing_job.phases = existing_job.model_dump()["phases"]

        # Mock database operations - patch at the database module level since retry_single_phase imports locally
        from api.services import database as db_mod
        monkeypatch.setattr(
            db_mod, "get_job", AsyncMock(side_effect=[existing_job, existing_job, existing_job])
        )
        update_job_mock = AsyncMock()
        monkeypatch.setattr(db_mod, "update_job", update_job_mock)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        # Capture calls to _apply_style_lint to prove it's wired in
        original_apply_style_lint = worker._apply_style_lint
        apply_style_lint_calls = []

        async def mock_apply_style_lint(job_id, context, validation_data):
            apply_style_lint_calls.append({"job_id": job_id, "context": context, "validation_data": validation_data})
            # Call the real method to get actual merged result
            return await original_apply_style_lint(job_id, context, validation_data)

        monkeypatch.setattr(worker, "_apply_style_lint", mock_apply_style_lint)

        # Mock _run_phase to return retried phase output and passing validator JSON
        passing_verdict_json = json.dumps(_passing_verdict())

        async def fake_run_phase(job_id, phase_name, context, project_path, model_override=None):
            if phase_name == "validator":
                return {"success": True, "output": passing_verdict_json, "model": "validator-model"}
            else:
                return {"success": True, "output": "Retried phase output", "model": "test-model"}

        monkeypatch.setattr(worker, "_run_phase", fake_run_phase)

        # Write transcript file for load
        (tmp_path / "test.txt").write_text("Test transcript content")

        result = await worker.retry_single_phase(
            job_id=42,
            phase_name="seo",
            feedback="Tighten the title",
        )

        # Verify retry succeeded
        assert result["success"] is True

        # Prove _apply_style_lint was called during the retry's re-validation phase
        assert apply_style_lint_calls, "expected _apply_style_lint to be called during retry re-validation"
        call = apply_style_lint_calls[0]
        assert call["job_id"] == 42
        assert call["validation_data"]["overall"] == "pass"  # input is passing verdict

        # Verify the persisted validation_result is the merged one from _apply_style_lint
        persisted_validations = [
            c.args[1]
            for c in update_job_mock.await_args_list
            if len(c.args) >= 2 and hasattr(c.args[1], "validation_result") and c.args[1].validation_result
        ]
        assert persisted_validations, "update_job was never called with validation_result"

        # The last call should have the merged result
        final_validation = persisted_validations[-1].validation_result
        assert final_validation is not None
