"""Tests for the worker's style-engine pre/post hooks (routing.style_engine).

Wires the pure `run_pre_stage`/`run_post_stage` pipeline stages
(api/services/style_engine/{pre_stage,post_stage}.py) into `JobWorker._run_phase`
behind default-off `routing.style_engine` config flags. Covers:

1. Kill switch -- missing config block, `enabled: false`, or phase mode "off"
   must produce byte-for-byte today's behavior (proven separately by the
   unmodified tests/api/test_worker.py suite staying green; also asserted
   directly here for the persisted-file format).
2. Pre-generation hook -- prompt-section injection into the built user
   prompt, and the stale-state guard that pops any leftover `style_pre` from
   a previous phase.
3. Post-generation hook -- shadow mode (record-only, raw content flows) vs.
   enforce mode (normalized content persists, `.raw.md` archive, provenance
   line) vs. fail-open on any exception (missing rules file, event-logging
   failure).

Follows tests/api/test_worker.py's fixture/mocking conventions (mock_llm_client,
mock_llm_response, AGENTS_DIR patched to redirect into tmp_path).
"""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest
import yaml

from api.models.events import EventType
from api.services.worker import JobWorker

# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------


@pytest.fixture
def mock_llm_client():
    """Create a mock LLM client. Mirrors tests/api/test_worker.py's fixture --
    `config["routing"]` deliberately has no `style_engine` key, which is the
    kill-switch default state."""
    client = MagicMock()
    client.config = {
        "routing": {
            "long_form_threshold_minutes": 15,
        }
    }
    client.get_backend_for_phase.return_value = "openrouter-cheapskate"
    return client


@pytest.fixture
def mock_llm_response():
    """Create a mock LLM response."""
    response = MagicMock()
    response.content = "Test output content"
    response.cost = 0.001
    response.total_tokens = 500
    response.model = "test-model"
    return response


def _style_engine_cfg(rules_file, phases=None, enabled=True, keep_raw_on_fix=True):
    return {
        "enabled": enabled,
        "rules_file": str(rules_file),
        "keep_raw_on_fix": keep_raw_on_fix,
        "phases": phases or {},
    }


def _write_rules(tmp_path, title_max=80, short_max=90, long_max=350):
    """Minimal house-style YAML covering both pre-stage and post-stage needs.
    Mirrors the synthetic StyleRules built inline in tests/test_style_stages.py."""
    raw = {
        "meta": {"version": 1},
        "voice": {
            "forbidden_phrases": [
                {"match": "discover", "category": "viewer_directive", "severity": "error"},
            ],
            "first_person_markers": [r"\bwe\b", r"\bour\b"],
            "second_person_markers": [r"\byou\b"],
        },
        "casing": {
            "style": "down",
            "proper_nouns": ["Wisconsin", "Governor", "Madison"],
            "acronyms": ["PBS"],
            "casing_variants": {},
            "surname_stoplist": [],
        },
        "limits": {
            "fields": {
                "title": {"max": title_max},
                "short_description": {"max": short_max},
                "long_description": {"max": long_max},
            },
            "content_type_overrides": {},
        },
        "programs": {},
    }
    path = tmp_path / "house_style.yaml"
    path.write_text(yaml.safe_dump(raw))
    return path


def _seo_report(
    title: str,
    short_description: str = "A short description of the episode.",
    long_description: str = "A longer description of the episode content, spanning more detail than the short one.",
) -> str:
    return (
        "# SEO Report\n\n"
        "### Title (Final Recommendation)\n\n"
        "**Recommended:**\n"
        f"{title}\n\n"
        "**Character Count:** 0\n\n"
        "---\n\n"
        "### Short Description (150 chars max)\n\n"
        "**Recommended:**\n"
        f"{short_description}\n\n"
        "---\n\n"
        "### Long Description (300 chars max)\n\n"
        "**Recommended:**\n"
        f"{long_description}\n\n"
        "---\n"
    )


ANALYST_TABLE = """<!-- Provenance: Generated by cardigan-v4 analyst phase -->

## Speakers & Roles

| Speaker | Role/Title | Topic | Time |
|---|---|---|---|
| Nick Hoffman | Host | Budget debate | 1:20 |
"""


# ---------------------------------------------------------------------------
# 1. Kill switch: all-off -- byte-for-byte today's behavior
# ---------------------------------------------------------------------------


class TestKillSwitch:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_no_style_engine_block_is_pure_passthrough(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """No `routing.style_engine` key at all -- _run_phase must behave exactly
        as it did before this task: no style_pre, no style_checks, output is the
        raw LLM content, and the persisted file has no style-engine provenance
        line."""
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Test transcript"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["success"] is True
        assert result["output"] == "Test output content"
        assert "style_pre" not in context
        assert "style_checks" not in context

        expected_header = "<!-- model: test-model | cost: $0.0010 | tokens: 500 -->\n"
        assert (tmp_path / "seo_output.md").read_text() == expected_header + "Test output content"

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_enabled_false_is_pure_passthrough(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """style_engine block present but enabled: false -- same kill-switch
        guarantee as a missing block."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path,
                    phases={"seo": {"pre": True, "post": "enforce"}},
                    enabled=False,
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Test transcript", "analyst_output": ANALYST_TABLE}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["output"] == "Test output content"
        assert "style_pre" not in context
        assert "style_checks" not in context
        assert not (tmp_path / "seo_output.raw.md").exists()

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_phase_mode_off_is_pure_passthrough(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """style_engine enabled globally but this phase's pre/post are off --
        no injection, no post-processing."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": False, "post": "off"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Test transcript", "analyst_output": ANALYST_TABLE}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["output"] == "Test output content"
        assert "style_pre" not in context
        assert "style_checks" not in context


# ---------------------------------------------------------------------------
# 2. Pre-generation hook
# ---------------------------------------------------------------------------


class TestPreHook:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_pre_enabled_injects_style_section_into_prompt(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": True, "post": "off"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Nick Hoffman opens the show.", "analyst_output": ANALYST_TABLE}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["success"] is True
        assert "style_pre" in context
        assert context["style_pre"]["prompt_section"].startswith("## Style Rules (authoritative)")

        sent_messages = mock_llm_client.chat.call_args.kwargs["messages"]
        user_message = sent_messages[1]["content"]
        assert "## Style Rules (authoritative)" in user_message
        assert "Nick Hoffman" in user_message

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_pre_disabled_omits_style_section(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": False, "post": "off"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Nick Hoffman opens the show.", "analyst_output": ANALYST_TABLE}

        await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert "style_pre" not in context
        sent_messages = mock_llm_client.chat.call_args.kwargs["messages"]
        user_message = sent_messages[1]["content"]
        assert "## Style Rules (authoritative)" not in user_message

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_stale_style_pre_popped_when_pre_disabled(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """A `style_pre` left in context by a previous phase must never leak
        into a phase whose pre-hook is off."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": False, "post": "off"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {
            "transcript": "Nick Hoffman opens the show.",
            "style_pre": {"prompt_section": "## Style Rules (authoritative)\nSTALE FROM PREVIOUS PHASE\n"},
        }

        await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert "style_pre" not in context
        sent_messages = mock_llm_client.chat.call_args.kwargs["messages"]
        user_message = sent_messages[1]["content"]
        assert "STALE FROM PREVIOUS PHASE" not in user_message


# ---------------------------------------------------------------------------
# 3. Post-generation hook: shadow vs enforce
# ---------------------------------------------------------------------------


class TestPostHookShadow:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_shadow_records_but_never_mutates(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": False, "post": "shadow"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_output = _seo_report("Discover Wisconsin's Budget Story")
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)

        logged_events = []

        async def _capture(event):
            logged_events.append(event)

        mock_log_event.side_effect = _capture
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        # Result output and persisted file are the RAW response content.
        assert result["success"] is True
        assert result["output"] == raw_output
        persisted = (tmp_path / "seo_output.md").read_text()
        assert persisted.endswith(raw_output)
        assert "style-engine:" not in persisted
        assert not (tmp_path / "seo_output.raw.md").exists()

        # But context + events record the check.
        assert "style_checks" in context
        violations = context["style_checks"]["seo"]["violations"]
        assert len(violations) >= 1

        style_violation_events = [e for e in logged_events if e.event_type == EventType.style_violation]
        assert len(style_violation_events) == len(violations)
        assert style_violation_events[0].data.phase == "seo"
        assert style_violation_events[0].data.extra["mode"] == "shadow"
        assert style_violation_events[0].data.extra["action"] == "shadow"


class TestPostHookEnforce:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_enforce_normalizes_and_writes_raw_archive(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": False, "post": "enforce"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_title = "Wisconsin Governor Signs New Budget Bill In Madison"
        raw_output = _seo_report(raw_title)
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        expected_title = "Wisconsin Governor signs new budget bill in Madison"
        assert result["success"] is True
        assert expected_title in result["output"]
        assert raw_title not in result["output"]

        persisted = (tmp_path / "seo_output.md").read_text()
        assert "<!-- style-engine: fixes: 1 | flags: 0 -->" in persisted
        assert expected_title in persisted

        raw_archive = tmp_path / "seo_output.raw.md"
        assert raw_archive.exists()
        assert raw_archive.read_text() == raw_output

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_enforce_keep_raw_on_fix_false_skips_archive(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path,
                    phases={"seo": {"pre": False, "post": "enforce"}},
                    keep_raw_on_fix=False,
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_title = "Wisconsin Governor Signs New Budget Bill In Madison"
        raw_output = _seo_report(raw_title)
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["success"] is True
        assert not (tmp_path / "seo_output.raw.md").exists()


# ---------------------------------------------------------------------------
# 4. Fail-open guarantees
# ---------------------------------------------------------------------------


class TestFailOpen:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_post_fails_open_on_missing_rules_file(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    tmp_path / "does_not_exist.yaml",
                    phases={"seo": {"pre": False, "post": "enforce"}},
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["success"] is True
        assert result["output"] == "Test output content"
        assert (tmp_path / "seo_output.md").read_text().endswith("Test output content")
        assert not (tmp_path / "seo_output.raw.md").exists()

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_pre_fails_open_on_missing_rules_file(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    tmp_path / "does_not_exist.yaml",
                    phases={"seo": {"pre": True, "post": "off"}},
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["success"] is True
        assert "style_pre" not in context

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    @patch("api.services.style_engine.run_post_stage")
    async def test_post_fails_open_when_log_event_raises(
        self, mock_run_post_stage, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """A style_violation log_event() failure must not fail the phase or
        leak a partially-applied normalization -- the raw content flows.

        Extended test: when log_event raises on a LATER violation (not the first),
        the style_checks[phase] entry must be cleaned up so the QA gate doesn't
        treat an incomplete event trail as a completed check."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path, phases={"seo": {"pre": False, "post": "shadow"}}
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_output = _seo_report(
            title="Discover Wisconsin Governor Signs New Budget Bill In Madison",
            short_description="Wisconsin Governor DISCOVERS the budget impact.",
            long_description="A longer description about what the Governor Discovered regarding the budget situation."
        )
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)

        # Mock post object with MULTIPLE violations to trigger loop iterations
        from api.services.style_engine.types import RuleViolation
        mock_post = MagicMock()
        mock_post.normalized_output = raw_output
        mock_post.changed = False

        # Create 2 violations to ensure loop iterates more than once
        violations = [
            RuleViolation(
                rule_id="voice.forbidden.viewer_directive",
                phase="seo",
                severity="error",
                message='Forbidden phrase "Discover"',
                field="title",
                span=[0, 8],
                model_fixable=True,
            ),
            RuleViolation(
                rule_id="casing.mismatch",
                phase="seo",
                severity="warning",
                message="Unexpected casing in field",
                field="short_description",
                span=[10, 20],
                model_fixable=True,
            ),
        ]
        mock_check = MagicMock()
        mock_check.violations = violations
        mock_check.to_dict.return_value = {"violations": [v.to_dict() for v in violations]}
        mock_post.check = mock_check
        mock_run_post_stage.return_value = mock_post

        call_count = [0]
        async def _flaky_log_event(event):
            """Log first violation successfully, raise on the second."""
            if event.event_type == EventType.style_violation:
                call_count[0] += 1
                if call_count[0] > 1:
                    raise RuntimeError("boom on second violation")
            return None

        mock_log_event.side_effect = _flaky_log_event
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(
            job_id=1, phase_name="seo", context=context, project_path=tmp_path
        )

        assert result["success"] is True
        assert result["output"] == raw_output
        assert not (tmp_path / "seo_output.raw.md").exists()

        # NEW ASSERTION: style_checks[seo] must NOT exist on fail-open path
        # (even though violations were found, the exception mid-loop leaves it partial)
        assert "seo" not in context.get("style_checks", {}), (
            "style_checks[seo] should be cleaned up on fail-open, "
            "but survived with partial state"
        )
