"""Tests for the worker's style-engine pre/post hooks (routing.style_engine).

Wires the pure `run_pre_stage`/`run_post_stage` pipeline stages
(api/services/style_engine/{pre_stage,post_stage}.py) into `JobWorker._run_phase`
behind default-off `routing.style_engine` config flags. Covers:

1. Kill switch -- missing config block, `enabled: false`, or phase mode "off"
   must produce byte-for-byte today's behavior (proven separately by the
   unmodified tests/api/test_worker.py suite staying green; also asserted
   directly here for the persisted-file format).
2. Pre-generation hook -- prompt-section injection into the built user
   prompt, and the stale-state guard that pops any leftover `style_pre` from
   a previous phase.
3. Post-generation hook -- shadow mode (record-only, raw content flows) vs.
   enforce mode (normalized content persists, `.raw.md` archive, provenance
   line) vs. fail-open on any exception (missing rules file, event-logging
   failure).

Follows tests/api/test_worker.py's fixture/mocking conventions (mock_llm_client,
mock_llm_response, AGENTS_DIR patched to redirect into tmp_path).
"""

import json
from types import SimpleNamespace
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
import yaml

from api.models.events import EventType
from api.services import worker as worker_mod
from api.services.chunking import TranscriptChunk
from api.services.escalation import classify_qa_failure
from api.services.worker import JobWorker

# ---------------------------------------------------------------------------
# Fixtures / helpers
# ---------------------------------------------------------------------------


@pytest.fixture
def mock_llm_client():
    """Create a mock LLM client. Mirrors tests/api/test_worker.py's fixture --
    `config["routing"]` deliberately has no `style_engine` key, which is the
    kill-switch default state."""
    client = MagicMock()
    client.config = {
        "routing": {
            "long_form_threshold_minutes": 15,
        }
    }
    client.get_backend_for_phase.return_value = "openrouter-cheapskate"
    return client


@pytest.fixture
def mock_llm_response():
    """Create a mock LLM response."""
    response = MagicMock()
    response.content = "Test output content"
    response.cost = 0.001
    response.total_tokens = 500
    response.model = "test-model"
    return response


def _style_engine_cfg(rules_file, phases=None, enabled=True, keep_raw_on_fix=True, qa_gate=None):
    cfg = {
        "enabled": enabled,
        "rules_file": str(rules_file),
        "keep_raw_on_fix": keep_raw_on_fix,
        "phases": phases or {},
    }
    if qa_gate is not None:
        cfg["qa_gate"] = qa_gate
    return cfg


def _write_rules(tmp_path, title_max=80, short_max=90, long_max=350):
    """Minimal house-style YAML covering both pre-stage and post-stage needs.
    Mirrors the synthetic StyleRules built inline in tests/test_style_stages.py."""
    raw = {
        "meta": {"version": 1},
        "voice": {
            "forbidden_phrases": [
                {"match": "discover", "category": "viewer_directive", "severity": "error"},
            ],
            "first_person_markers": [r"\bwe\b", r"\bour\b"],
            "second_person_markers": [r"\byou\b"],
        },
        "casing": {
            "style": "down",
            "proper_nouns": ["Wisconsin", "Governor", "Madison"],
            "acronyms": ["PBS"],
            "casing_variants": {},
            "surname_stoplist": [],
        },
        "limits": {
            "fields": {
                "title": {"max": title_max},
                "short_description": {"max": short_max},
                "long_description": {"max": long_max},
            },
            "content_type_overrides": {},
        },
        "programs": {},
    }
    path = tmp_path / "house_style.yaml"
    path.write_text(yaml.safe_dump(raw))
    return path


def _seo_report(
    title: str,
    short_description: str = "A short description of the episode.",
    long_description: str = "A longer description of the episode content, spanning more detail than the short one.",
) -> str:
    return (
        "# SEO Report\n\n"
        "### Title (Final Recommendation)\n\n"
        "**Recommended:**\n"
        f"{title}\n\n"
        "**Character Count:** 0\n\n"
        "---\n\n"
        "### Short Description (150 chars max)\n\n"
        "**Recommended:**\n"
        f"{short_description}\n\n"
        "---\n\n"
        "### Long Description (300 chars max)\n\n"
        "**Recommended:**\n"
        f"{long_description}\n\n"
        "---\n"
    )


ANALYST_TABLE = """<!-- Provenance: Generated by cardigan-v4 analyst phase -->

## Speakers & Roles

| Speaker | Role/Title | Topic | Time |
|---|---|---|---|
| Nick Hoffman | Host | Budget debate | 1:20 |
"""


# ---------------------------------------------------------------------------
# Formatter-phase rules fixture (chunked formatter tests, task 3b) --
# `_write_rules` above only covers voice/casing/limits (seo-phase needs);
# the formatter phase's pre/post stages read `phases.formatter.*` instead.
# Mirrors tests/test_style_stages.py's `_formatter_rules` fixture.
# ---------------------------------------------------------------------------

_FORMATTER_SUBSTITUTIONS = [
    {"find": r"\b[Oo]kay\b", "replace": "OK", "tier": "enforce"},
    {"find": r"\bSenator\b", "replace": "Sen.", "tier": "enforce"},
    {"find": r"\bLiberals\b", "replace": "liberals", "tier": "enforce", "note": "sentence-initial guard applies"},
    {
        "id": "de_italicize_program_names",
        "find": r"\*(Wisconsin Life|Here & Now)\*",
        "replace": r"\1",
        "tier": "enforce",
    },
    {"id": "oxford_comma", "detect": r",\s+and\b", "tier": "flag", "severity": "warning"},
    {"id": "capitol_capital", "detect": r"\bcapital\b", "tier": "flag", "severity": "warning"},
]

_FORMATTER_SPEAKER_LABEL_SPEC = {
    "pattern": r"^\*\*[A-Z][\w.'-]+(?: [A-Z][\w.'-]+)+:\*\*",
    "trailing_spaces": 2,
    "blank_lines_between_turns": 1,
    "no_honorifics": True,
}


def _write_formatter_rules(tmp_path, substitutions=None, speaker_label=None, review_notes=None):
    """YAML house-style file covering `phases.formatter` (substitutions,
    speaker_label, review_notes) -- what the formatter phase's pre/post
    stages actually read."""
    raw = {
        "meta": {"version": 1},
        "phases": {
            "formatter": {
                "substitutions": _FORMATTER_SUBSTITUTIONS if substitutions is None else substitutions,
                "speaker_label": _FORMATTER_SPEAKER_LABEL_SPEC if speaker_label is None else speaker_label,
                "review_notes": (
                    {"placement": "top", "format": "html_comment", "tier": "flag"}
                    if review_notes is None
                    else review_notes
                ),
            }
        },
        "casing": {"surname_stoplist": []},
    }
    path = tmp_path / "formatter_house_style.yaml"
    path.write_text(yaml.safe_dump(raw))
    return path


def _write_timestamp_rules(tmp_path, chapter_max_by_duration=None, first_chapter_title="Episode intro"):
    """YAML house-style file covering `phases.timestamp` -- what the
    timestamp phase's post-stage reads (chapter_max_by_duration,
    first_chapter, chapter_name, formats, constraints). Mirrors
    tests/test_style_stages.py's `_timestamp_rules` fixture."""
    raw = {
        "meta": {"version": 1},
        "voice": {
            "forbidden_phrases": [],
            "first_person_markers": [],
            "second_person_markers": [],
        },
        "casing": {
            "style": "down",
            "proper_nouns": ["Wisconsin"],
            "acronyms": [],
            "casing_variants": {},
            "surname_stoplist": [],
        },
        "phases": {
            "timestamp": {
                "chapter_max_by_duration": (
                    [
                        {"lt": 5, "max": 3},
                        {"lt": 15, "max": 5},
                        {"lt": 30, "max": 7},
                        {"lt": 60, "max": 8},
                        {"lt": None, "max": 10},
                    ]
                    if chapter_max_by_duration is None
                    else chapter_max_by_duration
                ),
                "first_chapter": {"time": "0:00", "title": first_chapter_title, "tier": "enforce"},
                "chapter_name": {"case": "sentence", "words": {"min": 2, "max": 6}, "tier": "flag"},
                "formats": {
                    "media_manager": {"start": "H:MM:SS.000", "end": "H:MM:SS.999", "tier": "enforce"},
                    "youtube": {"style": "M:SS", "tier": "enforce"},
                },
                "constraints": {"no_gaps": True, "chronological": True, "final_end_equals_srt_end": True},
            }
        },
    }
    path = tmp_path / "timestamp_house_style.yaml"
    path.write_text(yaml.safe_dump(raw))
    return path


def _bare_chunked_worker(style_engine_cfg: dict | None = None) -> JobWorker:
    """A JobWorker with only `llm.config.routing.style_engine` stubbed and
    prompt loading bypassed -- enough to drive `_run_formatter_chunked`
    directly without the DB/queue machinery. Mirrors
    tests/test_model_selection_integrity.py's conventions for this method."""
    worker = JobWorker.__new__(JobWorker)
    worker.llm = MagicMock()
    worker.llm.get_backend_for_phase = MagicMock(return_value="openrouter")
    worker.llm.get_backend_config = MagicMock(return_value={"timeout": 120})
    worker.llm.config = {"routing": {"style_engine": style_engine_cfg or {}}}
    worker._load_agent_prompt = lambda phase: "system"
    return worker


# ---------------------------------------------------------------------------
# 1. Kill switch: all-off -- byte-for-byte today's behavior
# ---------------------------------------------------------------------------


class TestKillSwitch:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_no_style_engine_block_is_pure_passthrough(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """No `routing.style_engine` key at all -- _run_phase must behave exactly
        as it did before this task: no style_pre, no style_checks, output is the
        raw LLM content, and the persisted file has no style-engine provenance
        line."""
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Test transcript"}

        result = await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert result["success"] is True
        assert result["output"] == "Test output content"
        assert "style_pre" not in context
        assert "style_checks" not in context

        expected_header = "<!-- model: test-model | cost: $0.0010 | tokens: 500 -->\n"
        assert (tmp_path / "seo_output.md").read_text() == expected_header + "Test output content"

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_enabled_false_is_pure_passthrough(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """style_engine block present but enabled: false -- same kill-switch
        guarantee as a missing block."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path,
                    phases={"seo": {"pre": True, "post": "enforce"}},
                    enabled=False,
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Test transcript", "analyst_output": ANALYST_TABLE}

        result = await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert result["output"] == "Test output content"
        assert "style_pre" not in context
        assert "style_checks" not in context
        assert not (tmp_path / "seo_output.raw.md").exists()

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_phase_mode_off_is_pure_passthrough(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """style_engine enabled globally but this phase's pre/post are off --
        no injection, no post-processing."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(rules_path, phases={"seo": {"pre": False, "post": "off"}}),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Test transcript", "analyst_output": ANALYST_TABLE}

        result = await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert result["output"] == "Test output content"
        assert "style_pre" not in context
        assert "style_checks" not in context


# ---------------------------------------------------------------------------
# 2. Pre-generation hook
# ---------------------------------------------------------------------------


class TestPreHook:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_pre_enabled_injects_style_section_into_prompt(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(rules_path, phases={"seo": {"pre": True, "post": "off"}}),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Nick Hoffman opens the show.", "analyst_output": ANALYST_TABLE}

        result = await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert result["success"] is True
        assert "style_pre" in context
        assert context["style_pre"]["prompt_section"].startswith("## Style Rules (authoritative)")

        sent_messages = mock_llm_client.chat.call_args.kwargs["messages"]
        user_message = sent_messages[1]["content"]
        assert "## Style Rules (authoritative)" in user_message
        assert "Nick Hoffman" in user_message

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_pre_disabled_omits_style_section(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(rules_path, phases={"seo": {"pre": False, "post": "off"}}),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "Nick Hoffman opens the show.", "analyst_output": ANALYST_TABLE}

        await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert "style_pre" not in context
        sent_messages = mock_llm_client.chat.call_args.kwargs["messages"]
        user_message = sent_messages[1]["content"]
        assert "## Style Rules (authoritative)" not in user_message

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_stale_style_pre_popped_when_pre_disabled(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """A `style_pre` left in context by a previous phase must never leak
        into a phase whose pre-hook is off."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(rules_path, phases={"seo": {"pre": False, "post": "off"}}),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {
            "transcript": "Nick Hoffman opens the show.",
            "style_pre": {"prompt_section": "## Style Rules (authoritative)\nSTALE FROM PREVIOUS PHASE\n"},
        }

        await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert "style_pre" not in context
        sent_messages = mock_llm_client.chat.call_args.kwargs["messages"]
        user_message = sent_messages[1]["content"]
        assert "STALE FROM PREVIOUS PHASE" not in user_message


# ---------------------------------------------------------------------------
# 3. Post-generation hook: shadow vs enforce
# ---------------------------------------------------------------------------


class TestPostHookShadow:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_shadow_records_but_never_mutates(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(rules_path, phases={"seo": {"pre": False, "post": "shadow"}}),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_output = _seo_report("Discover Wisconsin's Budget Story")
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)

        logged_events = []

        async def _capture(event):
            logged_events.append(event)

        mock_log_event.side_effect = _capture
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        # Result output and persisted file are the RAW response content.
        assert result["success"] is True
        assert result["output"] == raw_output
        persisted = (tmp_path / "seo_output.md").read_text()
        assert persisted.endswith(raw_output)
        assert "style-engine:" not in persisted
        assert not (tmp_path / "seo_output.raw.md").exists()

        # Events record the check, but context["style_checks"] must NOT be
        # populated in shadow mode (PR #295 review #4): that key flips on the
        # validator pre-stage's "deterministic checks already performed" prompt
        # section, a downstream change shadow mode is contractually forbidden
        # from making. The style_violation events are shadow's record of truth.
        assert "style_checks" not in context

        style_violation_events = [e for e in logged_events if e.event_type == EventType.style_violation]
        assert len(style_violation_events) >= 1
        assert style_violation_events[0].data.phase == "seo"
        assert style_violation_events[0].data.extra["mode"] == "shadow"
        assert style_violation_events[0].data.extra["action"] == "shadow"


class TestPostHookEnforce:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_enforce_normalizes_and_writes_raw_archive(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(rules_path, phases={"seo": {"pre": False, "post": "enforce"}}),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_title = "Wisconsin Governor Signs New Budget Bill In Madison"
        raw_output = _seo_report(raw_title)
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        expected_title = "Wisconsin Governor signs new budget bill in Madison"
        assert result["success"] is True
        assert expected_title in result["output"]
        assert raw_title not in result["output"]

        persisted = (tmp_path / "seo_output.md").read_text()
        assert "<!-- style-engine: fixes: 1 | flags: 0 -->" in persisted
        assert expected_title in persisted

        raw_archive = tmp_path / "seo_output.raw.md"
        assert raw_archive.exists()
        assert raw_archive.read_text() == raw_output

        # Enforce mode DOES record context["style_checks"] -- the validator
        # pre-stage + lint merge legitimately consume it (contrast shadow,
        # which must not; PR #295 review #4).
        assert "seo" in context.get("style_checks", {})

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_enforce_logs_fixed_event_per_applied_fix(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """Task 6b follow-up -- the feedback loop's missing signal:
        enforce-tier AppliedFixes (here, seo's title down-casing) must be
        logged as their own style_violation event with action="fixed", not
        just baked into the persisted `<!-- style-engine: fixes: N -->`
        provenance comment where scripts/style_report.py can't see them."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(rules_path, phases={"seo": {"pre": False, "post": "enforce"}}),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_title = "Wisconsin Governor Signs New Budget Bill In Madison"
        raw_output = _seo_report(raw_title)
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)

        logged_events = []

        async def _capture(event):
            logged_events.append(event)

        mock_log_event.side_effect = _capture
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)
        assert result["success"] is True

        style_violation_events = [e for e in logged_events if e.event_type == EventType.style_violation]
        fixed_events = [e for e in style_violation_events if e.data.extra.get("action") == "fixed"]
        assert len(fixed_events) == 1
        assert fixed_events[0].data.phase == "seo"
        assert fixed_events[0].data.extra["rule_id"] == "casing.down_style.title"
        assert fixed_events[0].data.extra["mode"] == "enforce"
        assert fixed_events[0].data.extra["before"] == raw_title

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_enforce_keep_raw_on_fix_false_skips_archive(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    rules_path,
                    phases={"seo": {"pre": False, "post": "enforce"}},
                    keep_raw_on_fix=False,
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_title = "Wisconsin Governor Signs New Budget Bill In Madison"
        raw_output = _seo_report(raw_title)
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert result["success"] is True
        assert not (tmp_path / "seo_output.raw.md").exists()


# ---------------------------------------------------------------------------
# 4. Fail-open guarantees
# ---------------------------------------------------------------------------


class TestFailOpen:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_post_fails_open_on_missing_rules_file(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    tmp_path / "does_not_exist.yaml",
                    phases={"seo": {"pre": False, "post": "enforce"}},
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert result["success"] is True
        assert result["output"] == "Test output content"
        assert (tmp_path / "seo_output.md").read_text().endswith("Test output content")
        assert not (tmp_path / "seo_output.raw.md").exists()

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_pre_fails_open_on_missing_rules_file(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(
                    tmp_path / "does_not_exist.yaml",
                    phases={"seo": {"pre": True, "post": "off"}},
                ),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert result["success"] is True
        assert "style_pre" not in context

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    @patch("api.services.style_engine.run_post_stage")
    async def test_post_fails_open_when_log_event_raises(
        self,
        mock_run_post_stage,
        mock_agents_dir,
        mock_log_event,
        mock_get_llm,
        mock_llm_client,
        mock_llm_response,
        tmp_path,
    ):
        """A style_violation log_event() failure must not fail the phase or
        leak a partially-applied normalization -- the raw content flows.

        Extended test: when log_event raises on a LATER violation (not the first),
        the style_checks[phase] entry must be cleaned up so the QA gate doesn't
        treat an incomplete event trail as a completed check."""
        rules_path = _write_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(rules_path, phases={"seo": {"pre": False, "post": "shadow"}}),
            }
        }
        mock_get_llm.return_value = mock_llm_client
        raw_output = _seo_report(
            title="Discover Wisconsin Governor Signs New Budget Bill In Madison",
            short_description="Wisconsin Governor DISCOVERS the budget impact.",
            long_description="A longer description about what the Governor Discovered regarding the budget situation.",
        )
        mock_llm_response.content = raw_output
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)

        # Mock post object with MULTIPLE violations to trigger loop iterations
        from api.services.style_engine.types import RuleViolation

        mock_post = MagicMock()
        mock_post.normalized_output = raw_output
        mock_post.changed = False

        # Create 2 violations to ensure loop iterates more than once
        violations = [
            RuleViolation(
                rule_id="voice.forbidden.viewer_directive",
                phase="seo",
                severity="error",
                message='Forbidden phrase "Discover"',
                field="title",
                span=[0, 8],
                model_fixable=True,
            ),
            RuleViolation(
                rule_id="casing.mismatch",
                phase="seo",
                severity="warning",
                message="Unexpected casing in field",
                field="short_description",
                span=[10, 20],
                model_fixable=True,
            ),
        ]
        mock_check = MagicMock()
        mock_check.violations = violations
        mock_check.to_dict.return_value = {"violations": [v.to_dict() for v in violations]}
        mock_post.check = mock_check
        mock_run_post_stage.return_value = mock_post

        call_count = [0]

        async def _flaky_log_event(event):
            """Log first violation successfully, raise on the second."""
            if event.event_type == EventType.style_violation:
                call_count[0] += 1
                if call_count[0] > 1:
                    raise RuntimeError("boom on second violation")
            return None

        mock_log_event.side_effect = _flaky_log_event
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {"transcript": "irrelevant"}

        result = await worker._run_phase(job_id=1, phase_name="seo", context=context, project_path=tmp_path)

        assert result["success"] is True
        assert result["output"] == raw_output
        assert not (tmp_path / "seo_output.raw.md").exists()

        # NEW ASSERTION: style_checks[seo] must NOT exist on fail-open path
        # (even though violations were found, the exception mid-loop leaves it partial)
        assert "seo" not in context.get("style_checks", {}), (
            "style_checks[seo] should be cleaned up on fail-open, " "but survived with partial state"
        )


# ---------------------------------------------------------------------------
# 5. Validator lint + merge hook (_apply_style_lint, task 2b)
#
# Wires `run_lint`/`merge_style_flags` (api/services/style_engine/{lint,
# qa_merge}.py, task 2a) into the worker's validation flow behind
# `routing.style_engine.phases.validator.lint` (off | shadow | enforce).
# ---------------------------------------------------------------------------


def _bare_worker(style_engine_cfg: dict) -> JobWorker:
    """A JobWorker with only `llm.config.routing.style_engine` stubbed --
    enough for `_apply_style_lint` (and, for the wiring test below,
    `_finalize_with_qa_gate`) without touching the DB/queue machinery."""
    worker = JobWorker.__new__(JobWorker)
    worker.llm = MagicMock()
    worker.llm.config = {"routing": {"style_engine": style_engine_cfg}}
    return worker


_CLEAN_FORMATTER_BODY = "**John Smith:**\nDialogue text that is long enough to matter here and ends properly."


def _passing_verdict() -> dict:
    return {
        "overall": "pass",
        "phase_results": {
            "analyst": {"status": "pass", "flags": []},
            "formatter": {"status": "pass", "flags": []},
            "seo": {"status": "pass", "flags": []},
        },
    }


class TestValidatorLintHook:
    @pytest.mark.asyncio
    async def test_lint_off_explicit_is_passthrough(self, tmp_path, monkeypatch):
        """`validator.lint: "off"` -- the explicit off case (kill switch is
        covered generally by test_worker.py staying green; this is the
        lint-specific off assertion)."""
        rules_path = _write_rules(tmp_path)
        cfg = _style_engine_cfg(rules_path, phases={"validator": {"lint": "off"}})
        worker = _bare_worker(cfg)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        context = {
            "analyst_output": ANALYST_TABLE,
            "formatter_output": _CLEAN_FORMATTER_BODY,
            "seo_output": _seo_report("A reasonably short seo title"),
        }
        validation_data = _passing_verdict()

        result = await worker._apply_style_lint(job_id=1, context=context, validation_data=validation_data)

        assert result is validation_data
        assert "lint_checks" not in context

    @pytest.mark.asyncio
    async def test_shadow_records_events_and_lint_checks_without_merging(self, tmp_path, monkeypatch):
        rules_path = _write_rules(tmp_path, title_max=40)
        cfg = _style_engine_cfg(rules_path, phases={"validator": {"lint": "shadow"}})
        worker = _bare_worker(cfg)

        logged_events = []

        async def _capture(event):
            logged_events.append(event)

        monkeypatch.setattr(worker_mod, "log_event", _capture)

        over_limit_title = "This SEO Title Is Deliberately Written To Exceed The Forty Character Limit"
        context = {
            "analyst_output": ANALYST_TABLE,
            "formatter_output": _CLEAN_FORMATTER_BODY,
            "seo_output": _seo_report(over_limit_title),
        }
        validation_data = _passing_verdict()

        result = await worker._apply_style_lint(job_id=1, context=context, validation_data=validation_data)

        # Shadow mode is strictly record-only -- same object, no merge.
        assert result is validation_data

        assert "lint_checks" in context
        seo_violations = context["lint_checks"]["seo"]["violations"]
        assert any(v["rule_id"] == "lint.seo.title_over_limit" for v in seo_violations)

        lint_events = [e for e in logged_events if e.event_type == EventType.style_violation]
        assert lint_events, "expected at least one style_violation event from the lint suite"
        assert all(e.data.extra.get("source") == "lint" for e in lint_events)
        assert all(e.data.extra.get("mode") == "shadow" for e in lint_events)

    @pytest.mark.asyncio
    async def test_enforce_fail_on_error_appends_flag_and_flips_status(self, tmp_path, monkeypatch):
        rules_path = _write_rules(tmp_path, title_max=40)
        cfg = _style_engine_cfg(
            rules_path,
            phases={"validator": {"lint": "enforce"}},
            qa_gate={"merge_flags": True, "fail_on_error": True},
        )
        worker = _bare_worker(cfg)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        over_limit_title = "This SEO Title Is Deliberately Written To Exceed The Forty Character Limit"
        context = {
            "analyst_output": ANALYST_TABLE,
            "formatter_output": _CLEAN_FORMATTER_BODY,
            "seo_output": _seo_report(over_limit_title),
        }
        validation_data = _passing_verdict()

        result = await worker._apply_style_lint(job_id=1, context=context, validation_data=validation_data)

        assert result is not validation_data  # merge returns a fresh dict
        seo_flags = result["phase_results"]["seo"]["flags"]
        assert any(f.startswith("[style:lint.seo.title_over_limit]") for f in seo_flags)
        assert result["phase_results"]["seo"]["status"] == "fail"
        assert result["overall"] == "fail"
        # merge_style_flags never mutates its input.
        assert validation_data["overall"] == "pass"
        assert validation_data["phase_results"]["seo"]["flags"] == []

    @pytest.mark.asyncio
    async def test_enforce_nonfixable_lint_hit_routes_escalation_false(self, tmp_path, monkeypatch):
        """Formatter output missing -> lint.output_missing (model_fixable=False)
        -> merged flag carries the "[style-nonfixable:...]" prefix ->
        classify_qa_failure over the MERGED result returns escalate=False.
        Proves the end-to-end routing the escalation.py change enables."""
        rules_path = _write_rules(tmp_path)
        cfg = _style_engine_cfg(
            rules_path,
            phases={"validator": {"lint": "enforce"}},
            qa_gate={"merge_flags": True, "fail_on_error": True},
        )
        worker = _bare_worker(cfg)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        context = {
            "analyst_output": ANALYST_TABLE,
            # formatter_output intentionally omitted -> lint.output_missing
            "seo_output": _seo_report("A reasonably short seo title"),
        }
        validation_data = _passing_verdict()

        result = await worker._apply_style_lint(job_id=1, context=context, validation_data=validation_data)

        formatter_flags = result["phase_results"]["formatter"]["flags"]
        assert any(f.startswith("[style-nonfixable:lint.output_missing]") for f in formatter_flags)
        assert result["phase_results"]["formatter"]["status"] == "fail"
        assert result["overall"] == "fail"

        classed = classify_qa_failure(result, context)
        assert classed["escalate"] is False
        assert classed["nonfixable"]

    @pytest.mark.asyncio
    async def test_fail_open_on_bogus_rules_file(self, tmp_path, monkeypatch):
        cfg = _style_engine_cfg(
            tmp_path / "does_not_exist.yaml",
            phases={"validator": {"lint": "enforce"}},
            qa_gate={"merge_flags": True, "fail_on_error": True},
        )
        worker = _bare_worker(cfg)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())
        warning_calls = []
        monkeypatch.setattr(worker_mod.logger, "warning", lambda *a, **kw: warning_calls.append((a, kw)))

        context = {
            "analyst_output": ANALYST_TABLE,
            "formatter_output": _CLEAN_FORMATTER_BODY,
            "seo_output": _seo_report("A reasonably short seo title"),
        }
        validation_data = _passing_verdict()

        result = await worker._apply_style_lint(job_id=1, context=context, validation_data=validation_data)

        assert result is validation_data
        assert "lint_checks" not in context
        assert warning_calls, "fail-open must log a warning"

    @pytest.mark.asyncio
    async def test_none_validation_data_enforce_builds_merged_skeleton(self, tmp_path, monkeypatch):
        """Unparseable LLM validator output -> validation_data is None ->
        _apply_style_lint must still merge the lint flags into qa_merge's
        None-skeleton (exercises qa_merge's None path through the worker)."""
        rules_path = _write_rules(tmp_path)
        cfg = _style_engine_cfg(
            rules_path,
            phases={"validator": {"lint": "enforce"}},
            qa_gate={"merge_flags": True, "fail_on_error": True},
        )
        worker = _bare_worker(cfg)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        context: dict = {}  # all 3 canonical phase outputs missing

        result = await worker._apply_style_lint(job_id=1, context=context, validation_data=None)

        assert result["_merged_from_none"] is True
        assert result["overall"] == "fail"
        for phase in ("analyst", "formatter", "seo"):
            flags = result["phase_results"][phase]["flags"]
            assert any(f.startswith("[style-nonfixable:lint.output_missing]") for f in flags)
            assert result["phase_results"][phase]["status"] == "fail"


class TestFinalizeQaGateLintWiring:
    """Proves the SECOND call site (`_finalize_with_qa_gate`'s re-validation
    parse, ~worker.py:1440) routes through `_apply_style_lint` before the
    merged verdict decides completed vs. paused -- not just the main-loop
    parse point covered by TestValidatorLintHook above."""

    @pytest.mark.asyncio
    async def test_revalidation_merges_lint_flags_before_gate_decision(self, tmp_path, monkeypatch):
        rules_path = _write_rules(tmp_path)
        style_cfg = _style_engine_cfg(
            rules_path,
            phases={"validator": {"lint": "enforce"}},
            qa_gate={"merge_flags": True, "fail_on_error": True},
        )

        worker = JobWorker.__new__(JobWorker)
        worker.llm = MagicMock()
        worker.llm.config = {
            "qa_escalation": {
                "on_validation_fail": True,
                "max_auto_escalations": 1,
                "exclude_variants": ["fast", "fable"],
            },
            "routing": {"style_engine": style_cfg},
        }

        monkeypatch.setattr(worker_mod, "get_job", AsyncMock(return_value=None))
        monkeypatch.setattr(
            worker_mod, "resolve_escalated_model", AsyncMock(return_value="anthropic/claude-sonnet-4-6")
        )
        pause = AsyncMock()
        monkeypatch.setattr(worker_mod, "pause_and_suggest", pause)
        update_job_mock = AsyncMock()
        monkeypatch.setattr(worker_mod, "update_job", update_job_mock)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        passing_verdict_json = json.dumps(_passing_verdict())
        escalated_seo_output = (
            "Escalated seo output content that is comfortably longer than the "
            "fifty character substantive-length floor."
        )

        async def fake_run_phase(job_id, phase_name, context, project_path, model_override=None):
            if phase_name == "validator":
                return {"success": True, "output": passing_verdict_json, "model": "validator-model"}
            return {"success": True, "output": escalated_seo_output, "model": "strong-model"}

        monkeypatch.setattr(worker, "_run_phase", fake_run_phase)

        initial_validation_result = {
            "overall": "fail",
            "phase_results": {
                "analyst": {"status": "pass", "flags": []},
                "formatter": {"status": "pass", "flags": []},
                "seo": {"status": "fail", "flags": ["seo title needs shortening"]},
            },
        }
        context = {
            "analyst_output": ANALYST_TABLE,
            "seo_output": "stale pre-escalation seo output",
            # formatter_output intentionally omitted -- lint.output_missing
            # fires during the re-validation's _apply_style_lint call even
            # though the LLM's re-validation JSON claims formatter passed.
        }

        outcome = await worker._finalize_with_qa_gate(
            job_id=99,
            context=context,
            project_path=str(tmp_path),
            validation_result=initial_validation_result,
            phase_order=["analyst", "formatter", "seo", "validator"],
        )

        # Without the merge wired in, the LLM's re-validation JSON says
        # "pass" and the gate would complete. With it wired in, the missing
        # formatter output surfaces a non-fixable flag that flips the
        # persisted verdict to "fail" -- the gate must pause instead.
        assert outcome == "paused"
        pause.assert_awaited_once()

        persisted = [
            c.args[1]
            for c in update_job_mock.await_args_list
            if len(c.args) >= 2 and hasattr(c.args[1], "validation_result")
        ]
        assert persisted, "update_job was never called with a validation_result payload"
        merged = persisted[-1].validation_result
        assert merged["overall"] == "fail"
        formatter_flags = merged["phase_results"]["formatter"]["flags"]
        assert any(f.startswith("[style-nonfixable:lint.output_missing]") for f in formatter_flags)


class TestRetryRevalidationLintMerge:
    """Proves the THIRD call site (`retry_single_phase`'s post-retry re-validation
    parse, ~worker.py:564) routes through `_apply_style_lint` before persisting --
    not just the main-loop parse (TestValidatorLintHook) and QA-gate parse
    (TestFinalizeQaGateLintWiring) covered above."""

    @pytest.mark.asyncio
    async def test_retry_phase_merges_lint_flags_on_revalidation(self, tmp_path, monkeypatch):
        """After retrying a phase (e.g., seo), the re-run of the validator must
        merge lint flags before persisting the validation_result, so a manually
        retried job with validator.lint="enforce" does NOT bypass QA flags.

        This test proves the third validation-persist path routes through
        _apply_style_lint by verifying the hook is called with the parsed
        validator verdict and context, and the merged result is persisted."""
        rules_path = _write_rules(tmp_path, title_max=40)
        style_cfg = _style_engine_cfg(
            rules_path,
            phases={"validator": {"lint": "enforce"}},
            qa_gate={"merge_flags": True, "fail_on_error": True},
        )

        worker = JobWorker.__new__(JobWorker)
        worker.llm = MagicMock()
        worker.llm.config = {
            "routing": {"style_engine": style_cfg},
        }

        # Mock job with minimal fields needed for retry_single_phase
        existing_job = MagicMock()
        existing_job.model_dump.return_value = {
            "id": 42,
            "project_name": "Test Project",
            "transcript_file": "test.txt",
            "project_path": str(tmp_path),
            "word_count": 100,
            "duration_minutes": 5,
            "status": "completed",
            "phases": [
                {
                    "name": "seo",
                    "status": "completed",
                    "cost": 0.001,
                    "tokens": 100,
                    "input_tokens": 50,
                    "output_tokens": 50,
                    "model": "test-model",
                    "completed_at": "2024-01-01T00:00:00Z",
                    "retry_count": 0,
                }
            ],
        }
        existing_job.phases = existing_job.model_dump()["phases"]

        # Mock database operations - patch at the database module level since retry_single_phase imports locally
        from api.services import database as db_mod

        monkeypatch.setattr(db_mod, "get_job", AsyncMock(side_effect=[existing_job, existing_job, existing_job]))
        update_job_mock = AsyncMock()
        monkeypatch.setattr(db_mod, "update_job", update_job_mock)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        # Capture calls to _apply_style_lint to prove it's wired in
        original_apply_style_lint = worker._apply_style_lint
        apply_style_lint_calls = []

        async def mock_apply_style_lint(job_id, context, validation_data):
            apply_style_lint_calls.append({"job_id": job_id, "context": context, "validation_data": validation_data})
            # Call the real method to get actual merged result
            return await original_apply_style_lint(job_id, context, validation_data)

        monkeypatch.setattr(worker, "_apply_style_lint", mock_apply_style_lint)

        # Mock _run_phase to return retried phase output and passing validator JSON
        passing_verdict_json = json.dumps(_passing_verdict())

        async def fake_run_phase(job_id, phase_name, context, project_path, model_override=None):
            if phase_name == "validator":
                return {"success": True, "output": passing_verdict_json, "model": "validator-model"}
            else:
                return {"success": True, "output": "Retried phase output", "model": "test-model"}

        monkeypatch.setattr(worker, "_run_phase", fake_run_phase)

        # Write transcript file for load
        (tmp_path / "test.txt").write_text("Test transcript content")

        result = await worker.retry_single_phase(
            job_id=42,
            phase_name="seo",
            feedback="Tighten the title",
        )

        # Verify retry succeeded
        assert result["success"] is True

        # Prove _apply_style_lint was called during the retry's re-validation phase
        assert apply_style_lint_calls, "expected _apply_style_lint to be called during retry re-validation"
        call = apply_style_lint_calls[0]
        assert call["job_id"] == 42
        assert call["validation_data"]["overall"] == "pass"  # input is passing verdict

        # Verify the persisted validation_result is the merged one from _apply_style_lint
        persisted_validations = [
            c.args[1]
            for c in update_job_mock.await_args_list
            if len(c.args) >= 2 and hasattr(c.args[1], "validation_result") and c.args[1].validation_result
        ]
        assert persisted_validations, "update_job was never called with validation_result"

        # The last call should have the merged result
        final_validation = persisted_validations[-1].validation_result
        assert final_validation is not None


# ---------------------------------------------------------------------------
# 6. Chunked formatter path (task 3b)
#
# The unchunked formatter (and every other phase) gets style_pre/style_post
# for free from the generic hooks covered above. The chunked path
# (`_run_formatter_chunked`, entered from `_run_phase`'s chunking branch)
# builds its own per-chunk messages and has its own merge+persist site, so
# it needs its own wiring:
#   - every chunk's prompt carries `context["style_pre"]["prompt_section"]`
#     (set by `_run_phase`'s pre-hook, which runs BEFORE the chunking branch
#     -- see `_run_phase` around the `context.pop("style_pre", None)` reset,
#     followed later by the `if phase_name == "formatter": ... return await
#     self._run_formatter_chunked(...)` branch -- so `style_pre` is already
#     in `context` by the time any chunk request is built)
#   - `_apply_style_post` runs ONCE on `merge_formatter_chunks(...)`'s
#     output, never per-chunk
# ---------------------------------------------------------------------------


class TestChunkedFormatterStylePre:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    @patch("api.services.chunking.split_transcript")
    async def test_pre_enabled_injects_style_section_into_every_chunk_prompt(
        self, mock_split_transcript, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, tmp_path
    ):
        """End-to-end through `_run_phase` (not a direct `_run_formatter_chunked`
        call) so this also proves the pre-hook-before-chunking-branch ordering,
        not just that the chunked path CAN carry a style section if handed one."""
        rules_path = _write_formatter_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(rules_path, phases={"formatter": {"pre": True, "post": "off"}}),
                "chunking": {"enabled": True},
            }
        }
        mock_get_llm.return_value = mock_llm_client
        mock_split_transcript.return_value = [
            TranscriptChunk(
                index=0,
                content="chunk zero dialogue",
                start_timecode="0",
                end_timecode="1",
                word_count=3,
                overlap_prefix="",
            ),
            TranscriptChunk(
                index=1,
                content="chunk one dialogue",
                start_timecode="1",
                end_timecode="2",
                word_count=3,
                overlap_prefix="chunk zero dialogue",
            ),
        ]

        captured_user_messages = []

        async def fake_chat(**kwargs):
            captured_user_messages.append(next(m["content"] for m in kwargs["messages"] if m["role"] == "user"))
            return SimpleNamespace(
                content="formatted chunk",
                cost=0.001,
                total_tokens=10,
                input_tokens=5,
                output_tokens=5,
                model="test-model",
            )

        mock_llm_client.chat = fake_chat
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {
            "transcript": "irrelevant -- split_transcript is mocked",
            "transcript_file": "test.txt",
            "analyst_output": ANALYST_TABLE,
        }

        result = await worker._run_phase(job_id=1, phase_name="formatter", context=context, project_path=tmp_path)

        assert result["success"] is True
        assert len(captured_user_messages) == 2, "both chunks must have called the LLM"
        for user_message in captured_user_messages:
            assert "## Style Rules (authoritative)" in user_message


class TestChunkedFormatterStylePost:
    @pytest.mark.asyncio
    async def test_enforce_normalizes_merged_output_and_writes_raw_archive(self, tmp_path, monkeypatch):
        rules_path = _write_formatter_rules(tmp_path)
        cfg = _style_engine_cfg(rules_path, phases={"formatter": {"pre": False, "post": "enforce"}})
        worker = _bare_chunked_worker(cfg)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        # Chunk 0's speaker label already matches the spec (2 trailing spaces);
        # chunk 1's is mis-spaced (5) -- normalize_speaker_turns must fix it.
        # "Senator"/"okay" are enforce-tier substitutions.
        chunk_outputs = {
            0: "**Nick Hoffman:**  \nSenator Smith says that's okay with the budget.",
            1: "**Angela Fitzgerald:**     \nThat's right, we'll see.",
        }

        async def fake_chat(**kwargs):
            user_message = next(m["content"] for m in kwargs["messages"] if m["role"] == "user")
            idx = 1 if "Continue formatting from where the previous" in user_message else 0
            return SimpleNamespace(
                content=chunk_outputs[idx],
                cost=0.01,
                total_tokens=10,
                input_tokens=6,
                output_tokens=4,
                model="m",
            )

        worker.llm.chat = fake_chat

        chunks = [
            TranscriptChunk(
                index=0, content="opening", start_timecode="0", end_timecode="1", word_count=1, overlap_prefix=""
            ),
            TranscriptChunk(
                index=1, content="closing", start_timecode="1", end_timecode="2", word_count=1, overlap_prefix="opening"
            ),
        ]
        context = {"analyst_output": ""}

        result = await worker._run_formatter_chunked(
            job_id=1,
            chunks=chunks,
            context=context,
            project_path=tmp_path,
            chunking_config={"max_parallel": 2},
        )

        assert result["success"] is True
        assert "OK with the budget" in result["output"]
        assert "okay" not in result["output"]
        assert "Sen. Smith" in result["output"]

        persisted = (tmp_path / "formatter_output.md").read_text()
        assert "<!-- style-engine: fixes: 2 | flags: 0 -->" in persisted
        assert "OK with the budget" in persisted
        # Trailing-space normalization landed in the persisted, merged doc.
        assert "**Angela Fitzgerald:**  \n" in persisted
        assert "**Angela Fitzgerald:**     \n" not in persisted

        raw_archive = tmp_path / "formatter_output.raw.md"
        assert raw_archive.exists()
        assert "okay" in raw_archive.read_text()

    @pytest.mark.asyncio
    async def test_shadow_records_but_never_mutates_merged_output(self, tmp_path, monkeypatch):
        rules_path = _write_formatter_rules(tmp_path)
        cfg = _style_engine_cfg(rules_path, phases={"formatter": {"pre": False, "post": "shadow"}})
        worker = _bare_chunked_worker(cfg)

        logged_events = []

        async def _capture(event):
            logged_events.append(event)

        monkeypatch.setattr(worker_mod, "log_event", _capture)

        # Flag-tier-only content (no enforce-tier substitutions) so shadow's
        # "raw content flows unchanged" guarantee is unambiguous.
        chunk_outputs = {
            0: "**Nick Hoffman:**  \nWe discussed red, white, and blue today.",
            1: "**Angela Fitzgerald:**  \nThe capital was raised for the fund.",
        }

        async def fake_chat(**kwargs):
            user_message = next(m["content"] for m in kwargs["messages"] if m["role"] == "user")
            idx = 1 if "Continue formatting from where the previous" in user_message else 0
            return SimpleNamespace(
                content=chunk_outputs[idx],
                cost=0.01,
                total_tokens=10,
                input_tokens=6,
                output_tokens=4,
                model="m",
            )

        worker.llm.chat = fake_chat

        chunks = [
            TranscriptChunk(
                index=0, content="a", start_timecode="0", end_timecode="1", word_count=1, overlap_prefix=""
            ),
            TranscriptChunk(
                index=1, content="b", start_timecode="1", end_timecode="2", word_count=1, overlap_prefix="a"
            ),
        ]
        context = {"analyst_output": ""}

        result = await worker._run_formatter_chunked(
            job_id=1,
            chunks=chunks,
            context=context,
            project_path=tmp_path,
            chunking_config={"max_parallel": 2},
        )

        raw_merged = result["output"]
        assert result["success"] is True
        assert "red, white, and blue" in raw_merged
        assert "capital was raised" in raw_merged

        persisted = (tmp_path / "formatter_output.md").read_text()
        assert persisted.endswith(raw_merged)
        assert "style-engine:" not in persisted
        assert not (tmp_path / "formatter_output.raw.md").exists()

        # Shadow must not populate style_checks (PR #295 review #4) -- events
        # are the record; the context key would leak into the validator prompt.
        assert "style_checks" not in context

        style_violation_events = [e for e in logged_events if e.event_type == EventType.style_violation]
        assert len(style_violation_events) >= 2  # oxford_comma + capitol_capital
        assert all(e.data.phase == "formatter" for e in style_violation_events)
        assert all(e.data.extra["mode"] == "shadow" for e in style_violation_events)


class TestChunkedFormatterKillSwitch:
    @pytest.mark.asyncio
    async def test_all_off_chunked_output_byte_identical(self, tmp_path, monkeypatch):
        """No `routing.style_engine` block -- the chunked persist must match
        today's format exactly: no style_pre injection, no style-engine
        provenance line, no `.raw.md` archive."""
        worker = _bare_chunked_worker()
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        async def fake_chat(**kwargs):
            return SimpleNamespace(
                content="Formatted chunk content",
                cost=0.01,
                total_tokens=10,
                input_tokens=6,
                output_tokens=4,
                model="test-model",
            )

        worker.llm.chat = fake_chat

        chunks = [
            TranscriptChunk(
                index=0,
                content="a",
                start_timecode="00:00:00",
                end_timecode="00:00:05",
                word_count=1,
                overlap_prefix="",
            ),
        ]
        context = {"analyst_output": ""}

        result = await worker._run_formatter_chunked(
            job_id=1,
            chunks=chunks,
            context=context,
            project_path=tmp_path,
            chunking_config={"max_parallel": 1},
        )

        assert result["success"] is True
        assert result["output"] == "Formatted chunk content"
        persisted = (tmp_path / "formatter_output.md").read_text()
        assert "style-engine:" not in persisted
        assert persisted.endswith("Formatted chunk content")
        assert not (tmp_path / "formatter_output.raw.md").exists()
        assert "style_pre" not in context


class TestChunkedFormatterFailOpen:
    @pytest.mark.asyncio
    async def test_post_fails_open_on_missing_rules_file(self, tmp_path, monkeypatch):
        cfg = _style_engine_cfg(
            tmp_path / "does_not_exist.yaml", phases={"formatter": {"pre": False, "post": "enforce"}}
        )
        worker = _bare_chunked_worker(cfg)
        monkeypatch.setattr(worker_mod, "log_event", AsyncMock())

        async def fake_chat(**kwargs):
            return SimpleNamespace(
                content="formatted chunk",
                cost=0.01,
                total_tokens=10,
                input_tokens=6,
                output_tokens=4,
                model="m",
            )

        worker.llm.chat = fake_chat

        chunks = [
            TranscriptChunk(
                index=0, content="a", start_timecode="0", end_timecode="1", word_count=1, overlap_prefix=""
            ),
        ]
        context = {"analyst_output": ""}

        result = await worker._run_formatter_chunked(
            job_id=1,
            chunks=chunks,
            context=context,
            project_path=tmp_path,
            chunking_config={"max_parallel": 1},
        )

        assert result["success"] is True
        assert result["output"] == "formatted chunk"
        assert (tmp_path / "formatter_output.md").read_text().endswith("formatted chunk")
        assert not (tmp_path / "formatter_output.raw.md").exists()


# ---------------------------------------------------------------------------
# 7. Project name flow through context (task 4b fix)
#
# Validates that process_job's main context dict includes project_name
# (matching retry_single_phase semantics), so style-engine emitters like
# the timestamp post-stage can render "**Project:** <name>" headers.
#
# Two tests: the first exercises the kill-switch (no routing.style_engine
# config) passthrough path -- the post-stage never runs in that mode, so it
# only proves the *prompt* sent to the LLM carries "## Project: <name>"; it
# does NOT prove anything about the persisted file's "**Project:**" header.
# The second test is the real end-to-end case -- style_engine enabled with
# timestamp {pre: false, post: "enforce"}, a slim-contract ```chapters fence
# as the mocked LLM response, and assertions against the actual persisted
# timestamp_output.md.
# ---------------------------------------------------------------------------


class TestProjectNameInContext:
    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_timestamp_phase_receives_project_name_in_context(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """Verify that the timestamp phase receives project_name in context
        from process_job's main context dict, and that the built user-message
        prompt sent to the LLM includes the project name header.

        This is a kill-switch (no routing.style_engine config) passthrough
        test -- the post-stage never runs, so this only proves the *prompt*
        carries "## Project: <name>". It does NOT prove the persisted
        timestamp_output.md contains a "**Project:**" header (that requires
        the enforce-mode post-stage to actually run and render the report --
        see test_enforce_mode_persists_project_header_and_rendered_sections
        below for that end-to-end case).
        """
        # Setup: mock LLM client without style_engine (kill-switch passthrough)
        mock_get_llm.return_value = mock_llm_client
        mock_llm_client.config = {
            "routing": {
                "long_form_threshold_minutes": 15,
            }
        }

        # Mock LLM response with timestamp report content
        timestamp_output = """# Timestamp Report

## Media Manager Format

| Chapter | Start Time | End Time |
|---------|-----------|----------|
| Introduction | 0:00:00.000 | 0:02:30.000 |
| Main Content | 0:02:30.000 | 0:15:45.000 |

## YouTube Format

0:00 Introduction
0:02:30 Main Content
"""
        mock_llm_response.content = timestamp_output
        mock_llm_response.cost = 0.002
        mock_llm_response.total_tokens = 200
        mock_llm_response.model = "timestamp-model"
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()

        # Create context WITH project_name (as process_job now provides)
        context = {
            "project_name": "Wisconsin Public Affairs",
            "transcript": "Sample transcript content for timestamp phase",
            "analyst_output": ANALYST_TABLE,
            "srt_content": """1
00:00:00,000 --> 00:00:05,000
Introduction text

2
00:02:30,000 --> 00:02:35,000
Main content text
""",
        }

        result = await worker._run_phase(job_id=1, phase_name="timestamp", context=context, project_path=tmp_path)

        assert result["success"] is True

        # Verify context still has project_name (passthrough)
        assert context.get("project_name") == "Wisconsin Public Affairs"

        # Verify the LLM was called with prompt containing project_name
        sent_messages = mock_llm_client.chat.call_args.kwargs["messages"]
        user_message = sent_messages[1]["content"]
        assert "## Project: Wisconsin Public Affairs" in user_message

        # Verify the persisted timestamp_output.md file exists and passed the
        # raw LLM content through unchanged (kill switch -- no post-stage ran,
        # so this does NOT exercise the "**Project:**" header; that's the
        # enforce-mode test below).
        timestamp_file = tmp_path / "timestamp_output.md"
        assert timestamp_file.exists()
        persisted_content = timestamp_file.read_text()
        # The persisted content should include the model attribution header
        assert "model: timestamp-model" in persisted_content
        # And the timestamp content itself
        assert "Timestamp Report" in persisted_content or "Introduction" in persisted_content

    @pytest.mark.asyncio
    @patch("api.services.worker.get_llm_client")
    @patch("api.services.worker.log_event")
    @patch("api.services.worker.AGENTS_DIR")
    async def test_enforce_mode_persists_project_header_and_rendered_sections(
        self, mock_agents_dir, mock_log_event, mock_get_llm, mock_llm_client, mock_llm_response, tmp_path
    ):
        """End-to-end enforce-mode case: routing.style_engine enabled with
        timestamp {pre: false, post: "enforce"}, the LLM returning a bare
        slim-contract ```chapters fence (no manually-typed tables/prose --
        exactly what timestamp.output_contract's slim profile instructs),
        and a real `_run_phase` call. Asserts against the actual PERSISTED
        timestamp_output.md -- the file editors copy-paste from -- not just
        the outbound prompt, proving the post-stage renders the
        "**Project:**" header plus both the Media Manager and YouTube
        sections from the model's minimal chapter list."""
        rules_path = _write_timestamp_rules(tmp_path)
        mock_llm_client.config = {
            "routing": {
                "style_engine": _style_engine_cfg(rules_path, phases={"timestamp": {"pre": False, "post": "enforce"}}),
            }
        }
        mock_get_llm.return_value = mock_llm_client

        srt_content = (
            "1\n00:00:00,000 --> 00:00:05,000\nWelcome to the show today.\n\n"
            "2\n00:09:58,000 --> 00:10:00,000\nThanks for watching, see you next time.\n"
        )
        # Bare slim-contract output: only the fenced chapters block, no
        # manually-rendered tables or prose -- the pipeline builds both
        # published sections deterministically from this.
        mock_llm_response.content = "```chapters\n2:30 Budget debate begins\n8:15 Weather turns sunny\n```"
        mock_llm_response.cost = 0.002
        mock_llm_response.total_tokens = 200
        mock_llm_response.model = "timestamp-model"
        mock_llm_client.chat = AsyncMock(return_value=mock_llm_response)
        mock_log_event.return_value = None
        mock_agents_dir.__truediv__ = lambda self, name: tmp_path / name

        worker = JobWorker()
        context = {
            "project_name": "Budget Debate 2026",
            "transcript_file": "episode.srt",
            "transcript": srt_content,
            "srt_content": srt_content,
            "analyst_output": ANALYST_TABLE,
        }

        result = await worker._run_phase(job_id=1, phase_name="timestamp", context=context, project_path=tmp_path)

        assert result["success"] is True

        timestamp_file = tmp_path / "timestamp_output.md"
        assert timestamp_file.exists()
        persisted_content = timestamp_file.read_text()

        assert "**Project:** Budget Debate 2026" in persisted_content
        assert "## Media Manager Format" in persisted_content
        assert "## YouTube Format" in persisted_content
        # Forced first chapter, prepended by the deterministic pipeline (not
        # the model -- the slim contract explicitly withholds it).
        assert "Episode intro" in persisted_content
        # The model's chapter titles, rendered into both published formats.
        assert "Budget debate begins" in persisted_content
        assert "Weather turns sunny" in persisted_content
        assert "2:30 Budget debate begins" in persisted_content
        assert "8:15 Weather turns sunny" in persisted_content


# ---------------------------------------------------------------------------
# 8. Timestamp user-message prompt profile-awareness (review fix)
#
# `_build_phase_prompt_base`'s timestamp branch used to hardcode a "TWO
# sections" instruction that directly contradicts the slim system-prompt
# contract ({{style:timestamp.output_contract}}'s slim profile says "Output
# ONLY a fenced code block labeled `chapters`") once
# routing.style_engine.phases.timestamp.post is "enforce". Verifies the
# user message defers to the system instructions under slim and keeps the
# original two-section instruction under full (including "off"/absent
# config and non-enforce "shadow" mode, both of which resolve to "full").
# ---------------------------------------------------------------------------


class TestTimestampUserMessagePromptProfile:
    def _worker_with_style_cfg(self, style_engine_cfg: dict | None) -> JobWorker:
        worker = JobWorker.__new__(JobWorker)
        worker.llm = MagicMock()
        worker.llm.config = {"routing": {"style_engine": style_engine_cfg or {}}}
        return worker

    def _base_context(self) -> dict:
        return {
            "project_name": "Test Project",
            "srt_content": "1\n00:00:00,000 --> 00:00:05,000\nHello.\n",
            "analyst_output": ANALYST_TABLE,
            "transcript_metrics": {},
        }

    def test_full_profile_includes_two_sections_instruction(self):
        # No routing.style_engine block -- kill-switch default resolves to "full".
        worker = self._worker_with_style_cfg(None)
        prompt = worker._build_phase_prompt_base("timestamp", self._base_context())
        assert "Output a timestamp report with TWO sections:" in prompt
        assert "Media Manager Format" in prompt
        assert "YouTube Format" in prompt
        assert "Select chapter boundaries and titles per the output contract" not in prompt

    def test_slim_profile_omits_two_sections_instruction(self):
        style_cfg = {"enabled": True, "phases": {"timestamp": {"post": "enforce"}}}
        worker = self._worker_with_style_cfg(style_cfg)
        prompt = worker._build_phase_prompt_base("timestamp", self._base_context())
        assert "TWO sections" not in prompt
        assert "Media Manager Format" not in prompt
        assert "YouTube Format" not in prompt
        assert "Select chapter boundaries and titles per the output contract in your instructions." in prompt

    def test_shadow_mode_still_uses_full_profile(self):
        # resolve_prompt_profile only returns "slim" for mode == "enforce" --
        # shadow mode (record-only) must keep the full two-section instruction.
        style_cfg = {"enabled": True, "phases": {"timestamp": {"post": "shadow"}}}
        worker = self._worker_with_style_cfg(style_cfg)
        prompt = worker._build_phase_prompt_base("timestamp", self._base_context())
        assert "Output a timestamp report with TWO sections:" in prompt


# ---------------------------------------------------------------------------
# 9. _load_agent_prompt graceful fallback (review fix #1, PR #295)
#
# Prompt-block token rendering is LIVE on every phase run -- all five phase
# prompts carry {{style:*}} tokens and _load_agent_prompt calls
# render_prompt_blocks unconditionally. A missing/corrupt house-style YAML
# must NOT fail the phase (fail-fast here fails every job); it degrades to the
# raw prompt with tokens stripped. A boot-time check (validate_prompt_blocks,
# wired into main.lifespan) catches a broken file loudly at deploy instead.
# ---------------------------------------------------------------------------


class TestLoadAgentPromptFallback:
    def test_unrenderable_rules_file_strips_tokens_instead_of_raising(self, tmp_path, monkeypatch):
        (tmp_path / "seo.md").write_text("You are the SEO agent.\n{{style:seo.copy_rules}}\nWrite a title.")
        monkeypatch.setattr(worker_mod, "AGENTS_DIR", tmp_path)

        worker = JobWorker.__new__(JobWorker)
        worker.llm = MagicMock()
        worker.llm.config = {
            "routing": {
                "style_engine": {
                    "enabled": True,
                    "rules_file": str(tmp_path / "missing.yaml"),
                    "phases": {"seo": {"post": "enforce"}},
                }
            }
        }
        warning_calls = []
        monkeypatch.setattr(worker_mod.logger, "warning", lambda *a, **kw: warning_calls.append((a, kw)))

        result = worker._load_agent_prompt("seo")

        # No raise; token stripped; surrounding prompt text preserved.
        assert "{{style:" not in result
        assert "You are the SEO agent." in result
        assert "Write a title." in result
        assert warning_calls, "fail-open must log a warning for observability"

    def test_valid_rules_file_still_renders_tokens(self, tmp_path, monkeypatch):
        # Regression guard: a healthy YAML must still REPLACE tokens (not strip).
        (tmp_path / "seo.md").write_text("Intro.\n{{style:voice_rules}}\n")
        rules = tmp_path / "house_style.yaml"
        rules.write_text('meta: {version: 1}\nprompt_blocks:\n  voice_rules:\n    full: "No viewer directives."\n')
        monkeypatch.setattr(worker_mod, "AGENTS_DIR", tmp_path)

        worker = JobWorker.__new__(JobWorker)
        worker.llm = MagicMock()
        worker.llm.config = {
            "routing": {
                "style_engine": {
                    "enabled": True,
                    "rules_file": str(rules),
                    "phases": {"seo": {"post": "shadow"}},
                }
            }
        }

        result = worker._load_agent_prompt("seo")

        assert "No viewer directives." in result
        assert "{{style:" not in result
